import { PatientData } from '../types/cdss';

export interface SampleCase {
  id: string;
  title: string;
  subtitle: string;
  badge: string;
  data: PatientData;
}

export const SAMPLE_CASES: SampleCase[] = [
  {
    id: 'steroid-case',
    title: 'Ca 1: ĐTĐ Típ 2 + Dùng Corticoid',
    subtitle: 'Đang dùng Prednisolone 20mg sáng, ĐH chiều tối tăng cao',
    badge: 'Corticoid / Kháng Insulin',
    data: {
      id: 'CA-01',
      patientName: 'Ca 1 (Corticoid)',
      age: 62,
      gender: 'male',
      weightKg: 68,
      heightCm: 168,
      diabetesType: 'T2D',
      wardType: 'NON_ICU',
      dietType: 'ORAL_FULL',
      currentGlucose: 245,
      unit: 'mg_dl',
      fastingGlucose: 155,
      hba1c: 8.2,
      egfr: 65,
      creatinine: 95,
      potassium: 4.3,
      bloodKetones: 0.3,
      venousPh: 7.38,
      bicarbonate: 23,
      sodium: 137,
      chloride: 101,
      urea: 6.2,
      isTakingSteroids: true,
      steroidType: 'prednisolone',
      steroidDoseMg: 20,
      steroidSchedule: 'morning_once',
      isScheduledSurgery: false,
      isOnDialysis: false,
      currentOralMeds: ['metformin'],
      isPriorInsulinTreated: false,
      isOnIVInsulin: false,
    },
  },
  {
    id: 'surgery-case',
    title: 'Ca 2: Chu phẫu mổ sỏi mật',
    subtitle: 'Nhịn ăn mổ phiên sáng mai, đang dùng SGLT2i + Metformin',
    badge: 'Chu phẫu / Nhịn ăn',
    data: {
      id: 'CA-02',
      patientName: 'Ca 2 (Chu phẫu)',
      age: 58,
      gender: 'female',
      weightKg: 64,
      heightCm: 156,
      diabetesType: 'T2D',
      wardType: 'NON_ICU',
      dietType: 'NPO',
      currentGlucose: 172,
      unit: 'mg_dl',
      fastingGlucose: 142,
      hba1c: 7.8,
      egfr: 58,
      creatinine: 88,
      potassium: 4.1,
      bloodKetones: 0.2,
      venousPh: 7.41,
      bicarbonate: 24,
      sodium: 138,
      chloride: 102,
      urea: 5.5,
      isTakingSteroids: false,
      isScheduledSurgery: true,
      surgeryFastingExpectedMeals: 'more_than_one',
      isOnDialysis: false,
      currentOralMeds: ['metformin', 'dapagliflozin'],
      isPriorInsulinTreated: true,
      priorHomeTdd: 34,
      isOnIVInsulin: false,
    },
  },
  {
    id: 'dialysis-case',
    title: 'Ca 3: Suy thận chạy thận nhân tạo (mHDx)',
    subtitle: 'Ngày lọc máu chu kỳ, giảm 25% liều insulin để ngừa hạ đường huyết',
    badge: 'Lọc máu chu kỳ',
    data: {
      id: 'CA-03',
      patientName: 'Ca 3 (Chạy thận)',
      age: 71,
      gender: 'male',
      weightKg: 60,
      heightCm: 165,
      diabetesType: 'T2D',
      wardType: 'NON_ICU',
      dietType: 'ORAL_FULL',
      currentGlucose: 185,
      unit: 'mg_dl',
      fastingGlucose: 130,
      hba1c: 7.4,
      egfr: 12,
      creatinine: 480,
      potassium: 4.8,
      bloodKetones: 0.4,
      venousPh: 7.34,
      bicarbonate: 21,
      sodium: 135,
      chloride: 99,
      urea: 18.5,
      isTakingSteroids: false,
      isScheduledSurgery: false,
      isOnDialysis: true,
      dialysisType: 'hemodialysis',
      isDialysisDay: true,
      currentOralMeds: ['linagliptin'],
      isPriorInsulinTreated: true,
      priorHomeTdd: 28,
      isOnIVInsulin: false,
    },
  },
  {
    id: 'dka-case',
    title: 'Ca 4: ĐTĐ Típ 1 Cấp cứu Toan Ceton (DKA)',
    subtitle: 'Sốt cao, nôn ói, ĐH 24 mmol/L, Ceton máu 4.6 mmol/L, toan chuyển hóa',
    badge: 'Cấp cứu DKA',
    data: {
      id: 'CA-04',
      patientName: 'Ca 4 (Cấp cứu DKA)',
      age: 26,
      gender: 'male',
      weightKg: 55,
      heightCm: 170,
      diabetesType: 'T1D',
      wardType: 'ICU',
      dietType: 'NPO',
      currentGlucose: 432,
      unit: 'mg_dl',
      fastingGlucose: 432,
      hba1c: 11.2,
      egfr: 85,
      creatinine: 110,
      potassium: 4.7,
      bloodKetones: 4.6,
      venousPh: 7.15,
      bicarbonate: 11,
      sodium: 132,
      chloride: 98,
      urea: 9.8,
      isTakingSteroids: false,
      isScheduledSurgery: false,
      isOnDialysis: false,
      currentOralMeds: [],
      isPriorInsulinTreated: true,
      priorHomeTdd: 42,
      isOnIVInsulin: true,
      ivRateLast6hAvg: 5.5,
    },
  },
  {
    id: 'hypo-case',
    title: 'Ca 5: Hạ đường huyết mức 2 (< 54 mg/dL)',
    subtitle: 'Vã mồ hôi, run tay, ĐH 50 mg/dL (2.8 mmol/L), đang dùng Gliclazide',
    badge: 'Báo động Hạ ĐH',
    data: {
      id: 'CA-05',
      patientName: 'Ca 5 (Hạ đường huyết)',
      age: 74,
      gender: 'female',
      weightKg: 50,
      heightCm: 150,
      diabetesType: 'T2D',
      wardType: 'NON_ICU',
      dietType: 'ORAL_POOR',
      currentGlucose: 50,
      unit: 'mg_dl',
      fastingGlucose: 50,
      hba1c: 6.7,
      egfr: 38,
      creatinine: 135,
      potassium: 3.9,
      bloodKetones: 0.1,
      venousPh: 7.42,
      bicarbonate: 25,
      sodium: 136,
      chloride: 103,
      urea: 7.8,
      isTakingSteroids: false,
      isScheduledSurgery: false,
      isOnDialysis: false,
      currentOralMeds: ['gliclazide'],
      isPriorInsulinTreated: false,
      isOnIVInsulin: false,
    },
  },
  {
    id: 'premix-case',
    title: 'Ca 6: ĐTĐ Típ 2 + Phác Đồ Insulin Trộn Sẵn',
    subtitle: 'Bệnh nhân ổn định, ăn uống đúng giờ, dùng Premix 2 cữ Sáng - Chiều',
    badge: 'Insulin Trộn (Premix 70/30)',
    data: {
      id: 'CA-06',
      patientName: 'Ca 6 (Premix 70/30)',
      age: 59,
      gender: 'male',
      weightKg: 65,
      heightCm: 165,
      diabetesType: 'T2D',
      wardType: 'NON_ICU',
      dietType: 'ORAL_FULL',
      userPreferredRegimen: 'PREMIX',
      currentGlucose: 185,
      unit: 'mg_dl',
      fastingGlucose: 135,
      hba1c: 8.0,
      egfr: 72,
      creatinine: 88,
      potassium: 4.1,
      bloodKetones: 0.2,
      venousPh: 7.39,
      bicarbonate: 24,
      sodium: 138,
      chloride: 102,
      urea: 5.4,
      isTakingSteroids: false,
      isScheduledSurgery: false,
      isOnDialysis: false,
      currentOralMeds: [],
      isPriorInsulinTreated: true,
      priorHomeTdd: 30,
      isOnIVInsulin: false,
    },
  },
];
