-- ==============================================================================
-- MedLens DocSpace Pro — Supabase Database Schema
-- Tích hợp Hồ sơ Bác sĩ, Quản lý Bệnh nhân & Bệnh án Lâm sàng MedLens
-- ==============================================================================

-- 1. Bảng Doctors (Hồ sơ Bác sĩ)
create table if not exists public.doctors (
  id uuid primary key default gen_random_uuid(),
  uid text unique not null,
  email text unique not null,
  name text not null default 'Bác sĩ lâm sàng',
  role text not null default 'doctor',
  specialty text default 'Nội tổng quát & Cấp cứu',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Bảng Patients (Danh mục Bệnh nhân)
create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  patient_code text unique not null,
  full_name text not null,
  gender text not null default 'nam', -- 'nam' | 'nu' | 'khac'
  age integer,
  occupation text,
  phone_number text,
  id_card text,
  address text,
  notes text,
  created_by_uid text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Bảng Medical Records (Hồ sơ Bệnh án & Kết quả Phân tích MedLens)
create table if not exists public.medical_records (
  id bigint generated by default as identity primary key,
  record_code text unique not null,
  patient_id bigint references public.patients(id) on delete set null,
  patient_code text not null,
  patient_name text not null,
  gender text not null default 'nam',
  age integer,
  occupation text,
  doctor_uid text not null default 'dr_default',
  doctor_name text default 'Bác sĩ lâm sàng',
  admission_reason text,
  clinical_summary text,
  vitals jsonb default '{}'::jsonb,
  labs jsonb default '{}'::jsonb,
  selected_symptoms jsonb default '[]'::jsonb,
  derived_symptoms jsonb default '[]'::jsonb,
  negated_symptoms jsonb default '[]'::jsonb,
  free_texts jsonb default '{}'::jsonb,
  primary_diagnosis jsonb default '{}'::jsonb,
  differential_diagnoses jsonb default '[]'::jsonb,
  treatment_protocol jsonb default '{}'::jsonb,
  status text not null default 'hoan_tat', -- 'dang_kham' | 'hoan_tat' | 'chuyen_vien'
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Indexes tối ưu truy vấn
create index if not exists idx_patients_code on public.patients(patient_code);
create index if not exists idx_patients_name on public.patients(full_name);
create index if not exists idx_records_code on public.medical_records(record_code);
create index if not exists idx_records_patient_code on public.medical_records(patient_code);
create index if not exists idx_records_doctor on public.medical_records(doctor_uid);
create index if not exists idx_records_created on public.medical_records(created_at desc);

-- Row Level Security (RLS)
alter table public.doctors enable row level security;
alter table public.patients enable row level security;
alter table public.medical_records enable row level security;

-- Policies: Cho phép đọc/ghi qua Anon key và Authenticated user (Client-friendly)
create policy "Allow all access to doctors" on public.doctors for all using (true) with check (true);
create policy "Allow all access to patients" on public.patients for all using (true) with check (true);
create policy "Allow all access to medical_records" on public.medical_records for all using (true) with check (true);

-- Dữ liệu Bác sĩ mẫu
insert into public.doctors (uid, email, name, role, specialty)
values ('dr_demo_01', 'dr.minh@medlens.vn', 'BS.CKII Nguyễn Văn Minh', 'specialist', 'Tim mạch Can thiệp & Cấp cứu')
on conflict (uid) do nothing;

-- ==============================================================================
-- 4. Bảng SOAP Clinical Experiences (Sổ tay Đúc kết Kinh nghiệm Lâm sàng Chuẩn SOAP)
-- Lưu ý: Không lưu trữ thông tin nhận diện bệnh nhân (Không có họ tên, CMND, địa chỉ)
-- ==============================================================================
create table if not exists public.soap_clinical_experiences (
  id text primary key,
  title text not null,
  specialty text not null default 'Tim mạch',
  experience_level text not null default 'essential', -- 'essential' | 'pitfall' | 'rare' | 'advanced'
  tags jsonb default '[]'::jsonb,
  demographic_context text, -- Ví dụ: "Bệnh nhân 68 tuổi, tiền căn ĐTĐ 12 năm"
  author_doctor text default 'Bác sĩ lâm sàng',
  is_favorite boolean default false,
  view_count integer default 0,
  source_reference text, -- Guideline, Sách, Ca lâm sàng thực tế
  clinical_context text default 'Khoa Cấp cứu', -- Bối cảnh khoa phòng
  difficulty_rating integer default 3 check (difficulty_rating between 1 and 5), -- Độ khó 1-5
  outcome_notes text, -- Kết cục ca bệnh & Di chứng nếu có
  s jsonb not null default '{}'::jsonb, -- Subjective
  o jsonb not null default '{}'::jsonb, -- Objective
  a jsonb not null default '{}'::jsonb, -- Assessment
  p jsonb not null default '{}'::jsonb, -- Plan
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Bổ sung cột cho table đã tạo từ trước (Migration Safe)
alter table public.soap_clinical_experiences
  add column if not exists view_count integer default 0,
  add column if not exists source_reference text,
  add column if not exists clinical_context text default 'Khoa Cấp cứu',
  add column if not exists difficulty_rating integer default 3 check (difficulty_rating between 1 and 5),
  add column if not exists outcome_notes text;

create index if not exists idx_soap_specialty on public.soap_clinical_experiences(specialty);
create index if not exists idx_soap_level on public.soap_clinical_experiences(experience_level);
create index if not exists idx_soap_created on public.soap_clinical_experiences(created_at desc);
create index if not exists idx_soap_tags on public.soap_clinical_experiences using gin(tags);

alter table public.soap_clinical_experiences enable row level security;
create policy "Allow all access to soap_clinical_experiences" on public.soap_clinical_experiences for all using (true) with check (true);

