/**
 * CliniPortal 2.0 — Kho Guidelines Static Metadata Registry
 * Path: src/content/ebm/guidelines/kho-guidelines-registry.ts
 *
 * Cung cấp metadata phân loại chi tiết (Design, Specialty, Impact, ICD-10, ConditionKey)
 * cho toàn bộ tài liệu lâm sàng trong thư mục kho-guidelines/
 * Dùng làm nguồn dữ liệu EBM cơ sở cho SOAP & Tra cứu EBM nhanh.
 */

import { Study } from './guidelines-types';

export const KHO_GUIDELINES_STATIC: Study[] = [
  // --- TIM MẠCH & CHUYỂN HÓA (CARDIO / METABOLIC) ---
  {
    id: '2026-esc-hf-p1',
    title: 'ESC 2026: Khuyến cáo Chẩn đoán & Điều trị Suy tim Mạn (Phần 1: Định nghĩa, Kiểu hình & Phác đồ Nội khoa)',
    titleEn: '2026 ESC Guidelines for the management of heart failure (Part 1: Definitions, Phenotypes & Medical Therapy)',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Hội Tim mạch Châu Âu (ESC)',
    journal: 'Eur Heart J',
    file: '2026-esc-heart-failure-p1.html',
    conditionKey: 'heart-failure',
    icd10: ['I50', 'I50.1', 'I50.2', 'I50.9'],
    intervention: 'Xóa bỏ HFmrEF, Tái phân loại HFrEF (LVEF <50%) & HFpEF (≥50%), FMT Tứ trụ & Nhị trụ, Khởi trị đồng thời & Tăng liều nhanh 6 tuần (STRONG-HF), GLP-1 RA, Sắt IV',
    primaryEndpoint: 'Giảm tử vong do mọi nguyên nhân, tử vong tim mạch và tái nhập viện do suy tim',
    keyResults: 'Tứ trụ FMT HFrEF (ACEi/ARNI + BB + MRA + SGLT2i) & Nhị trụ FMT HFpEF (SGLT2i + MRA) đều đạt Class I. STRONG-HF giảm 34% tử vong/tái nhập viện tại 180 ngày.',
    summary: 'Cuộc cách mạng chẩn đoán và điều trị suy tim ESC 2026: Xóa bỏ phân nhóm HFmrEF, phân tầng giai đoạn Stages A-D, quy trình chẩn đoán ngoại trú, bảng liều chuẩn Table 11 và cơ sở dữ liệu 12+ thử nghiệm RCT bản lề.',
    detailedConclusion: 'Bắt buộc khởi trị đồng thời và tối ưu hóa liều tối đa FMT trong vòng 6 tuần đầu sau xuất viện; duy trì FMT trọn đời ở bệnh nhân có LVEF cải thiện (TRED-HF).'
  },
  {
    id: '2026-esc-hf-p2',
    title: 'ESC 2026: Khuyến cáo Chẩn đoán & Điều trị Suy tim (Phần 2: Suy tim mất bù, Thiết bị, Can thiệp & Giai đoạn D)',
    titleEn: '2026 ESC Guidelines for the management of heart failure (Part 2: Decompensated HF, Devices, Interventions & Advanced HF)',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Hội Tim mạch Châu Âu (ESC)',
    journal: 'Eur Heart J',
    file: '2026-esc-heart-failure-p2.html',
    conditionKey: 'heart-failure',
    icd10: ['I50', 'I50.1', 'I50.9', 'E85.8'],
    intervention: 'Suy tim mất bù (DHF), Giải áp sung huyết định hướng Natri niệu (uNa+ ≥70 mmol/L), ICD & CRT (Class I, A), Mitral TEER (COAPT-like), CABG/PCI, Trúng đích ATTR-CA, Durable LVAD & Ghép tim',
    primaryEndpoint: 'Giải áp sung huyết hoàn toàn, giảm biến cố đột tử, giảm tái nhập viện và kéo dài sống còn trong suy tim nặng',
    keyResults: 'Lợi tiểu định hướng uNa+ phối hợp Acetazolamide/Thiazide; CRT giảm tử vong ở LBBB QRS ≥150ms; Mitral TEER Class I; Tafamidis/Vutrisiran Class I trong ATTR-CA.',
    summary: 'Phác đồ hồi sức DHF nội viện 4 pha, giải áp sung huyết theo Natri niệu, chỉ định cấy ICD/CRT, can thiệp van tim & mạch vành, chẩn đoán không xâm lấn ATTR-CA, phân tầng Stage D theo INTERMACS và Chăm sóc giảm nhẹ.',
    detailedConclusion: 'Đánh giá trạng thái khô trước xuất viện (CSI=0, LUS, IVC); hội chẩn Shock Team cho sốc tim; chuyển viện sớm trung tâm chuyên sâu khi có dấu hiệu I NEED HELP.'
  },
  {
    id: '2024-esc-af',
    title: 'ESC 2024 Guidelines: Chẩn đoán và Quản lý Rung nhĩ (AF)',
    titleEn: '2024 ESC Guidelines for the management of atrial fibrillation',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2024,
    organization: 'Hội Tim mạch Châu Âu (ESC)',
    journal: 'Eur Heart J',
    file: '2024-esc-atrial-fibrillation.html',
    conditionKey: 'af',
    icd10: ['I48', 'I48.0', 'I48.9'],
    intervention: 'Chiến lược CARE (Comorbidity, Avoid stroke/DOAC, Reduce symptoms, Evaluate/Monitor), Kháng đông DOAC, Kiểm soát nhịp/tần số',
    primaryEndpoint: 'Giảm đột quỵ thiếu máu não, tử vong tim mạch, cải thiện chất lượng sống',
    summary: 'Khuyến cáo thực hành toàn diện về rung nhĩ: Phân tầng CHA2DS2-VA (bỏ giới tính), ưu tiên DOAC hơn VKA, chỉ định triệt đốt catheter sớm, quản lý bệnh đồng mắc tích cực.',
    detailedConclusion: 'Áp dụng đường dẫn AF-CARE: Kiểm soát yếu tố nguy cơ tim mạch, kháng đông đường uống DOAC cho hầu hết bệnh nhân có điểm nguy cơ, kiểm soát tần số tim < 110 bpm lúc nghỉ.'
  },
  {
    id: '2025-aha-acc-hypertension',
    title: 'AHA/ACC 2025: Hướng dẫn Quản lý và Điều trị Tăng huyết áp Toàn diện',
    titleEn: '2025 AHA/ACC/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2025,
    organization: 'AHA/ACC',
    journal: 'Circulation',
    file: '2025-aha-acc-hypertension.html',
    conditionKey: 'hypertension',
    icd10: ['I10', 'I11', 'I15'],
    intervention: 'Phối hợp thuốc hạ áp liều cố định sớm (SPC: ACEi/ARB + CCB/Thiazide-like), mục tiêu HA < 130/80 mmHg, lối sống DASH',
    primaryEndpoint: 'Giảm biến cố tim mạch chính (MACE), tử vong tim mạch, đột quỵ và suy thận',
    summary: 'Ngưỡng chẩn đoán THA ≥ 130/80 mmHg. Khởi trị phối hợp đôi (Single Pill Combination) ngay từ độ 1 có nguy cơ hoặc độ 2. Tối ưu hóa hạ áp ban đêm.',
    detailedConclusion: 'Mục tiêu chung < 130/80 mmHg cho đa số bệnh nhân; ưu tiên dạng viên phối hợp liều cố định để tăng tuân thủ; theo dõi HA tại nhà (HBPM).'
  },
  {
    id: '2015-nejm-empareg-outcome',
    title: 'EMPA-REG OUTCOME: Thử nghiệm lâm sàng Empagliflozin trên biến cố tim mạch ở BN ĐTĐ típ 2',
    titleEn: 'Empagliflozin, Cardiovascular Outcomes, and Mortality in Type 2 Diabetes',
    sourceType: 'intl-study',
    specialty: 'cardio',
    design: 'rct',
    impact: 'practice-changing',
    year: 2015,
    organization: 'Boehringer Ingelheim & Eli Lilly / NEJM',
    journal: 'N Engl J Med',
    file: '2015-nejm-empareg-outcome.html',
    conditionKey: 'heart-failure',
    icd10: ['E11', 'I50', 'I25'],
    intervention: 'Empagliflozin 10mg hoặc 25mg/ngày vs Placebo trên nền điều trị chuẩn',
    primaryEndpoint: '3-point MACE (Tử vong do tim mạch, nhồi máu cơ tim không tử vong, đột quỵ không tử vong)',
    keyResults: 'Giảm 14% 3-point MACE (HR 0.86, p=0.04), giảm 38% tử vong tim mạch (HR 0.62, p<0.001), giảm 35% nhập viện vì suy tim (HR 0.65, p=0.002).',
    summary: 'Cột mốc lịch sử mở ra kỷ nguyên SGLT2i trong bảo vệ tim mạch - thận bất kể tình trạng kiểm soát đường huyết.',
    detailedConclusion: 'SGLT2i là trụ cột bắt buộc ở bệnh nhân ĐTĐ típ 2 kèm bệnh tim mạch xơ vữa hoặc suy tim nhằm giảm tử vong và nhập viện.'
  },
  {
    id: '2026-aha-acc-ckm',
    title: 'AHA/ACC 2026: Hội chứng Tim mạch - Thận - Chuyển hóa (CKM Syndrome)',
    titleEn: 'Cardiovascular-Kidney-Metabolic (CKM) Syndrome: A Presidential Advisory',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'American Heart Association (AHA)',
    journal: 'Circulation',
    file: '2026-aha-acc-ckm-syndrome.html',
    conditionKey: 'cad',
    icd10: ['E11', 'I50', 'N18', 'E66'],
    intervention: 'Phân tầng 5 giai đoạn CKM (Giai đoạn 0-4), đa trị liệu sớm SGLT2i, GLP-1RA, Finerenone, Statin, ức chế RAAS',
    primaryEndpoint: 'Phòng ngừa tiến triển suy tim, suy thận giai đoạn cuối và tử vong tim mạch',
    summary: 'Khung tiếp cận hợp nhất sức khỏe tim mạch, thận và chuyển hóa; sàng lọc eGFR + UACR định kỳ; cá thể hóa can thiệp theo giai đoạn CKM.',
    detailedConclusion: 'Tích hợp SGLT2i và GLP-1RA/nsMRA từ sớm ở giai đoạn 2 và 3 để làm chậm suy thoái cơ quan đích.'
  },
  {
    id: '2026-jcva-soc-tim',
    title: 'JCVA 2026: Hồi sức và Tiếp cận Sốc tim (Cardiogenic Shock) Đa mô thức',
    titleEn: 'Multidisciplinary Management of Cardiogenic Shock in the Modern Era',
    sourceType: 'intl-guideline',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Society of Cardiovascular Anesthesiologists',
    journal: 'Intensive Care Med',
    file: '2026-jcva-soc-tim.html',
    conditionKey: 'heart-failure',
    icd10: ['R57.0', 'I50', 'I21'],
    intervention: 'Phân loại SCAI shock stage A-E, theo dõi PAC/huyết động xâm lấn, can thiệp MCS (ECMO, Impella, IABP) sớm',
    primaryEndpoint: 'Sống còn 30 ngày, phục hồi tưới máu mô và chức năng thất',
    summary: 'Nhấn mạnh kích hoạt Shock Team nhanh chóng, phân loại SCAI, hồi sức thuốc vận mạch/tăng co bóp có định hướng huyết động (Norepinephrine + Dobutamine/Milrinone).',
    detailedConclusion: 'Hạ lactate, duy trì MAP ≥ 65 mmHg, cân nhắc hỗ trợ tuần hoàn cơ học (MCS) sớm trước khi suy đa tạng không hồi phục.'
  },
  {
    id: '2026-dash-diet-hypertension',
    title: 'Tổng quan Chế độ ăn DASH và Can thiệp Lối sống trong Kiểm soát Huyết áp',
    titleEn: 'DASH Dietary Pattern and Lifestyle Modifications for Blood Pressure Control',
    sourceType: 'intl-study',
    specialty: 'cardio',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'AHA / NHLBI',
    journal: 'Circulation',
    file: '2026-dash-diet-hypertension.html',
    conditionKey: 'hypertension',
    icd10: ['I10', 'E66'],
    intervention: 'Chế độ ăn giàu rau quả, kali, giảm natri (< 2300mg/ngày, tối ưu < 1500mg/ngày), hạn chế rượu bia',
    primaryEndpoint: 'Mức giảm HA tâm thu và tâm trương',
    summary: 'Chế độ ăn DASH kết hợp giảm muối giúp giảm huyết áp tâm thu 8-14 mmHg, tương đương hiệu quả của 1 loại thuốc hạ áp đơn trị liệu.',
    detailedConclusion: 'Khuyến cáo áp dụng cho mọi giai đoạn THA và tiền THA.'
  },
  {
    id: '2026-nejm-ngat',
    title: 'NEJM 2026: Tiếp cận và Phân tầng Nguy cơ Ngất (Syncope) tại Cấp cứu',
    titleEn: 'Evaluation and Management of Syncope in the Emergency Department',
    sourceType: 'intl-study',
    specialty: 'cardio',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'NEJM Review Article',
    journal: 'N Engl J Med',
    file: '2026-nejm-ngat.html',
    conditionKey: 'cad',
    icd10: ['R55', 'I45', 'I49'],
    intervention: 'Phân tầng nguy cơ cao (Red flags ECG/lâm sàng), siêu âm tim, theo dõi Holter, nghiệm pháp bàn nghiêng',
    primaryEndpoint: 'Phát hiện nguyên nhân tim mạch đe dọa tính mạng (loạn nhịp, hẹp van nặng, bệnh cơ tim)',
    summary: 'Quy trình tiếp cận ngất tại khoa cấp cứu: Phân biệt ngất do phản xạ, hạ HA tư thế và ngất do nguyên nhân tim mạch; tiêu chí chỉ định nhập viện an toàn.',
    detailedConclusion: 'Bệnh nhân có cờ đỏ tim mạch hoặc bất thường ECG cần nhập viện theo dõi telemetry và làm siêu âm tim khẩn.'
  },

  // --- HÔ HẤP & BỆNH PHỔI (PULMONOLOGY) ---
  {
    id: '2026-byt-viem-phoi-cong-dong',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Viêm phổi Mắc phải Cộng đồng ở Người lớn',
    titleEn: 'National Guidelines on Management of Community-Acquired Pneumonia in Adults',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-viem-phoi-cong-dong.html',
    conditionKey: 'pneumonia',
    icd10: ['J18', 'J18.9', 'J15', 'J13'],
    intervention: 'Phân tầng CURB-65 / CRB-65 / PSI, phác đồ kháng sinh kinh nghiệm (Amoxicillin/Clavulanate + Macrolide hoặc FQ hô hấp), cấy vi sinh',
    primaryEndpoint: 'Tỷ lệ lui bệnh lâm sàng, hạ sốt, giảm tỷ lệ tử vong và biến chứng SHH',
    summary: 'Hướng dẫn chuẩn quốc gia về CAP: Chỉ định nhập viện ngoại trú/nội trú/ICU theo CURB-65, thời điểm chuyển kháng sinh uống, quản lý CAP nặng kèm cờ đỏ.',
    detailedConclusion: 'Bệnh nhân ngoại trú: Beta-lactam phối hợp Macrolide hoặc Doxycycline; nội trú thường: Beta-lactam tiêm + Macrolide/FQ; ICU: Beta-lactam phổ rộng + FQ/Macrolide ± Kháng MRSA/Pseudomonas nếu có yếu tố nguy cơ.'
  },
  {
    id: '2023-nejm-cape-cod-hydrocortisone-severe-cap',
    title: 'CAPE COD: Thử nghiệm Lâm sàng Hydrocortisone trong Viêm Phổi Mắc Phải Cộng Đồng Nặng (SCAP)',
    titleEn: 'Hydrocortisone in Severe Community-Acquired Pneumonia (CAPE COD Trial)',
    sourceType: 'intl-study',
    specialty: 'pulmo',
    design: 'rct',
    impact: 'practice-changing',
    year: 2023,
    organization: 'Mạng lưới Nghiên cứu CRICS-TriGGERSep (Pháp) / NEJM',
    journal: 'N Engl J Med',
    file: '2023-nejm-cape-cod-hydrocortisone-severe-cap.html',
    conditionKey: 'pneumonia',
    icd10: ['J18.9', 'J18.0', 'J96.0'],
    intervention: 'Hydrocortisone 200 mg/ngày truyền tĩnh mạch liên tục trong 4 ngày đầu -> giảm liều 8-14 ngày vs Placebo trên nền điều trị chuẩn tại ICU',
    primaryEndpoint: 'Tử vong do mọi nguyên nhân ở ngày thứ 28 (Day 28 all-cause mortality)',
    keyResults: 'Giảm 5.6% tử vong ngày 28 (6.2% vs 11.9%, P=0.006); giảm 41% đặt nội khí quản (HR 0.59); giảm 41% khởi đầu dùng vận mạch (HR 0.59); an toàn không tăng nhiễm trùng bệnh viện hay xuất huyết tiêu hóa.',
    summary: 'Thử nghiệm pha 3 ngẫu nhiên mù đôi bản lề chứng minh liệu pháp hydrocortisone truyền liên tục sớm (bắt đầu < 15 giờ sau nhập ICU) giúp cải thiện rõ rệt sống còn ở bệnh nhân SCAP nặng nhập ICU không có sốc nhiễm trùng ban đầu.',
    detailedConclusion: 'Chỉ định Hydrocortisone 200 mg/ngày truyền liên tục sớm cho bệnh nhân SCAP nhập ICU có PaO2/FiO2 < 300 hoặc PSI > 130 không có sốc nhiễm trùng hay cúm để giảm tử vong và giảm nguy cơ đặt ống thở máy.'
  },
  {
    id: '2026-byt-copd',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Bệnh phổi Tắc nghẽn Mạn tính (COPD)',
    titleEn: 'National Guidelines on Management of Chronic Obstructive Pulmonary Disease',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-copd.html',
    conditionKey: 'copd',
    icd10: ['J44', 'J44.0', 'J44.1', 'J44.9'],
    intervention: 'Phân nhóm GOLD ABE, đo chức năng thông khí (FEV1/FVC < 0.70 sau test giãn phế quản), điều trị bộ ba LAMA+LABA+ICS, xử trí đợt cấp (SABA/SAMA + Corticosteroid toàn thân + Kháng sinh)',
    primaryEndpoint: 'Giảm đợt cấp, bảo tồn chức năng phổi, giảm tử vong',
    summary: 'Cập nhật GOLD ABE, vai trò đếm bạch cầu ái toan máu (Eosinophils) định hướng chỉ định ICS, kỹ thuật hít dụng cụ và phục hồi chức năng hô hấp.',
    detailedConclusion: 'Đợt cấp COPD: Khí dung SABA+SAMA, Prednisolone 40mg/ngày x 5 ngày, kháng sinh khi có đủ 3 triệu chứng Anthonisen hoặc cần thở máy.'
  },
  {
    id: '2026-gina-asthma',
    title: 'GINA 2026: Chiến lược Toàn cầu về Quản lý và Phòng ngừa Hen suyễn (Asthma)',
    titleEn: 'Global Strategy for Asthma Management and Prevention (GINA 2026)',
    sourceType: 'intl-guideline',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Global Initiative for Asthma (GINA)',
    journal: 'Eur Respir J',
    file: '2026-gina-asthma.html',
    conditionKey: 'asthma',
    icd10: ['J45', 'J45.0', 'J45.9'],
    intervention: 'Đường dẫn 1 (Ưu tiên): ICS-Formoterol cắt cơn và duy trì (MART); Đường dẫn 2: SABA cắt cơn + ICS duy trì; Liệu pháp sinh học cho hen nặng',
    primaryEndpoint: 'Kiểm soát triệu chứng, ngăn ngừa cơn kịch phát hen nặng và tử vong',
    summary: 'GINA nhấn mạnh KHÔNG sử dụng SABA đơn độc. Lựa chọn ưu tiên là ICS-Formoterol liều thấp khi cần ở bậc 1-2 và duy trì/cắt cơn ở bậc 3-5.',
    detailedConclusion: 'Mọi bệnh nhân hen đều cần điều trị chứa ICS để kiểm soát tình trạng viêm mạn tính phế quản.'
  },
  {
    id: '2026-jrs-copd',
    title: 'JRS 2026: Hướng dẫn Quản lý COPD Hội Hô hấp Nhật Bản',
    titleEn: 'Japanese Respiratory Society Guidelines for the Management of COPD 2026',
    sourceType: 'intl-guideline',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'informative',
    year: 2026,
    organization: 'Japanese Respiratory Society (JRS)',
    journal: 'Eur Respir J',
    file: '2026-jrs-copd.html',
    conditionKey: 'copd',
    icd10: ['J44'],
    intervention: 'LAMA/LABA phối hợp sớm, đặc thù cá thể hóa trên quần thể người cao tuổi và thể trạng người Châu Á',
    primaryEndpoint: 'Chất lượng cuộc sống, ngăn ngừa suy giảm khối cơ (sarcopenia) và đợt cấp',
    summary: 'Nhấn mạnh dinh dưỡng, phục hồi chức năng và tiếp cận đặc thù trên bệnh nhân COPD cao tuổi Châu Á.',
    detailedConclusion: 'Tối ưu thuốc giãn phế quản tác dụng kéo dài kép (LAMA/LABA) kết hợp can thiệp thể chất đa phương diện.'
  },
  {
    id: '2023-byt-benh-phoi-mo-ke',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị Bệnh phổi Mô kẽ (ILD)',
    titleEn: 'National Guidelines on Interstitial Lung Disease Diagnosis and Treatment',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-benh-phoi-mo-ke.html',
    conditionKey: 'interstitial-lung',
    icd10: ['J84', 'J84.1', 'J84.9'],
    intervention: 'HRCT lồng ngực độ phân giải cao, thảo luận đa chuyên khoa (MDD), thuốc chống xơ (Nintedanib, Pirfenidone), ức chế miễn dịch cho CTD-ILD',
    primaryEndpoint: 'Làm chậm tốc độ suy giảm dung tích sống gắng sức (FVC), giảm đợt cấp',
    summary: 'Tiếp cận chẩn đoán phân biệt ILD tự phát (IPF), bệnh phổi kẽ liên quan bệnh mô liên kết (CTD-ILD), viêm phổi quá mẫn (HP).',
    detailedConclusion: 'Chỉ định thuốc chống xơ hóa phổi sớm cho bệnh nhân xơ phổi tiến triển (PPF).'
  },
  {
    id: '2024-byt-lao-p1',
    title: 'BYT 2024 (Phần 1): Hướng dẫn Chẩn đoán và Điều trị Bệnh Lao Nhạy cảm',
    titleEn: 'National Guidelines for the Diagnosis and Treatment of Tuberculosis (Part 1: Drug-Susceptible TB)',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam / Chương trình Chống Lao Quốc gia',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-lao-p1.html',
    conditionKey: 'tb',
    icd10: ['A15', 'A16'],
    intervention: 'GeneXpert MTB/RIF, Phác đồ A1 (2RHZE/4RHE) ở người lớn, phác đồ điều trị lao tiềm ẩn (TPT)',
    primaryEndpoint: 'Tỷ lệ khỏi bệnh, âm hóa đờm, phòng ngừa lây nhiễm cộng đồng',
    summary: 'Chuẩn quốc gia về chẩn đoán lao bằng sinh học phân tử nhanh, theo dõi độc tính thuốc kháng lao (men gan, axit uric, thị lực).',
    detailedConclusion: 'Tuân thủ nghiêm ngặt điều trị có kiểm soát trực tiếp (DOTS) đủ liệu trình 6 tháng.'
  },
  {
    id: '2024-byt-lao-p2',
    title: 'BYT 2024 (Phần 2): Hướng dẫn Chẩn đoán và Điều trị Lao Kháng thuốc (DR-TB)',
    titleEn: 'National Guidelines for the Diagnosis and Treatment of Drug-Resistant Tuberculosis (Part 2)',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-lao-p2.html',
    conditionKey: 'tb',
    icd10: ['A15', 'Z16.24'],
    intervention: 'Phác đồ BPaL / BPaLM (Bedaquiline, Pretomanid, Linezolid ± Moxifloxacin) đường uống ngắn hạn 6 tháng',
    primaryEndpoint: 'Tỷ lệ thành công điều trị MDR/RR-TB, giảm tác dụng phụ so với phác đồ dài hạn',
    summary: 'Bước đột phá áp dụng phác đồ toàn thuốc uống ngắn hạn cho lao đa kháng và siêu kháng thuốc.',
    detailedConclusion: 'Theo dõi sát ECG (QTc) khi dùng Bedaquiline và công thức máu (Linezolid).'
  },

  // --- HỒI SỨC CẤP CỨU & NHIỄM TRÙNG NẶNG (ICU / CRITICAL CARE) ---
  {
    id: '2026-ssc-sepsis',
    title: 'Surviving Sepsis Campaign (SSC) 2026: Hướng dẫn Quốc tế Xử trí Nhiễm khuẩn huyết & Sốc nhiễm khuẩn',
    titleEn: 'Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2026',
    sourceType: 'intl-guideline',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'SCCM / ESICM (Surviving Sepsis Campaign)',
    journal: 'Crit Care Med',
    file: '2026-ssc-sepsis.html',
    conditionKey: 'icu',
    icd10: ['A41', 'R65.2', 'R57.2'],
    intervention: 'Gói 1 giờ (Hour-1 Bundle): Đo Lactate, cấy máu trước KS, KS phổ rộng trong 1h đầu, truyền dịch tinh thể 30ml/kg trong 3h, Norepinephrine vận mạch duy trì MAP ≥ 65 mmHg',
    primaryEndpoint: 'Giảm tỷ lệ tử vong nội viện 28 ngày và suy đa tạng',
    summary: 'Cập nhật tiêu chuẩn Sepsis-3, cá thể hóa truyền dịch bằng các chỉ số động đáp ứng bù dịch (PLR, PPV, siêu âm Vena Cava), kiểm soát ổ nhiễm (Source control).',
    detailedConclusion: 'Bắt đầu kháng sinh phổ rộng ngay trong giờ đầu tiên. Bù dịch có kiểm soát và dùng Norepinephrine sớm qua catheter ngoại vi an toàn nếu chưa có CVC.'
  },
  {
    id: '2021-ssc-soc-nhiem-khuan',
    title: 'SSC 2021: Tóm tắt Khuyến cáo Sốc nhiễm khuẩn và Hồi sức Huyết động',
    titleEn: 'Surviving Sepsis Campaign 2021 Guidelines Summary',
    sourceType: 'intl-guideline',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2021,
    organization: 'SCCM / ESICM',
    journal: 'Crit Care Med',
    file: '2021-ssc-soc-nhiem-khuan-sepsis3.html',
    conditionKey: 'icu',
    icd10: ['A41.9', 'R57.2'],
    intervention: 'Hồi sức dịch ban đầu, Vasopressin liều cố định 0.03 U/min phối hợp Norepinephrine, Hydrocortisone liều sinh lý nếu sốc kháng trị',
    primaryEndpoint: 'Tử vong 28 ngày',
    summary: 'Khuyến cáo nền tảng về phác đồ phối hợp vận mạch và hồi sức thể tích tuần hoàn.',
    detailedConclusion: 'Tránh quá tải dịch sau giai đoạn hồi sức ban đầu; hạ bậc kháng sinh (de-escalation) theo kết quả vi sinh.'
  },
  {
    id: '2016-jama-sepsis-3',
    title: 'JAMA 2016: Đồng thuận Quốc tế Định nghĩa Nhiễm khuẩn huyết và Sốc nhiễm khuẩn (Sepsis-3)',
    titleEn: 'The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2016,
    organization: 'SCCM / ESICM Taskforce',
    journal: 'JAMA',
    file: '2016-jama-sepsis-3-consensus.html',
    conditionKey: 'icu',
    icd10: ['A41', 'R65.2'],
    intervention: 'Thang điểm SOFA (tăng ≥ 2 điểm xác định Sepsis), sàng lọc nhanh bằng qSOFA tại khoa phòng thường',
    primaryEndpoint: 'Độ chính xác dự báo tử vong nội viện',
    summary: 'Định nghĩa lại Sepsis là rối loạn chức năng cơ quan đe dọa tính mạng do đáp ứng mất điều hòa của cơ thể với nhiễm trùng.',
    detailedConclusion: 'Bỏ tiêu chuẩn SIRS trong định nghĩa Sepsis; sử dụng SOFA score để đánh giá mức độ tổn thương cơ quan đích.'
  },
  {
    id: '2026-byt-nhap-vien-cap-cuu',
    title: 'BYT 2026: Hướng dẫn Tiêu chuẩn Phân loại & Chỉ định Nhập viện Cấp cứu',
    titleEn: 'National Emergency Triage and Admission Indication Criteria',
    sourceType: 'vn-moh',
    specialty: 'icu',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-chi-dinh-nhap-vien-cap-cuu.html',
    conditionKey: 'icu',
    icd10: ['R68.8', 'Z03.8'],
    intervention: 'Phân loại tam giác cấp cứu (Emergency Triage), dấu hiệu sinh tồn bất thường (NEWS2), tiêu chuẩn chuyển khoa ICU/HDU/nội trú',
    primaryEndpoint: 'An toàn người bệnh, giảm tử vong tránh được tại phòng cấp cứu',
    summary: 'Văn bản quy chuẩn phân loại độ ưu tiên cấp cứu cấp quốc gia, cờ đỏ lâm sàng bắt buộc nhập viện cấp cứu nội khoa và hồi sức.',
    detailedConclusion: 'Bắt buộc rà soát các dấu hiệu đe dọa tính mạng (đường thở, hô hấp, tuần hoàn, ý thức) trước khi quyết định xử trí ngoại trú.'
  },
  {
    id: '2026-icu-khang-sinh-bn-nang',
    title: 'Chiến lược Dược động học/Dược lực học (PK/PD) Kháng sinh cho Bệnh nhân Nặng tại ICU',
    titleEn: 'PK/PD Optimization of Antibiotics in Critically Ill Patients',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'practice-changing',
    year: 2026,
    organization: 'ESICM Critical Care Review',
    journal: 'Intensive Care Med',
    file: '2026-icu-khang-sinh-cho-bn-nang.html',
    conditionKey: 'icu',
    icd10: ['A41', 'Z16'],
    intervention: 'Liều nạp (Loading dose), truyền kéo dài / truyền liên tục Beta-lactam, theo dõi nồng độ thuốc trị liệu (TDM)',
    primaryEndpoint: 'Đạt mục tiêu PK/PD (100% fT > MIC hoặc fT > 4xMIC), tăng tỷ lệ diệt khuẩn',
    summary: 'Xử lý biến đổi thể tích phân bố (Vd) tăng và độ thanh thải thận tăng (ARC) ở bệnh nhân sốc nhiễm khuẩn hồi sức.',
    detailedConclusion: 'Luôn dùng liều nạp đầy đủ trong 24h đầu bất kể chức năng thận; truyền kéo dài 3-4h cho Beta-lactam để tối ưu hiệu quả.'
  },
  {
    id: '2026-icu-ca-the-hoa-beta-lactam',
    title: 'Cá thể hóa Liều Beta-lactam và Phối hợp Kháng sinh theo Hướng dẫn IDSA/ESCMID',
    titleEn: 'Personalized Beta-Lactam Dosing Strategies in the ICU',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'ESCMID / ESICM',
    journal: 'Lancet Infect Dis',
    file: '2026-icu-ca-the-hoa-beta-lactam.html',
    conditionKey: 'icu',
    icd10: ['A41', 'Z16'],
    intervention: 'Phối hợp Colistin, Meropenem, Ceftazidime/Avibactam, Piperacillin/Tazobactam liều cá thể hóa',
    primaryEndpoint: 'Kiểm soát nhiễm khuẩn đa kháng (CRKP, CRAB, CRPA)',
    summary: 'Tối ưu phác đồ kháng sinh chống vi khuẩn Gram âm đa kháng đường ruột và không lên men tại khoa hồi sức.',
    detailedConclusion: 'Kết hợp TDM và phương pháp truyền liên tục để đạt nồng độ mục tiêu không gây độc thận.'
  },
  {
    id: '2026-icm-namsap-ards',
    title: 'ICM 2026: Thông khí Nằm sấp và Chiến lược Bảo vệ Phổi trong ARDS Nặng',
    titleEn: 'Prone Positioning and Lung-Protective Ventilation in Moderate-to-Severe ARDS',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'practice-changing',
    year: 2026,
    organization: 'European Society of Intensive Care Medicine (ESICM)',
    journal: 'Intensive Care Med',
    file: '2026-icm-namsap-ards.html',
    conditionKey: 'pneumonia',
    icd10: ['J80', 'J96.0'],
    intervention: 'Thông khí nằm sấp ≥ 16 giờ/ngày, thể tích khí lưu thông thấp (Vt 4-6 ml/kg PBW), Pplat < 30 cmH2O, Driving pressure < 14 cmH2O',
    primaryEndpoint: 'Giảm tỷ lệ tử vong 28 ngày và 90 ngày ở bệnh nhân ARDS có PaO2/FiO2 < 150',
    summary: 'Can thiệp nằm sấp sớm giúp đồng đều thông khí - tưới máu phổi, mở các phế nang xẹp vùng lưng và cải thiện sống còn rõ rệt.',
    detailedConclusion: 'Bắt đầu nằm sấp sớm trong vòng 24-48 giờ đầu ở ARDS từ vừa đến nặng có chỉ định.'
  },
  {
    id: '2026-mbm-tongquan-ards',
    title: 'Tổng quan Tiếp cận Chẩn đoán và Điều trị Suy hô hấp Cấp tiến triển (ARDS)',
    titleEn: 'Clinical Review: Diagnosis and Modern Phenotyping of ARDS',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'ATS / ESICM Review',
    journal: 'Am J Respir Crit Care Med',
    file: '2026-mbm-tongquan-ards.html',
    conditionKey: 'pneumonia',
    icd10: ['J80'],
    intervention: 'Định nghĩa Berlin cải biên (Global Definition), phân biệt ARDS dưới kiểu hình viêm cao (Hyperinflammatory) vs viêm thấp',
    primaryEndpoint: 'Tối ưu hóa phác đồ điều trị dịch và PEEP',
    summary: 'Cung cấp cơ sở sinh lý bệnh, vai trò thuốc giãn cơ ngắn ngày, huy động phế nang và ECMO VV trong ARDS kháng trị.',
    detailedConclusion: 'Kiểm soát hạn chế dịch (Conservative fluid strategy) sau khi đã hồi sức sốc ổn định.'
  },

  // --- NỘI TIẾT & CHUYỂN HÓA (ENDOCRINOLOGY) ---
  {
    id: '2026-ada-diabetes',
    title: 'ADA 2026: Tiêu chuẩn Chăm sóc Y tế trong Bệnh Đái tháo đường (Standards of Care)',
    titleEn: 'Standards of Care in Diabetes—2026 (American Diabetes Association)',
    sourceType: 'intl-guideline',
    specialty: 'endo',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Hiệp hội Đái tháo đường Hoa Kỳ (ADA)',
    journal: 'Diabetes Care',
    file: '2026-ada-diabetes.html',
    conditionKey: 'diabetes-t2d',
    icd10: ['E11', 'E11.9', 'E10', 'E11.2'],
    intervention: 'Mục tiêu HbA1c < 7.0% (cá thể hóa 6.5-8.0%), SGLT2i và GLP-1RA độc lập với HbA1c cho BN có ASCVD/HF/CKD, Tirzepatide (GIP/GLP-1 RA) kép',
    primaryEndpoint: 'Bảo vệ tim thận mạch, giảm cân, phòng ngừa biến chứng vi mạch và mạch máu lớn',
    summary: 'Khuyến cáo kim chỉ nam toàn cầu về ĐTĐ: Ưu tiên bảo vệ cơ quan đích (Tim - Thận - Cân nặng) song hành cùng kiểm soát đường huyết.',
    detailedConclusion: 'Bệnh nhân ĐTĐ típ 2 có nguy cơ tim mạch cao hoặc suy tim/bệnh thận: Bắt buộc chỉ định SGLT2i và/hoặc GLP-1RA không phụ thuộc HbA1c nền.'
  },
  {
    id: '2025-byt-than-kinh-dtđ',
    title: 'BYT 2025: Hướng dẫn Chẩn đoán và Điều trị Biến chứng Thần kinh Đái tháo đường',
    titleEn: 'National Guidelines on Diagnosis and Treatment of Diabetic Neuropathy',
    sourceType: 'vn-moh',
    specialty: 'endo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2025-byt-benh-than-kinh-dai-thao-duong.html',
    conditionKey: 'diabetes-t2d',
    icd10: ['E11.4', 'G63.2'],
    intervention: 'Sàng lọc khám bàn chân bằng Monofilament 10g + âm thoa 128Hz, thuốc giảm đau thần kinh (Duloxetine, Pregabalin, Gabapentin), chăm sóc phòng loét',
    primaryEndpoint: 'Giảm đau thần kinh, ngăn ngừa loét bàn chân và đoạn chi',
    summary: 'Quy trình sàng lọc định kỳ bệnh thần kinh ngoại biên và tự chủ ở bệnh nhân ĐTĐ, phân tầng nguy cơ bàn chân đái tháo đường.',
    detailedConclusion: 'Kiểm soát đường huyết chặt chẽ để làm chậm tiến triển tổn thương sợi thần kinh; điều trị đau bằng Duloxetine hoặc Pregabalin liều tăng dần.'
  },
  {
    id: '2026-jcem-bao-giap',
    title: 'JCEM 2026: Hướng dẫn Chẩn đoán và Xử trí Cấp cứu Bão giáp (Thyroid Storm)',
    titleEn: 'Emergency Management and Contemporary Diagnosis of Thyroid Storm',
    sourceType: 'intl-guideline',
    specialty: 'endo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Endocrine Society / ATA',
    journal: 'JCEM',
    file: '2026-jcem-bao-giap.html',
    conditionKey: 'thyroid',
    icd10: ['E05.5', 'E05.0'],
    intervention: 'Thang điểm Burch-Wartofsky (BWPS ≥ 45 điểm), Phác đồ 5 bước: Kháng giáp tổng hợp (PTU/Thiamazole) -> Iod vô cơ (Lugol) sau 1h -> Chẹn beta (Propranolol) -> Corticosteroid (Hydrocortisone) -> Hạ nhiệt/Hỗ trợ',
    primaryEndpoint: 'Cắt đứt cơn bão giáp, ổn định huyết động và nhịp tim, giảm tử vong',
    summary: 'Cấp cứu nội tiết tối khẩn: Phối hợp đồng thời phong bế tổng hợp hormone giáp, ức chế giải phóng hormone mới, chẹn thụ thể giao cảm và ức chế chuyển T4 thành T3.',
    detailedConclusion: 'Không bao giờ cho Iod trước thuốc kháng giáp tổng hợp (tránh hiệu ứng Jod-Basedow). Dùng Hydrocortisone để phòng ngừa suy thượng thận cấp tương đối.'
  },
  {
    id: '2020-nutrients-lowcarb-vs-lowfat',
    title: 'Nghiên cứu So sánh Chế độ ăn Low-Carb vs Low-Fat trong Giảm cân và Kiểm soát Chuyển hóa',
    titleEn: 'Effects of Low-Carbohydrate vs Low-Fat Diets on Metabolic Parameters and Weight Loss',
    sourceType: 'intl-study',
    specialty: 'nutri',
    design: 'meta',
    impact: 'informative',
    year: 2020,
    organization: 'Nutrients Meta-Analysis',
    journal: 'Nat Med',
    file: '2020-nutrients-lowcarb-vs-lowfat.html',
    conditionKey: 'obesity',
    icd10: ['E66', 'E11'],
    intervention: 'Chế độ ăn giảm Carbohydrate (< 50-130g/ngày) vs Giảm chất béo (< 30% tổng năng lượng)',
    primaryEndpoint: 'Mức giảm cân nặng, HbA1c, Triglyceride và cải thiện nhạy cảm Insulin',
    summary: 'Chế độ ăn Low-Carb cho thấy ưu thế vượt trội trong 6 tháng đầu về giảm cân nhanh và kiểm soát đường huyết sau ăn, sau 12 tháng phụ thuộc chủ yếu vào mức độ tuân thủ năng lượng nạp vào.',
    detailedConclusion: 'Cá thể hóa chế độ ăn dựa trên sự ưa thích và khả năng duy trì lâu dài của bệnh nhân.'
  },

  // --- THẬN HỌC & TIẾT NIỆU (NEPHROLOGY) ---
  {
    id: '2024-kdigo-ckd',
    title: 'KDIGO 2024: Hướng dẫn Lâm sàng Thực hành Đánh giá & Quản lý Bệnh Thận Mạn (CKD)',
    titleEn: 'KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease',
    sourceType: 'intl-guideline',
    specialty: 'renal',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2024,
    organization: 'Kidney Disease: Improving Global Outcomes (KDIGO)',
    journal: 'Kidney Int',
    file: '2024-kdigo-ckd.html',
    conditionKey: 'ckd',
    icd10: ['N18', 'N18.3', 'N18.9'],
    intervention: 'Phân loại CGA (Cause, eGFR G1-G5, Albuminuria A1-A3), Trụ cột 4 thuốc bảo vệ thận: ACEi/ARB + SGLT2i + nsMRA (Finerenone) + GLP-1RA / Statin',
    primaryEndpoint: 'Làm chậm tốc độ suy giảm eGFR, giảm biến cố tim mạch và nhu cầu lọc máu',
    summary: 'Định hướng toàn diện mới nhất: Tầm quan trọng của xét nghiệm UACR nước tiểu; SGLT2i là chỉ định nền tảng cho CKD có eGFR ≥ 20 ml/min/1.73m2 bất kể có ĐTĐ hay không.',
    detailedConclusion: 'Duy trì điều trị SGLT2i liên tục cho đến khi bắt đầu lọc máu hoặc ghép thận; chấp nhận eGFR giảm tạm thời < 30% khi khởi đầu ức chế RAAS/SGLT2i.'
  },

  // --- TRUYỀN NHIỄM & VI RÚT & NẤM (INFECTIOUS DISEASES) ---
  {
    id: '2026-idsa-amr',
    title: 'IDSA 2026: Hướng dẫn Điều trị Nhiễm khuẩn Vi khuẩn Gram Âm Kháng thuốc (AMR Guidance)',
    titleEn: 'Infectious Diseases Society of America 2026 Guidance on the Treatment of Antimicrobial-Resistant Gram-Negative Infections',
    sourceType: 'intl-guideline',
    specialty: 'infect',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Hiệp hội Bệnh Truyền nhiễm Hoa Kỳ (IDSA)',
    journal: 'Clin Infect Dis',
    file: '2026-idsa-amr.html',
    conditionKey: 'icu',
    icd10: ['A41', 'Z16'],
    intervention: 'Ceftazidime-avibactam, Meropenem-vaborbactam, Imipenem-relebactam, Cefiderocol cho CRE, DTR-Pseudomonas aeruginosa, CR-Acinetobacter baumannii (Ampicillin-sulbactam liều cao)',
    primaryEndpoint: 'Lui bệnh vi sinh, sống còn 30 ngày',
    summary: 'Cập nhật phân loại enzyme Carbapenemase (KPC, NDM, OXA-48) và phác đồ kháng sinh thế hệ mới tối ưu cho từng loại men kháng.',
    detailedConclusion: 'Nhiễm NDM (Metallo-beta-lactamase): Phối hợp Ceftazidime/Avibactam + Aztreonam để vượt qua cơ chế kháng thuốc.'
  },
  {
    id: '2024-byt-aspergillus-cpa',
    title: 'BYT 2024: Hướng dẫn Chẩn đoán và Điều trị Bệnh Nhiễm Nấm Aspergillus Phổi Mạn tính (CPA)',
    titleEn: 'National Guidelines for the Diagnosis and Treatment of Chronic Pulmonary Aspergillosis',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-aspergillus-cpa.html',
    conditionKey: 'invasive-fungal',
    icd10: ['B44', 'B44.0', 'B44.9'],
    intervention: 'Huyết thanh học kháng thể Aspergillus IgG, CT lồng ngực (hình ảnh lục lạc - Fungus ball/hang), Itraconazole / Voriconazole uống kéo dài ≥ 6 tháng',
    primaryEndpoint: 'Kiểm soát triệu chứng ho ra máu, ngăn phá hủy nhu mô phổi',
    summary: 'Chỉ dẫn chi tiết phân biệt CPA trên nền di chứng lao phổi, chỉ định phẫu thuật cắt thùy phổi khi ho ra máu đe dọa tính mạng.',
    detailedConclusion: 'Kháng nấm đường uống Itraconazole 200mg x 2 lần/ngày (theo dõi nồng độ thuốc TDM) tối thiểu 6 tháng.'
  },
  {
    id: '2023-byt-sot-xuat-huyet',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị Sốt xuất huyết Dengue',
    titleEn: 'National Guidelines on Management of Dengue Hemorrhagic Fever',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-sot-xuat-huyet-dengue.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A90', 'A91'],
    intervention: 'Theo dõi dấu hiệu cảnh báo (Warning signs), theo dõi Hct và tiểu cầu, phác đồ truyền dịch chống sốc theo giờ (Điện giải -> Cao phân tử Dextran/HES)',
    primaryEndpoint: 'Kịp thời phát hiện sốc, tái lập thể tích tuần hoàn, giảm tử vong do sốc thoát huyết tương',
    summary: 'Quy chuẩn phân độ: SXH Dengue, SXH Dengue có dấu hiệu cảnh báo, và SXH Dengue nặng; sơ đồ truyền dịch chi tiết từng giờ.',
    detailedConclusion: 'Chỉ định truyền dịch đúng thời điểm khi có dấu hiệu cảnh báo/sốc, tránh quá tải dịch giai đoạn hồi phục.'
  },
  {
    id: '2023-byt-sot-ret',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị Bệnh Sốt Rét',
    titleEn: 'National Guidelines on Malaria Treatment and Elimination',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-sot-ret.html',
    conditionKey: 'malaria',
    icd10: ['B50', 'B51', 'B54'],
    intervention: 'Thuốc Artemisinin phối hợp (ACT: Dihydroartemisinin-Piperaquine, Pyronaridine-Artesunate), Artesunate tiêm tĩnh mạch cho sốt rét ác tính, Primaquine diệt thể giao bào/thể ngủ',
    primaryEndpoint: 'Sạch ký sinh trùng, cắt đứt lây truyền, cứu sống bệnh nhân sốt rét ác tính',
    summary: 'Hướng dẫn điều trị sốt rét thông thường do P. falciparum, P. vivax và xử trí các thể sốt rét ác tính (não, đái huyết cầu tố, suy thận).',
    detailedConclusion: 'Artesunate tiêm TM khẩn cấp cho mọi ca sốt rét nặng ác tính; xét nghiệm G6PD trước khi dùng Primaquine liều cao.'
  },
  {
    id: '2024-byt-tay-chan-mieng',
    title: 'BYT 2024: Hướng dẫn Chẩn đoán và Điều trị Bệnh Tay Chân Miệng (HFMD)',
    titleEn: 'National Guidelines on Hand-Foot-Mouth Disease Management',
    sourceType: 'vn-moh',
    specialty: 'pedia',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-taychanmieng.html',
    conditionKey: 'hfmd',
    icd10: ['B08.4'],
    intervention: 'Phân độ lâm sàng 1, 2a, 2b (nhóm 1, nhóm 2), độ 3, độ 4. Chỉ định Phenobarbital uống/tiêm, IVIG (Immunoglobulin miễn dịch), Milrinone trợ tim hạ áp',
    primaryEndpoint: 'Ngăn ngừa biến chứng viêm não, phù phổi cấp và suy tuần hoàn do EV71',
    summary: 'Nhận biết sớm dấu hiệu giật mình chới với, sốt cao khó hạ, rung giật nhãn cầu để phân độ và điều trị tích cực kịp thời.',
    detailedConclusion: 'Độ 2b nhóm 2 trở lên: Điều trị nội trú phòng cấp cứu/ICU, chỉ định IVIG khi có triệu chứng thần kinh tiến triển.'
  },
  {
    id: '2025-byt-soi',
    title: 'BYT 2025: Hướng dẫn Giám sát, Chẩn đoán và Xử trí Bệnh Sởi (Measles)',
    titleEn: 'National Guidelines on Measles Diagnosis, Treatment and Outbreak Control',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2025-byt-soi.html',
    conditionKey: 'measles',
    icd10: ['B05', 'B05.9'],
    intervention: 'Cách ly hô hấp, bổ sung Vitamin A liều cao (2 ngày liên tiếp), kháng sinh khi có bội nhiễm phổi/tai',
    primaryEndpoint: 'Phòng ngừa biến chứng viêm phổi, viêm não và tử vong',
    summary: 'Quy trình xử trí sởi mùa dịch, vai trò thiết yếu của Vitamin A giảm biến chứng mù lòa và tử vong ở trẻ em.',
    detailedConclusion: 'Bổ sung Vitamin A ngay khi chẩn đoán cho mọi trẻ mắc sởi theo lứa tuổi.'
  },
  {
    id: '2025-byt-cum-mua',
    title: 'BYT 2025: Hướng dẫn Chẩn đoán và Điều trị Cúm Mùa (Influenza)',
    titleEn: 'National Guidelines on Seasonal Influenza Diagnosis and Management',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2025-byt-cummua.html',
    conditionKey: 'flu',
    icd10: ['J09', 'J10', 'J11'],
    intervention: 'Thuốc ức chế Neuraminidase (Oseltamivir - Tamiflu) chỉ định sớm trong 48 giờ đầu cho đối tượng nguy cơ cao',
    primaryEndpoint: 'Rút ngắn thời gian bệnh, giảm tỷ lệ viêm phổi cúm và suy hô hấp',
    summary: 'Phân loại cúm không biến chứng và cúm có biến chứng/nguy cơ cao (người già, phụ nữ có thai, bệnh phổi mạn).',
    detailedConclusion: 'Khởi đầu Oseltamivir càng sớm càng tốt, không cần chờ kết quả PCR khẳng định ở nhóm nguy cơ cao.'
  },
  {
    id: '2023-byt-covid19',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị COVID-19 (Cập nhật)',
    titleEn: 'National Guidelines on Diagnosis and Treatment of COVID-19',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-covid19.html',
    conditionKey: 'covid19',
    icd10: ['U07.1'],
    intervention: 'Kháng virus (Nirmatrelvir/Ritonavir - Paxlovid, Molnupiravir), Dexamethasone cho ca thở oxy, kháng đông dự phòng LMWH',
    primaryEndpoint: 'Ngăn diễn tiến nặng, giảm tử vong',
    summary: 'Chuyển đổi COVID-19 sang bệnh truyền nhiễm nhóm B, quản lý tập trung nhóm nguy cơ cao và xử trí cơn bão cytokine.',
    detailedConclusion: 'Paxlovid trong 5 ngày đầu cho bệnh nhân nguy cơ cao; Dexamethasone 6mg/ngày chỉ dùng khi bệnh nhân có giảm SpO2.'
  },
  {
    id: '2025-who-viem-mang-nao',
    title: 'WHO 2025: Lộ trình Toàn cầu và Phác đồ Xử trí Cấp cứu Viêm màng não Vi khuẩn',
    titleEn: 'WHO Global Roadmap to Defeat Meningitis and Emergency Management',
    sourceType: 'intl-guideline',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Tổ chức Y tế Thế giới (WHO)',
    journal: 'Lancet Infect Dis',
    file: '2025-who-viem-mang-nao.html',
    conditionKey: 'meningitis',
    icd10: ['G00', 'G00.9'],
    intervention: 'Chọc dò dịch não tủy (CSF) khẩn, Dexamethasone 10mg TM trước hoặc cùng liều kháng sinh đầu tiên, Ceftriaxone/Cefotaxime liều màng não + Vancomycin + Ampicillin (nếu nghi ngờ Listeria)',
    primaryEndpoint: 'Giảm di chứng điếc, tổn thương thần kinh vĩnh viễn và tử vong',
    summary: 'Tiếp cận cấp cứu viêm màng não: Không trì hoãn kháng sinh nếu phải chờ chụp CT scan sọ não; dùng Corticoid trước để giảm phản ứng viêm do ly giải vi khuẩn.',
    detailedConclusion: 'Dexamethasone TM 0.15 mg/kg mỗi 6 giờ x 4 ngày (đặc biệt hiệu quả trong viêm màng não do Phế cầu).'
  },
  {
    id: '2023-byt-marburg',
    title: 'BYT 2023: Hướng dẫn Giám sát và Phòng chống Bệnh do Vi rút Marburg',
    titleEn: 'National Guidelines on Marburg Virus Disease Surveillance and Response',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-marburg.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A98.3'],
    intervention: 'Cách ly nghiêm ngặt cấp 4, phòng hộ PPE toàn thân, hồi sức bù dịch điện giải tích cực, điều trị triệu chứng',
    primaryEndpoint: 'Kiểm soát lây nhiễm chéo bệnh viện, duy trì tưới máu cơ quan',
    summary: 'Hướng dẫn phòng ngừa và kiểm soát bệnh sốt xuất huyết do vi rút Marburg có tỷ lệ tử vong cao.',
    detailedConclusion: 'Tuân thủ nghiêm ngặt kiểm soát nhiễm khuẩn và xử lý chất thải sinh học lây nhiễm cao.'
  },
  {
    id: '2026-byt-ebola',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Bệnh Sốt xuất huyết do Vi rút Ebola',
    titleEn: 'National Guidelines on Ebola Virus Disease Clinical Management',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-ebola.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A98.4'],
    intervention: 'Kháng thể đơn dòng (Inmazeb, Ebanga), tối ưu hóa hồi sức dịch và thăng bằng kiềm toan',
    primaryEndpoint: 'Giảm tỷ lệ tử vong ở bệnh nhân nhiễm Ebolavirus',
    summary: 'Cập nhật liệu pháp kháng thể đặc hiệu và nguyên tắc an toàn sinh học tuyệt đối.',
    detailedConclusion: 'Truyền kháng thể đơn dòng sớm kết hợp hồi sức hỗ trợ tích cực.'
  },
  {
    id: '2026-byt-nipah',
    title: 'BYT 2026: Hướng dẫn Giám sát, Chẩn đoán và Điều trị Bệnh do Vi rút Nipah',
    titleEn: 'National Guidelines on Nipah Virus Encephalitis Management',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-nipah.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A98'],
    intervention: 'Hồi sức hô hấp, chống co giật, thuốc kháng virus thử nghiệm (Ribavirin, Remdesivir)',
    primaryEndpoint: 'Kiểm soát viêm não cấp và suy hô hấp',
    summary: 'Hướng dẫn ứng phó bệnh truyền nhiễm lây từ động vật (dơi ăn quả) sang người gây viêm não tử vong cao.',
    detailedConclusion: 'Chẩn đoán xác định bằng RT-PCR; hồi sức nâng đỡ chức năng sống tại phòng cách ly áp lực âm.'
  },

  // --- TIÊU HÓA & GAN MẬT (GASTROENTEROLOGY & HEPATOLOGY) ---
  {
    id: '2026-byt-viem-gan-b',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Bệnh Viêm gan Vi rút B (Cập nhật Toàn diện)',
    titleEn: 'National Guidelines on Chronic Hepatitis B Diagnosis and Management (2026 Update)',
    sourceType: 'vn-moh',
    specialty: 'gi',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-viem-gan-b.html',
    conditionKey: 'hepatitis-b',
    icd10: ['B18.0', 'B18.1', 'B16'],
    intervention: 'Chỉ định thuốc kháng virus uống (NUCs: Tenofovir Alafenamide - TAF, Tenofovir Disoproxil - TDF, Entecavir - ETV), mở rộng tiêu chuẩn điều trị, tầm soát ung thư gan HCC bằng AFP + Siêu âm định kỳ 6 tháng',
    primaryEndpoint: 'Ức chế virus HBV-DNA dưới ngưỡng phát hiện, bình thường hóa ALT, ngăn ngừa xơ gan và HCC',
    summary: 'Quy chuẩn quốc gia mới nhất: Mở rộng chỉ định điều trị NUCs cho bệnh nhân có HBV-DNA cao và ALT tăng nhẹ hoặc có xơ hóa gan F ≥ 2, dự phòng lây truyền mẹ con từ tuần thai 24-28.',
    detailedConclusion: 'Ưu tiên TAF/TDF/ETV là thuốc hàng đầu có hàng rào kháng thuốc cao; không tự ý ngừng thuốc kháng virus khi chưa đạt tiêu chuẩn ngừng an toàn.'
  },
  {
    id: '2026-byt-tom-tat-viem-gan-b',
    title: 'BYT 2026: Tóm tắt Lưu đồ Tiếp cận và Xử trí Nhanh Viêm gan B',
    titleEn: 'Quick Clinical Algorithm for Hepatitis B Management',
    sourceType: 'vn-moh',
    specialty: 'gi',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-tom-tat-viem-gan-b.html',
    conditionKey: 'hepatitis-b',
    icd10: ['B18.1'],
    intervention: 'Lưu đồ 3 bước: Xác định HBsAg -> Đo tải lượng HBV DNA & Men gan -> Đánh giá mức độ xơ hóa (FIB-4 / FibroScan) để quyết định khởi trị',
    primaryEndpoint: 'Hỗ trợ quyết định lâm sàng nhanh cho bác sĩ tuyến cơ sở và đa khoa',
    summary: 'Bảng tra cứu nhanh liều lượng TDF, TAF, ETV và hiệu chỉnh liều theo mức lọc cầu thận eGFR.',
    detailedConclusion: 'Bệnh nhân xơ gan còn bù hoặc mất bù có HBsAg (+) cần điều trị NUCs suốt đời bất kể nồng độ ALT và HBV-DNA.'
  },
  {
    id: '2026-apasl-viem-gan-b',
    title: 'APASL 2026: Đồng thuận Khu vực Châu Á - Thái Bình Dương về Quản lý Viêm gan B',
    titleEn: 'APASL 2026 Consensus Guidelines on the Management of Hepatitis B Virus Infection',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Asian Pacific Association for the Study of the Liver (APASL)',
    journal: 'J Hepatol',
    file: '2026-apasl-viem-gan-b.html',
    conditionKey: 'hepatitis-b',
    icd10: ['B18.1'],
    intervention: 'Chiến lược Treat-all (Mở rộng tối đa điều trị), theo dõi nồng độ HBsAg định lượng (qHBsAg), tiêu chuẩn "khỏi bệnh chức năng" (Functional Cure)',
    primaryEndpoint: 'Mất HBsAg huyết thanh, giảm tỷ lệ ung thư biểu mô tế bào gan ở chủng tộc Châu Á',
    summary: 'Hướng dẫn thực hành từ hội gan mật hàng đầu châu lục, phù hợp đặc thù dịch tễ học và kiểu gen HBV tại Việt Nam.',
    detailedConclusion: 'Khuyến khích điều trị sớm để bảo vệ tế bào gan và ngăn biến chứng xơ gan tiến triển.'
  },
  {
    id: '2024-byt-vgsvc',
    title: 'BYT 2024: Hướng dẫn Chẩn đoán và Điều trị Viêm gan Vi rút C (HCV)',
    titleEn: 'National Guidelines on Hepatitis C Diagnosis and Treatment with Direct-Acting Antivirals (DAAs)',
    sourceType: 'vn-moh',
    specialty: 'gi',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-vgsvc.html',
    conditionKey: 'hepatitis-c',
    icd10: ['B18.2'],
    intervention: 'Thuốc kháng virus tác động trực tiếp toàn pangenotypic (Sofosbuvir/Velpatasvir x 12 tuần hoặc Glecaprevir/Pibrentasvir x 8 tuần)',
    primaryEndpoint: 'Đạt đáp ứng virus bền vững ở tuần thứ 12 sau điều trị (SVR12 > 95-98%) - Khỏi bệnh vi sinh',
    summary: 'Phác đồ điều trị viêm gan C đơn giản hóa không cần xác định kiểu gen (Genotype) cho hầu hết các trường hợp, điều trị an toàn trên cả bệnh nhân suy thận.',
    detailedConclusion: 'Uống đủ liệu trình DAA 8-12 tuần đạt tỷ lệ khỏi bệnh gần như tuyệt đối (> 97%).'
  },
  {
    id: '2018-tg18-viem-tui-mat',
    title: 'Tokyo Guidelines 2018 (TG18): Chẩn đoán, Phân độ nặng và Xử trí Viêm túi mật cấp',
    titleEn: 'Tokyo Guidelines 2018: Diagnostic criteria, severity grading, and management of acute cholecystitis',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2018,
    organization: 'Hội Gan Mật Tụy Nhật Bản (JSHBPS) & Ủy ban TG18',
    journal: 'J Hepatobiliary Pancreat Sci',
    file: '2018-tg18-viem-tui-mat.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K80.0', 'K81.0', 'K80.1'],
    intervention: 'Phẫu thuật cắt túi mật nội soi sớm (< 72h), Dẫn lưu túi mật qua da (PTGBD) / EUS-GBD LAMS cho bệnh nhân nguy cơ cao, Kháng sinh phân tầng theo độ nặng và dừng sau 24h sau mổ độ I/II',
    primaryEndpoint: 'Giảm tỷ lệ tử vong, tỷ lệ biến chứng quanh phẫu thuật, thời gian nằm viện và chi phí điều trị',
    keyResults: 'Lap-C sớm < 72h an toàn; Siêu âm nhạy 82% đặc hiệu 81%; PTGBD giải áp hiệu quả; Dừng KS ≤ 24h sau mổ Độ I/II kiểm soát tốt nhiễm trùng.',
    summary: 'Hướng dẫn kim chỉ nam quốc tế về viêm túi mật cấp: Tiêu chuẩn chẩn đoán TG18/TG13, phân tầng 3 mức độ nặng (Grade I-III), lưu đồ mổ nội soi sớm vs dẫn lưu túi mật cấp cứu, và phác đồ kháng sinh tối ưu.',
    detailedConclusion: 'Cắt túi mật nội soi sớm là lựa chọn hàng đầu cho Độ I và Độ II ở bệnh nhân nguy cơ mổ thấp; PTGBD là can thiệp đầu tay cho Độ III hoặc nguy cơ mổ cao không đáp ứng nội khoa.'
  },
  {
    id: '2018-tg18-viem-duong-mat',
    title: 'Tokyo Guidelines 2018 (TG18): Chẩn đoán, Phân độ nặng và Dẫn lưu Viêm đường mật cấp',
    titleEn: 'Tokyo Guidelines 2018: Diagnostic criteria, severity grading, and management bundles for acute cholangitis',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2018,
    organization: 'Hội Gan Mật Tụy Nhật Bản (JSHBPS) & Ủy ban TG18',
    journal: 'J Hepatobiliary Pancreat Sci',
    file: '2018-tg18-viem-duong-mat.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K83.0', 'K80.3', 'K80.4'],
    intervention: 'Nội soi mật tụy ngược dòng (ERCP) dẫn lưu giải áp sớm/cấp cứu (< 24-48h), PTBD cứu vãn, EUS-BD, gói quản lý 9 bước (Bundles), kháng sinh phổ rộng kỵ khí / Pseudomonas / Enterococcus và dừng sau 4-7 ngày sau dẫn lưu',
    primaryEndpoint: 'Giảm tỷ lệ tử vong 30 ngày từ 3.7% xuống 2.0% ở Độ II, ngăn ngừa sốc nhiễm khuẩn và suy đa tạng',
    keyResults: 'ERCP là can thiệp đầu tay (Grade 1 Level B); EBS và ENBD hiệu quả tương đương (Grade 1 Level A); Dẫn lưu sớm trong 24-48h cứu sống bệnh nhân; Dừng KS sau 4-7 ngày dẫn lưu thành công.',
    summary: 'Hướng dẫn kim chỉ nam quốc tế về viêm đường mật cấp: Tiêu chuẩn chẩn đoán TG18/TG13, phân tầng 3 mức độ nặng, lưu đồ dẫn lưu đường mật khẩn cấp (ERCP/PTBD/EUS-BD), gói quản lý bundles và phác đồ kháng sinh.',
    detailedConclusion: 'Dẫn lưu đường mật giải áp khẩn cấp (ERCP đầu tay) kết hợp hồi sức tạng và kháng sinh là chìa khóa sống còn; chỉ thực hiện lấy sỏi triệt để khi tình trạng viêm cấp đã ổn định.'
  },
  {
    id: '2022-easl-baveno-vii-portal-hypertension-consensus',
    title: 'Baveno VII (EASL 2022): Cá Thể Hóa Chăm Sóc Bệnh Nhân Tăng Áp Lực Tĩnh Mạch Cửa',
    titleEn: 'Baveno VII – Renewing consensus in portal hypertension: Personalized care for portal hypertension',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2022,
    organization: 'Hiệp hội Nghiên cứu Bệnh Gan Châu Âu (EASL) & Baveno VII Faculty',
    journal: 'J Hepatol',
    file: '2022-easl-baveno-vii-portal-hypertension-consensus.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K76.6', 'K74.6', 'I85.0'],
    intervention: 'Đánh giá không xâm lấn cACLD (Quy tắc số 5 LSM 10-15-20-25 kPa), tiêu chuẩn Baveno VI mở rộng tránh nội soi (LSM < 20 + PLT ≥ 150), Carvedilol dự phòng đợt mất bù đầu tiên, lưu đồ cấp cứu AVB 0h-12h-24h/72h (Pre-emptive TIPS)',
    primaryEndpoint: 'Ngăn ngừa đợt mất bù đầu tiên, giảm tỷ lệ tử vong và thất bại cầm máu 5 ngày trong xuất huyết vỡ giãn tĩnh mạch',
    keyResults: 'Carvedilol là NSBB ưu tiên hàng đầu; Tránh nội soi an toàn khi LSM < 20 và PLT ≥ 150; Pre-emptive TIPS trong 72h (tốt nhất < 24h) cho Child C < 14 hoặc Child B > 7 kèm chảy máu hoạt động; Tuyệt đối cấm truyền FFP trong AVB.',
    summary: 'Văn bản đồng thuận quốc tế kim chỉ nam của EASL về tăng áp lực tĩnh mạch cửa: Chẩn đoán không xâm lấn cACLD/CSPH, tiêu chuẩn vàng HVPG, Carvedilol dự phòng mất bù, xử trí cấp cứu AVB và chỉ định Pre-emptive TIPS sớm.',
    detailedConclusion: 'Áp dụng Quy tắc số 5 của LSM và tiêu chuẩn Baveno VI giúp giảm thiểu nội soi không cần thiết; dùng Carvedilol sớm khi có CSPH và kích hoạt Pre-emptive TIPS trong 72h cho AVB nguy cơ cao là chìa khóa cải thiện sống còn.'
  },
  {
    id: '2025-iap-acute-pancreatitis',
    title: 'IAP 2025: Hướng Dẫn Đồng Thuận Quốc Tế về Quản Lý Viêm Tụy Cấp',
    titleEn: 'International Association of Pancreatology Revised Guidelines on Acute Pancreatitis 2025',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2025,
    organization: 'Hiệp hội Tụy học Quốc tế (IAP), APA, EPC, IPC & JPS',
    journal: 'Pancreatology',
    file: '2025-iap-acute-pancreatitis.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K85', 'K85.0', 'K85.1', 'K85.9'],
    intervention: 'Chẩn đoán 2/3, hồi sức dịch vừa phải 1.5 ml/kg/h bằng Lactated Ringer\'s (WATERFALL), cấm kháng sinh/probiotics dự phòng, ăn đặc ít béo sớm, ERCP khi có viêm đường mật, can thiệp Step-Up hoại tử tụy (PCD/ETD LAMS/VARD) sau 4 tuần',
    primaryEndpoint: 'Giảm quá tải dịch (từ 21% xuống 6%), giảm tử vong do suy cơ quan kéo dài, kiểm soát biến chứng hoại tử tụy nhiễm trùng',
    keyResults: 'Truyền dịch vừa phải 1.5 ml/kg/h bằng LR an toàn; CẤM kháng sinh dự phòng thường quy; Bắt đầu ăn đặc ít béo sớm; Trì hoãn can thiệp hoại tử đến khi tạo WON (> 4 tuần) theo chiến lược Step-Up; Chống chỉ định LR ở thể cường cận giáp.',
    summary: 'Bản cập nhật hướng dẫn điều trị toàn diện 18 miền lâm sàng lớn nhất trong 10 năm qua của Hiệp hội Tụy học Quốc tế (IAP): Chuẩn hóa chẩn đoán, truyền dịch LR vừa phải, dinh dưỡng sớm, chỉ định ERCP và chiến lược Step-Up.',
    detailedConclusion: 'Chiến lược truyền dịch vừa phải bằng LR kết hợp dinh dưỡng sớm và can thiệp Step-Up xâm lấn tối thiểu sau 4 tuần là nền tảng quản lý hiện đại giúp giảm tỷ lệ tử vong và biến chứng trong viêm tụy cấp.'
  },
  {
    id: '2021-aag-nafld',
    title: 'AGA 2021: Thay Đổi Lối Sống, Chế Độ Ăn & Luyện Tập Giảm Cân Trong Quản Lý NAFLD/NASH',
    titleEn: 'AGA Clinical Practice Update on Lifestyle Modification Using Diet and Exercise to Achieve Weight Loss in the Management of Nonalcoholic Fatty Liver Disease: Expert Review',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2021,
    organization: 'Hiệp hội Tiêu hóa Hoa Kỳ (AGA)',
    journal: 'Gastroenterology',
    file: '2021-aag-nafld.html',
    conditionKey: 'masld-mash',
    icd10: ['K76.0', 'K75.81', 'E66', 'E88.81'],
    intervention: 'Chế độ ăn giảm 500-1000 kcal/ngày, Chế độ ăn Địa Trung Hải, Tập Aerobic 150-300 min/tuần + Kháng lực, Kiêng rượu, Dinh dưỡng Protein cao 1.2-1.5 g/kg/ngày cho xơ gan giảm cơ',
    primaryEndpoint: 'Giảm mỡ gan (≥5% TBW), thoái lui viêm gan NASH (≥7% TBW), đảo ngược xơ hóa gan (≥10% TBW)',
    keyResults: 'HBAR: Giảm mỡ gan: ≥ 5% TBW | Thoái lui NASH: ≥ 7% TBW | Đảo ngược xơ hóa: ≥ 10% TBW (45% BN) | Đảo ngược thể gầy (3-5% TBW): 50% BN | Uống rượu 9-20g/d: Tăng 2x biến cố gan',
    summary: 'Đồng thuận thực hành lâm sàng của AGA về can thiệp lối sống trong NAFLD/NASH: Xác lập các mốc giảm cân mô học then chốt, ưu tiên chế độ ăn Địa Trung Hải, quản lý NAFLD thể gầy (giảm 3-5% TBW) và dinh dưỡng chống teo cơ ở xơ gan.',
    detailedConclusion: 'Thay đổi lối sống là nền tảng đầu tay cho mọi bệnh nhân NAFLD. Mục tiêu giảm ≥10% TBW để cải thiện xơ hóa gan. Tập thể dục giúp giảm mỡ gan độc lập với giảm cân. Người từng hút thuốc bắt buộc kiêng cồn hoàn toàn.'
  },
  {
    id: '2024-acg-viemgandoruou',
    title: 'ACG 2024: Hướng Dẫn Lâm Sàng Bệnh Gan Do Rượu (ALD) & Viêm Gan Do Rượu Cấp (AH)',
    titleEn: 'ACG Clinical Guideline: Alcohol-Associated Liver Disease',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2024,
    organization: 'American College of Gastroenterology (ACG)',
    journal: 'Am J Gastroenterol',
    file: '2024-acg-viemgandoruou.html',
    conditionKey: 'cirrhosis',
    icd10: ['K70', 'K70.1', 'K70.3', 'K70.9', 'F10.2'],
    intervention: 'Chẩn đoán theo NIAAA, Phân tầng MELD > 20 (Severe AH), Prednisolone 40mg/ngày x 28 ngày + IV NAC 5 ngày, Dừng thuốc nếu Lille > 0.45, Dinh dưỡng 35 kcal/kg + Kẽm, Baclofen điều trị AUD, Ghép gan sớm (Early LT)',
    primaryEndpoint: 'Tỷ lệ sống sót 28 ngày, 90 ngày và sống sót sau ghép gan sớm',
    keyResults: 'HBAR: MELD > 20: Severe AH (Tử vong 90d ~ 20%) | Lille <= 0.45: Đáp ứng tiếp tục 28d | Prednisolone + IV NAC 5d: Giảm 85% tử vong AH | Sống sót 3 năm Ghép gan sớm (ACCELERATE-AH): 84% (vs 24% không ghép) | Thiếu Kẽm: Tăng 10.6x tử vong',
    summary: 'Hướng dẫn thực hành lâm sàng toàn diện của ACG về ALD và Viêm gan do rượu (AH): Tiêu chuẩn NIAAA chẩn đoán không cần sinh thiết cho Probable AH, phân tầng MELD, cửa sổ trị liệu Corticosteroids (MELD 21-39), dừng thuốc theo Lille Score, điều trị AUD bằng Baclofen và chỉ định Ghép gan sớm bỏ quy tắc 6 tháng.',
    detailedConclusion: 'MELD > 20 là chỉ định điều trị Prednisolone kết hợp IV NAC. Bắt buộc tính Lille score ngày 4 hoặc 7 để dừng ngay steroids nếu không đáp ứng nhằm tránh tử vong do nấm xâm lấn. Bệnh nhân không đáp ứng nội khoa cần được đánh giá Ghép gan sớm.'
  },
  {
    id: '2022-acg-gerd',
    title: 'ACG 2022: Hướng Dẫn Lâm Sàng Chẩn Đoán & Điều Trị Bệnh Trào Ngược Dạ Dày - Thực Quản (GERD)',
    titleEn: 'ACG Clinical Guideline for the Diagnosis and Management of Gastroesophageal Reflux Disease',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2022,
    organization: 'American College of Gastroenterology (ACG)',
    journal: 'Am J Gastroenterol',
    file: '2022-acg-gerd.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K21', 'K21.0', 'K21.9', 'K20'],
    intervention: 'Thử nghiệm PPI 8 tuần 1 lần/ngày trước ăn 30-60p, EGD sau ngưng PPI 2-4 tuần, đo trào ngược Off PPI khi EGD bình thường/LA A, PPI BID cho triệu chứng ngoài thực quản hỗn hợp, PPI duy trì vô thời hạn cho LA C/D, can thiệp (Nissen, MSA, TIF, RYGB)',
    primaryEndpoint: 'Kiểm soát triệu chứng ợ nóng/trớ, làm lành viêm thực quản bào mòn, phòng ngừa biến chứng loét, hẹp và thực quản Barrett',
    keyResults: 'PPI vượt trội H2RA trong làm lành và duy trì; Uống PPI trước ăn 30-60p tối ưu hiệu quả; Duy trì PPI vô thời hạn cho LA C/D; RCT Moayyedi trên 17.598 BN chứng minh PPI dài hạn an toàn không tăng nguy cơ tim mạch/thận/xương (nguy cơ duy nhất có ý nghĩa là nhiễm trùng ruột OR 1.33).',
    summary: 'Hướng dẫn thực hành lâm sàng toàn diện của ACG: Định nghĩa khách quan GERD, lưu đồ phân nhánh EGD và đo theo dõi trào ngược, 11 biện pháp thay đổi lối sống (Table 3), tiếp cận triệu chứng ngoài thực quản, quản lý kháng trị và bằng chứng an toàn dài hạn của PPI.',
    detailedConclusion: 'Thử PPI 8 tuần trước ăn là bước đầu tay cho triệu chứng điển hình; chỉ đo trào ngược Off PPI khi EGD không có tổn thương khách quan; bệnh nhân viêm thực quản độ C/D bắt buộc duy trì PPI dài hạn.'
  },
  {
    id: '2021-acg-ibs',
    title: 'ACG 2021: Hướng Dẫn Lâm Sàng Quản Lý Hội Chứng Ruột Kích Thích (IBS)',
    titleEn: 'ACG Clinical Guideline: Management of Irritable Bowel Syndrome',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2021,
    organization: 'American College of Gastroenterology (ACG)',
    journal: 'Am J Gastroenterol',
    file: '2021-acg-ibs.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K58', 'K58.0', 'K58.1', 'K58.2', 'K58.8'],
    intervention: 'Chiến lược chẩn đoán chủ động (Rome IV + BSFS 2 tuần), loại trừ Celiac (tTG-IgA) & IBD (Calprotectin phân/CRP), Low-FODMAP 3 giai đoạn, Chất xơ hòa tan (Psyllium), Linaclotide/Plecanatide/Lubiprostone cho IBS-C, Rifaximin/Eluxadoline/Alosetron cho IBS-D, TCAs liều thấp, Tâm lý ruột (CBT-GI/GDH)',
    primaryEndpoint: 'Giảm triệu chứng đau bụng tái phát, bình thường hóa tần suất và hình thái phân, cải thiện chất lượng sống',
    keyResults: 'Chẩn đoán chủ động giảm 40% chi phí y tế; Psyllium hiệu quả (NNT=7); Linaclotide (NNT=6); Rifaximin 14 ngày (NNT=9); TCAs liều thấp (NNT=4.5); Tâm lý GDPs (NNT=4); Chống chỉ định FMT và Eluxadoline ở người đã cắt túi mật.',
    summary: 'Hướng dẫn chuẩn GRADE toàn diện của ACG: 25 câu hỏi lâm sàng (9 chẩn đoán + 16 điều trị), tiêu chuẩn Rome IV, thang điểm Bristol, phác đồ dược lý đích cho từng phân nhóm IBS-C/D/M và can thiệp điều hòa trục não - ruột.',
    detailedConclusion: 'Chẩn đoán tự tin dựa trên tiêu chuẩn Rome IV và xét nghiệm định hướng tối thiểu; cá thể hóa trị liệu theo phân nhóm Bristol; ưu tiên secretagogues cho IBS-C và Rifaximin/TCAs cho IBS-D.'
  },
  {
    id: '2025-bsg-ibd',
    title: 'BSG 2025: Hướng Dẫn Lâm Sàng Quản Lý & Điều Trị Bệnh Viêm Ruột (IBD) Ở Người Lớn',
    titleEn: 'British Society of Gastroenterology guidelines on inflammatory bowel disease in adults: 2025',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2025,
    organization: 'British Society of Gastroenterology (BSG)',
    journal: 'Gut',
    file: '2025-bsg-ibd.html',
    conditionKey: 'ibd',
    icd10: ['K50', 'K51', 'K50.9', 'K51.9'],
    intervention: 'Phân loại Montreal/Paris, Quy trình sinh thiết >= 2 mẫu/vị trí, Treat-to-Target (FC, Endoscopic Healing, Transmural Healing), Sàng lọc TB/EBV/VZV, Dự phòng VTE bằng LMWH 100% khi nhập viện, TDM Thiopurine (6-TGN 235-450) & Kháng TNF, 5-ASA & Upadacitinib/Infliximab/Vedolizumab, Lưu đồ cấp cứu ASUC ngày 3-7, Infliximab cho CD quanh hậu môn, Tiếp tục Biologics/Anti-TNF suốt thai kỳ, CẤM tạo túi IPAA khi dùng steroid.',
    primaryEndpoint: 'Đạt thuyên giảm lâm sàng, chữa lành niêm mạc nội soi, bình thường hóa Calprotectin phân, phòng ngừa biến chứng xơ hẹp và giảm tỷ lệ cắt đoạn ruột.',
    keyResults: 'HBAR: Sinh thiết chuẩn: >=2 mẫu/vị trí | VTE Dự phòng: Bắt buộc 100% nhập viện | ASUC Kháng Steroid N3: Rescue Infliximab/Ciclosporin | 6-TGN Đơn trị: 235-450 pmol/8x10^8 RBC | Anti-TNF Thai kỳ: Tiếp tục suốt thai kỳ',
    summary: 'Bản cập nhật hướng dẫn thực hành lâm sàng toàn diện của Hội Tiêu hóa Anh quốc (BSG) về IBD: Chẩn đoán theo Montreal/Paris, Treat-to-Target, sàng lọc an toàn trước thuốc sinh học, giám sát nồng độ thuốc TDM, phác đồ điều trị UC/CD, thuật toán xử trí ASUC tại bệnh viện, quản lý thai kỳ và ngoại khoa chu phẫu.',
    detailedConclusion: 'Áp dụng tiếp cận cá thể hóa Treat-to-Target; sàng lọc an toàn hệ thống trước liệu pháp nâng cao; kiểm soát chặt chẽ cấp cứu ASUC theo mốc ngày 3 và ngày 7; duy trì thuốc sinh học suốt thai kỳ an toàn.'
  },

  // --- SẢN PHỤ KHOA (OBSTETRICS & GYNECOLOGY) ---
  {
    id: '2026-byt-u-xo-tu-cung',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Xử trí U xơ Tử cung (Uterine Fibroids)',
    titleEn: 'National Guidelines on Management of Uterine Leiomyomas',
    sourceType: 'vn-moh',
    specialty: 'obgyn',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-u-xo-tu-cung.html',
    conditionKey: 'uterine-fibroids',
    icd10: ['D25', 'D25.9'],
    intervention: 'Phân loại vị trí FIGO, theo dõi định kỳ, điều trị nội khoa (Dụng cụ tử cung chứa Levonorgestrel, chất đồng vận/đối vận GnRH), can thiệp nút mạch (UAE), bóc u hoặc cắt tử cung',
    primaryEndpoint: 'Kiểm soát xuất huyết tử cung bất thường (AUB), giảm đau vùng chậu, bảo tồn khả năng sinh sản nếu có nhu cầu',
    summary: 'Hướng dẫn phân loại u xơ theo vị trí cơ tử cung, chỉ định can thiệp phẫu thuật vs điều trị bảo tồn nội khoa cá thể hóa.',
    detailedConclusion: 'U xơ dưới niêm mạc (FIGO 0, 1, 2) gây rong kinh rong huyết ưu tiên can thiệp nội soi buồng tử cung bóc nhân xơ.'
  },

  // --- DƯỢC LÝ & SỬ DỤNG KHÁNG SINH (PHARMACOLOGY) ---
  {
    id: '2026-lww-khang-sinh-co-ban',
    title: 'Nguyên lý Sử dụng Kháng sinh Hợp lý và Cơ chế Đề kháng Vi sinh',
    titleEn: 'Principles of Antimicrobial Therapy and Resistance Mechanisms',
    sourceType: 'intl-study',
    specialty: 'infect',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'LWW Medical Pharmacology Series',
    journal: 'Lancet Infect Dis',
    file: '2026-lww-khang-sinh-co-ban.html',
    conditionKey: 'icu',
    icd10: ['Z16', 'A41'],
    intervention: 'Phân nhóm kháng sinh diệt khuẩn vs kìm khuẩn, phụ thuộc thời gian (T > MIC) vs phụ thuộc nồng độ (Cmax/MIC, AUC/MIC), quản lý kháng sinh (AMS)',
    primaryEndpoint: 'Tối ưu hiệu quả diệt khuẩn và làm chậm sự phát triển của vi khuẩn đa kháng',
    summary: 'Cẩm nang tra cứu phổ kháng khuẩn của các nhóm kháng sinh chính: Penicillin, Cephalosporin thế hệ 1-5, Carbapenem, Aminoglycoside, Macrolide, Fluoroquinolone.',
    detailedConclusion: 'Áp dụng nguyên tắc 5R trong sử dụng kháng sinh: Đúng bệnh, đúng thuốc, đúng liều, đúng đường dùng, và đúng thời gian.'
  },
  {
    id: '2026-nature-reviews-mrsa',
    title: 'Nature Reviews 2026: Tụ Cầu Vàng Kháng Methicillin (MRSA) — Dịch Tễ, Cơ Chế, Động Học Cư Trú & Phác Đồ',
    titleEn: 'Methicillin-resistant Staphylococcus aureus (Nature Reviews Disease Primers 2026)',
    sourceType: 'intl-study',
    specialty: 'infect',
    design: 'review',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Nature Reviews Disease Primers',
    journal: 'Nat Med',
    file: '2026-nature-reviews-mrsa.html',
    conditionKey: 'icu',
    icd10: ['A41.02', 'B95.62', 'Z16.24'],
    intervention: 'TDM Vancomycin (AUC/MIC 400-600), Daptomycin (8-10 mg/kg, chống chỉ định viêm phổi), Linezolid (ưu tiên viêm phổi hoại tử), Ceftaroline/Ceftobiprole (gắn PBP2a), Rạch dẫn lưu áp-xe, Khử trùng Mupirocin + Chlorhexidine',
    primaryEndpoint: 'Diệt khuẩn làm sạch cấy máu, giảm tỷ lệ tử vong do sốc nhiễm khuẩn/viêm phổi hoại tử, ngăn ngừa biến chứng viêm nội tâm mạc và kiểm soát lây truyền bệnh viện',
    keyResults: 'HBAR: Tử vong toàn cầu: >130.000 ca/năm | Giảm BSI Mỹ: 74% (2005-2016) | Đích Vanco: AUC/MIC 400-600 | Rút ngắn PCR: 1.7 ngày | Kháng Daptomycin BSI: 39% nếu không kiểm soát nguồn | Giảm lây REDUCE-MRSA: HR 0.63',
    summary: 'Bài tổng quan đỉnh cao của Nature Reviews Disease Primers 2026 về MRSA: Dịch tễ học toàn cầu, cơ chế đề kháng PBP2a và các biến thể BORSA/MOD-SA/OS-MRSA, động học cư trú tại hốc mũi và ruột, cơ chế né tránh miễn dịch Trojan Horse trong bạch cầu, phác đồ điều trị kháng sinh tối ưu và chiến lược kiểm soát nhiễm khuẩn.',
    detailedConclusion: 'Chẩn đoán nhanh bằng Real-time PCR và đĩa Cefoxitin; cá thể hóa kháng sinh theo hội chứng (ưu tiên Linezolid cho viêm phổi, Daptomycin cho nhiễm khuẩn huyết, Vancomycin TDM AUC/MIC 400-600); bắt buộc rạch dẫn lưu áp-xe và rút bỏ catheter nhiễm trùng.'
  },
  {
    id: '2021-acg-ugib',
    title: 'ACG 2021: Hướng dẫn Lâm sàng về Xuất huyết Tiêu hóa trên và Loét Dạ dày - Tá tràng',
    titleEn: 'ACG Clinical Guideline: Upper Gastrointestinal and Ulcer Bleeding (2021)',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2021,
    organization: 'American College of Gastroenterology (ACG)',
    journal: 'Gastroenterology',
    file: '2021-acg-ugib.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K25', 'K26', 'K27', 'K92.0', 'K92.2'],
    intervention: 'Thang điểm Glasgow-Blatchford (GBS 0-1 xuất viện ngoại trú), Truyền máu giới hạn Hb < 7 g/dL, Erythromycin 250mg IV trước soi 30-90p, Nội soi trong 24h, Can thiệp cầm máu theo Forrest (Nhiệt/Clip/Cồn, Cấm Epinephrine đơn trị), Phác đồ PPI liều cao 72h + PPI liều gấp đôi đến ngày 14, Ưu tiên soi lần 2 và nút mạch TAE',
    primaryEndpoint: 'Kiểm soát cầm máu ban đầu, giảm tỷ lệ tái xuất huyết 30 ngày, giảm nhu cầu phẫu thuật cấp cứu và giảm tỷ lệ tử vong',
    keyResults: 'HBAR: Độ nhạy GBS=1: 99% | Giảm tử vong truyền máu Hb<7: 44% (p=0.02) | Giảm soi lại do Erythro: OR 0.51 | Cầm máu nhiệt vs Ko can thiệp: RR 0.44 | Epinephrine phối hợp vs Đơn trị: RR 0.34 | Giảm biến chứng TAE vs Mổ hở: OR 0.45',
    summary: 'Hướng dẫn thực hành y học chứng cứ (GRADE) toàn diện của ACG về xử trí xuất huyết tiêu hóa trên cấp tính: Phân tầng nguy cơ cực thấp GBS 0-1, chiến lược truyền máu giới hạn Hb < 7 g/dL, thời điểm nội soi trong 24h, can thiệp cầm máu theo hình thái đáy loét Forrest và tối ưu hóa phác đồ PPI liều cao 72h.',
    detailedConclusion: 'Áp dụng GBS 0-1 để cho xuất viện an toàn; chỉ truyền máu khi Hb < 7 g/dL; truyền Erythromycin 250mg IV trước soi; nội soi can thiệp loét Forrest Ia, Ib, IIa bằng nhiệt/clip (cấm epinephrine đơn trị); duy trì PPI liều cao 72h tiếp nối liều gấp đôi đường uống đến ngày 14; ưu tiên nội soi lần 2 và nút mạch TAE khi tái xuất huyết/thất bại.'
  },
  {
    id: '2020-jsge-pud',
    title: 'JSGE 2020: Hướng dẫn Lâm sàng Dựa trên Bằng chứng về Bệnh Loét Dạ dày - Tá tràng',
    titleEn: 'Evidence-based Clinical Practice Guidelines for Peptic Ulcer Disease 2020 (JSGE)',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2021,
    organization: 'Japanese Society of Gastroenterology (JSGE)',
    journal: 'J Gastroenterol',
    file: '2020-jsge-pud.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K25', 'K26', 'K27', 'K28', 'K92.0', 'K92.2'],
    intervention: 'Duy trì Aspirin khi xuất huyết loét nguy cơ cao, PPI liều chuẩn sau cầm máu nội soi, Phác đồ Vonoprazan 3 thuốc bước 1 (VPZ-AC/VPZ-AM), Phác đồ cứu vãn bước 2 PAM (PPI/VPZ + Amox + Metro), Phác đồ bước 3 Sitafloxacin, Celecoxib + PPI dự phòng loét/chảy máu do NSAIDs/LDA, PPI cho loét mỏm cắt sau mổ & điều trị duy trì loét vô căn',
    primaryEndpoint: 'Tỷ lệ liền sẹo loét dạ dày tá tràng, tỷ lệ tiệt trừ H. pylori, giảm biến cố tái xuất huyết tiêu hóa và giảm tử vong do biến cố tim mạch tắc mạch',
    keyResults: 'HBAR: Tiệt trừ Bước 1 VPZ vs PPI: OR 0.28 (p<0.00001) | Bước 2 PAM vs PAC: OR 0.14 (p<0.00001) | Giảm XHTH DAPT + PPI: RR 0.26 (p=0.0002) | Liền sẹo NSAID PPI vs H2RA: OR 0.48 (p<0.00001) | Dự phòng thứ phát NSAID: OR 0.14 (p<0.00001) | COX-2 giảm loét DD: RR 0.21 | Ngừa chảy máu LDA PPI vs H2RA: RR 0.28 (p<0.0001)',
    summary: 'Hướng dẫn thực hành y học chứng cứ (GRADE) toàn diện của Hiệp hội Tiêu hóa Nhật Bản (JSGE) với 28 Câu hỏi lâm sàng (CQ-1 đến CQ-28): Duy trì aspirin ở bệnh nhân nguy cơ huyết khối cao khi xuất huyết, phác đồ tiệt trừ H. pylori bước 1 vượt trội chứa Vonoprazan (P-CAB), phân tầng dự phòng loét và biến chứng chảy máu do NSAIDs / Aspirin liều thấp (LDA), cùng xử trí loét vô căn và loét mỏm cắt dạ dày.',
    detailedConclusion: 'Tiếp tục duy trì Aspirin khi xuất huyết nếu nguy cơ tắc mạch cao; dùng PPI liều chuẩn sau cầm máu nội soi; ưu tiên phác đồ 3 thuốc chứa Vonoprazan (VPZ 20mg x 2 + Amox + Clari/Metro) bước 1; phác đồ cứu vãn bước 2 PAM; phối hợp Celecoxib + PPI ở bệnh nhân tiền sử loét/chảy máu dùng NSAID/LDA; duy trì PPI kéo dài cho loét vô căn và khởi trị ngay bằng PPI cho loét mỏm cắt.'
  }
];

if (typeof window !== 'undefined') {
  (window as any).KHO_GUIDELINES_STATIC = KHO_GUIDELINES_STATIC;
}
