/**
 * CliniPortal 2.0 — Tủ Sách Phác Đồ Tim Mạch & Chuyển Hóa
 * Path: src/content/protocols/registry/cardio-protocols.ts
 *
 * Ngăn tủ chuyên sâu Tim mạch: Hội chứng vành cấp (ACS), Suy tim cấp & Phù phổi cấp,
 * Suy tim mạn HFrEF 4 Trụ cột GDMT, Cơn Tăng huyết áp cấp cứu & Rung nhĩ AF-CARE.
 */

import { ClinicalProtocol } from '../protocol-types';

export const CARDIO_PROTOCOLS: ClinicalProtocol[] = [
  // ═══ NGĂN 1: HỘI CHỨNG VÀNH CẤP (ACS: STEMI & NSTE-ACS - ESC 2023) ═══
  {
    id: 'pddt-acs-esc-2023',
    title: 'Phác đồ Xử trí & Phân tầng Hội chứng Vành cấp (ACS: STEMI / NSTE-ACS)',
    titleEn: 'Acute Coronary Syndromes (ACS) Clinical Management & Reperfusion Protocol',
    aliases: ['Hội chứng vành cấp', 'Nhồi máu cơ tim', 'STEMI', 'NSTEMI', 'Đau ngực cấp'],
    icd10: ['I21', 'I21.0', 'I21.9', 'I20.0'],
    specialty: 'cardio',
    triageLevel: 'emergency',
    guidelineSource: 'ESC Guidelines for the management of acute coronary syndromes (2023 / 2024)',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Quy trình tiếp cận đau ngực cấp trong 10 phút đầu (ECG 12 chuyển đạo), phân định STEMI (kích hoạt can thiệp PCI khẩn < 90-120 phút) và NSTE-ACS (thuật toán hs-cTn 0h/1h), phác đồ kháng kết tập tiểu cầu kép DAPT và kháng đông.',
    redFlags: [
      'ECG có ST chênh lên ≥ 1mm ở ít nhất 2 chuyển đạo liên tiếp hoặc block nhánh trái mới xuất hiện.',
      'Đau ngực kiểu mạch vành dữ dội kéo dài > 20 phút không đáp ứng với Nitroglycerin.',
      'Huyết động bất ổn: Tụt huyết áp, sốc tim (Killip IV), phù phổi cấp do tim (Killip III).',
      'Rối loạn nhịp tim nguy hiểm: Rung thất, nhịp nhanh thất, Block nhĩ thất độ 3.',
    ],
    steps: [
      {
        stepId: 'step_1_ecg_10min',
        order: 1,
        phase: 'triage',
        title: '1. Tiếp nhận Đau ngực Cấp & Đo ECG 12 Chuyển đạo (≤ 10 phút)',
        timeframe: 'Trong 10 phút đầu',
        description: 'Đo và phân tích ECG 12 chuyển đạo trong vòng 10 phút kể từ lúc tiếp cận. Thở oxy nếu SpO2 < 90%. Thiết lập đường truyền tĩnh mạch và lắp monitor theo dõi nhịp tim liên tục.',
        conditionIf: 'ECG có ST chênh lên (STEMI)',
        conditionThen: 'Kích hoạt ngay Quy trình Báo động Đỏ Can thiệp Mạch Vành (Cath-Lab) < 90-120 phút.',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_stemi_reperfusion',
        order: 2,
        phase: 'first-line',
        title: '2. STEMI: Kháng Kết Tập Tiểu Cầu Kép (DAPT) & Nạp Kháng Đông',
        timeframe: 'Trước khi vào phòng can thiệp PCI',
        description: 'Nạp ngay DAPT bằng Aspirin + Thuốc ức chế P2Y12 thế hệ mới (Ticagrelor hoặc Prasugrel ưu tiên hơn Clopidogrel) + Heparin không phân đoạn (UFH) 70 - 100 UI/kg IV.',
        drugs: [
          {
            genericName: 'Aspirin',
            tradeNames: ['Aspégic', 'Cardiopirin'],
            route: 'PO',
            loadingDose: '150 - 300 mg (nhai nát hoặc hòa tan)',
            maintenanceDose: '75 - 100 mg uống 1 lần/ngày duy trì suốt đời',
            clinicalNotes: 'Nhai nát để đạt hấp thu và ức chế tiểu cầu tối đa trong vòng vài phút.',
          },
          {
            genericName: 'Ticagrelor',
            tradeNames: ['Brilinta'],
            route: 'PO',
            loadingDose: '180 mg (2 viên 90mg uống ngay)',
            maintenanceDose: '90 mg uống 2 lần/ngày trong 12 tháng',
            isHighAlert: true,
            clinicalNotes: 'Ức chế P2Y12 mạnh và nhanh hơn Clopidogrel. Tác dụng phụ thường gặp: Khó thở thoáng qua.',
          },
          {
            genericName: 'Clopidogrel',
            tradeNames: ['Plavix'],
            route: 'PO',
            loadingDose: '300 - 600 mg (nạp 600mg nếu can thiệp PCI cấp cứu)',
            maintenanceDose: '75 mg uống 1 lần/ngày',
            clinicalNotes: 'Chỉ dùng khi có chống chỉ định với Ticagrelor/Prasugrel hoặc bệnh nhân cần dùng kèm Kháng đông DOAC.',
          },
          {
            genericName: 'Heparin Không Phân Đoạn (UFH)',
            route: 'IV',
            loadingDose: '70 - 100 UI/kg tiêm tĩnh mạch bolus (hoặc 50 - 70 UI/kg nếu có dùng kháng GP IIb/IIIa)',
            maintenanceDose: 'Theo dõi aPTT hoặc ACT trong phòng Cath-lab',
            isHighAlert: true,
            clinicalNotes: 'Chuyển sang Enoxaparin 1mg/kg x 2 lần/ngày nếu không can thiệp PCI.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_3_nste_acs_troponin',
        order: 3,
        phase: 'first-line',
        title: '3. NSTE-ACS: Thuật toán hs-cTn 0h/1h & Phân tầng Nguy cơ GRACE',
        timeframe: 'Giờ thứ 0 và Giờ thứ 1',
        description: 'Lấy máu xét nghiệm Troponin siêu nhạy (hs-cTnI / hs-cTnT) tại thời điểm 0h và lặp lại chính xác sau 1h (hoặc 2h) để tính delta động học. Tính điểm nguy cơ GRACE score.',
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_statin_acei',
        order: 4,
        phase: 'recovery',
        title: '4. Điều Trị Nội Khoa Tối Ưu Nền Tảng (GDMT)',
        timeframe: 'Trong 24 giờ đầu',
        description: 'Khởi đầu Statin cường độ cao sớm (Atorvastatin 40-80mg hoặc Rosuvastatin 20-40mg) bất kể mức LDL-C ban đầu. Khởi đầu thuốc chẹn Beta giao cảm và ức chế men chuyển (ACEi/ARB) khi huyết động đã ổn định.',
        drugs: [
          {
            genericName: 'Atorvastatin',
            tradeNames: ['Lipitor'],
            route: 'PO',
            loadingDose: '80 mg uống ngay ngày đầu',
            maintenanceDose: '40 - 80 mg uống mỗi tối (đích LDL-C < 55 mg/dL và giảm ≥ 50%)',
            clinicalNotes: 'Liệu pháp Statin liều cao sớm giúp ổn định mảng xơ vữa và kháng viêm nội mạc.',
          },
        ],
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Tiền sử Xuất huyết tiêu hóa gần / Đang chảy máu hoạt động',
        forbiddenDrugOrAction: 'Phối hợp DAPT + Kháng đông mà không có thuốc ức chế bơm proton (PPI)',
        dangerLevel: 'absolute',
        explanation: 'Nguy cơ tái phát xuất huyết tiêu hóa ồ ạt do tác động hiệp đồng của thuốc chống huyết khối.',
        recommendation: 'BẮT BUỘC phối hợp thêm PPI (Pantoprazole 40mg hoặc Esomeprazole 40mg). Cân nhắc rút ngắn thời gian DAPT xuống 1 - 3 tháng.',
      },
      {
        conflictWithCondition: 'Nhồi máu cơ tim thất phải / HA tâm thu < 90 mmHg / Đang dùng thuốc ức chế PDE-5 (Sildenafil)',
        forbiddenDrugOrAction: 'Nitroglycerin ngậm dưới lưỡi hoặc truyền tĩnh mạch',
        dangerLevel: 'absolute',
        explanation: 'Nitroglycerin gây giãn tĩnh mạch làm giảm tiền gánh đột ngột, dẫn đến tụt HA trầm trọng và ngừng tim khi kết hợp thuốc PDE-5.',
        recommendation: 'Chống chỉ định tuyệt đối Nitrat nếu BN đã dùng Sildenafil trong 24h (hoặc Tadalafil trong 48h). Bù dịch NaCl 0.9% nếu NMCT thất phải.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Can Thiệp Mạch Vành Qua Da (PCI Cấp Cứu / Sớm)',
        approachType: 'standard-invasive',
        pros: [
          'Tái thông dòng chảy mạch vành tức thì, giảm tối đa diện tích hoại tử cơ tim.',
          'Giảm rõ rệt tỷ lệ tử vong tim mạch, tái nhồi máu và suy tim sau nhồi máu.',
        ],
        cons: [
          'Thủ thuật xâm lấn, nguy cơ biến chứng tại vị trí chọc mạch (chảy máu, tụ máu) và suy thận do thuốc cản quang (CIN).',
          'Bắt buộc dùng DAPT liên tục ít nhất 6 - 12 tháng.',
        ],
        estimatedCost: 'high',
        suitableFor: 'Mọi bệnh nhân STEMI trong 12h đầu và bệnh nhân NSTE-ACS có điểm GRACE > 140 hoặc huyết động không ổn định.',
      },
      {
        optionName: 'Phương án 2: Điều Trị Nội Khoa Bảo Tồn Tối Ưu (Medical Therapy Alone)',
        approachType: 'conservative',
        pros: [
          'Tránh các tai biến phẫu thuật/can thiệp mạch và nguy cơ suy thận do thuốc cản quang.',
        ],
        cons: [
          'Không giải quyết được tổn thương tắc nghẽn cơ học, nguy cơ đau ngực tái phát và biến cố tim mạch cao hơn.',
        ],
        estimatedCost: 'medium',
        suitableFor: 'Bệnh nhân NSTE-ACS nguy cơ rất thấp (GRACE < 109), hoặc bệnh nhân từ chối can thiệp/có nhiều bệnh lý ác tính giai đoạn cuối.',
      },
    ],
    cardioDetails: {
      ecgBiomarkers: 'Đo ECG 12 chuyển đạo trong <= 10 phút. Định lượng hs-cTnI / hs-cTnT 0h/1h (hoặc 0h/2h) theo thuật toán ESC.',
      antiplateletAnticoagulation: 'DAPT (Aspirin 300mg + Ticagrelor 180mg / Clopidogrel 600mg) + Heparin UFH 70-100 UI/kg hoặc Enoxaparin 1mg/kg x 2 lần/ngày.',
      gdmtPillars: 'Statin cường độ cao (Atorvastatin 80mg) + Khởi đầu sớm ACEi/ARB và Beta-blocker khi huyết động ổn định.',
      cardiacScores: ['Thang điểm GRACE (Phân tầng nguy cơ tử vong)', 'Thang điểm TIMI', 'Phân độ Killip I-IV'],
    },
    dischargeCriteria: [
      'Hết đau ngực hoàn toàn liên tục ≥ 48 giờ.',
      'Huyết động ổn định, không có suy tim tiến triển (Killip I).',
      'Đã hoàn thành phân tầng nguy cơ và tối ưu hóa đơn thuốc điều trị nền (Aspirin + P2Y12i + Statin + ACEi/ARB + Beta-blocker).',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 2: SUY TIM CẤP & PHÙ PHỔI CẤP DO TIM (ACUTE HEART FAILURE - ESC 2023) ═══
  {
    id: 'pddt-acute-heart-failure-esc',
    title: 'Phác đồ Xử trí Suy Tim Cấp & Phù Phổi Cấp do Tim (ESC 2023 / AHA 2024)',
    titleEn: 'Acute Heart Failure & Acute Cardiogenic Pulmonary Edema Clinical Protocol',
    aliases: ['Suy tim cấp', 'Phù phổi cấp do tim', 'AHF', 'Acute Pulmonary Edema', 'Killip III'],
    icd10: ['I50', 'I50.1', 'I50.9'],
    specialty: 'cardio',
    triageLevel: 'emergency',
    guidelineSource: 'ESC Guidelines for the diagnosis and treatment of acute and chronic heart failure (2023 / 2024)',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Phân loại nhanh theo kiểu hình huyết động (Ấm-Ướt 90%, Lạnh-Ướt, Lạnh-Khô, Ấm-Khô). Bộ 3 can thiệp khẩn cho kiểu hình Ấm - Ướt: Ngồi thõng 2 chân + Lợi tiểu quai Furosemide tĩnh mạch + Giãn mạch Nitroglycerin/Isosorbide + Thở máy không xâm lấn CPAP/BiPAP.',
    redFlags: [
      'Bệnh nhân khó thở dữ dội, tím tái, ho khạc bọt hồng, nghe ran ẩm dâng nhanh như thủy triều ở 2 đáy phổi.',
      'Suy hô hấp cấp: Nhịp thở > 30 l/p, SpO2 < 85%, co kéo cơ hô hấp phụ.',
      'Tụt huyết áp / Sốc tim (Kiểu hình Lạnh - Ướt): HA tâm thu < 90 mmHg kèm giảm tưới máu mô (chi lạnh, thiểu niệu, lú lẫn).',
    ],
    steps: [
      {
        stepId: 'step_1_position_oxygen_cpap',
        order: 1,
        phase: 'triage',
        title: '1. Tư Thế Ngồi Thõng Chân & Thở Máy Không Xâm Lấn (CPAP / BiPAP)',
        timeframe: 'Phút 0 - 10',
        description: 'Cho bệnh nhân ngồi tư thế Fowler cao thõng 2 chân xuống giường để giảm tiền gánh hồi lưu về tim. Thở CPAP áp lực dương liên tục (PEEP 5 - 10 cmH2O) hoặc BiPAP để giảm công thở và đẩy dịch phù phế nang trở lại lòng mạch. Thở oxy duy trì SpO2 94 - 98%.',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_iv_loop_diuretics',
        order: 2,
        phase: 'first-line',
        title: '2. Lợi Tiểu Quai Tĩnh Mạch (Furosemide IV Bolus)',
        timeframe: 'Trong 30 - 60 phút đầu',
        description: 'Tiêm tĩnh mạch Furosemide ngay lập tức: Nếu chưa từng dùng lợi tiểu trước đó: 20 - 40 mg IV bolus; Nếu đang dùng lợi tiểu uống mạn tính: Dùng liều IV tương đương 1 - 2 lần liều uống hàng ngày. Đánh giá đáp ứng sau 2 giờ: Đích bài niệu > 100 - 150 mL/giờ hoặc Natri niệu > 50 - 70 mEq/L.',
        drugs: [
          {
            genericName: 'Furosemide',
            tradeNames: ['Lasix'],
            route: 'IV',
            loadingDose: '40 - 80 mg IV bolus chậm trong 2 - 3 phút',
            maintenanceDose: 'Lặp lại hoặc tăng gấp đôi liều sau 2 giờ nếu Natri niệu < 50 mEq/L (hoặc truyền liên tục 5 - 20 mg/giờ)',
            renalAdjustment: 'Cần tăng liều Furosemide ở bệnh nhân suy thận nặng (eGFR < 30) do giảm bài tiết thuốc vào lòng ống thận.',
            clinicalNotes: 'Tác dụng giãn tĩnh mạch xuất hiện sau 5-15 phút trước khi có tác dụng lợi niệu.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_vasodilators_nitrate',
        order: 3,
        phase: 'first-line',
        title: '3. Thuốc Giãn Mạch Nitrat Tĩnh Mạch (Khi HA Tâm Thu ≥ 110 mmHg)',
        timeframe: 'Khi huyết áp cho phép',
        description: 'Khởi đầu truyền Nitroglycerin hoặc Isosorbide Dinitrate qua bơm tiêm điện để giảm cả tiền gánh và hậu gánh tim, cải thiện sung huyết phổi nhanh chóng mà không làm tăng tiêu thụ oxy cơ tim.',
        drugs: [
          {
            genericName: 'Nitroglycerin truyền tĩnh mạch',
            route: 'IV',
            loadingDose: 'Khởi đầu 10 - 20 mcg/phút',
            maintenanceDose: 'Tăng dần mỗi 5 - 10 phút lên 50 - 200 mcg/phút (duy trì HA tâm thu > 90 - 100 mmHg)',
            isHighAlert: true,
            clinicalNotes: 'Hiệu quả đặc biệt cao ở bệnh nhân suy tim cấp kèm cơn tăng huyết áp.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_inotropes_cardiogenic_shock',
        order: 4,
        phase: 'refractory',
        title: '4. Sốc Tim / Kiểu hình Lạnh - Ướt: Vận Mạch & Tăng Co Bóp Dobutamin / Noradrenaline',
        timeframe: 'Khi có tụt huyết áp (HA tâm thu < 90 mmHg)',
        description: 'NGƯNG NGAY thuốc giãn mạch Nitrat. Dùng Dobutamin (2.5 - 10 mcg/kg/phút) để tăng co bóp cơ tim phối hợp Noradrenaline nếu có tụt HA nặng. Cân nhắc bóng đối xung nội động mạch chủ (IABP) hoặc ECMO/Impella nếu sốc tim kháng trị.',
        drugs: [
          {
            genericName: 'Dobutamin',
            route: 'IV',
            loadingDose: '2.5 - 5 mcg/kg/phút qua bơm tiêm điện',
            maintenanceDose: 'Chỉnh liều đến 10 - 20 mcg/kg/phút theo cung lượng tim',
            isHighAlert: true,
            clinicalNotes: 'Tác dụng inotrope dương tính mạnh qua thụ thể Beta-1. Có thể gây loạn nhịp tim.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_5_transition_gdmt',
        order: 5,
        phase: 'recovery',
        title: '5. Chuyển Tiếp Sang Điều Trị Suy Tim Mạn Nền Tảng (4 Trụ Cột GDMT)',
        timeframe: 'Trước khi xuất viện',
        description: 'Tối ưu hóa phác đồ 4 trụ cột trước khi ra viện: Tiếp tục hoặc bắt đầu lại thuốc Ức chế SGLT2i (Dapagliflozin / Empagliflozin), ARNI (Sacubitril/Valsartan), Chẹn Beta giao cảm và Kháng Aldosterone (MRA) khi đã hết sung huyết dịch hoàn toàn.',
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Đợt suy tim cấp mất bù đang sung huyết nặng / Đang khó thở khi nằm',
        forbiddenDrugOrAction: 'Tăng liều hoặc khởi đầu mới thuốc Chẹn Beta giao cảm liều cao',
        dangerLevel: 'absolute',
        explanation: 'Thuốc chẹn beta ức chế co bóp cơ tim cấp thời, làm nặng thêm tình trạng phù phổi và kích hoạt sốc tim.',
        recommendation: 'Nếu bệnh nhân đang dùng chẹn beta mạn tính: Duy trì liều cũ hoặc giảm 50% liều (chỉ ngưng nếu có sốc tim). KHÔNG khởi đầu liều mới cho đến khi hết sung huyết hoàn toàn.',
      },
      {
        conflictWithCondition: 'Hẹp van động mạch chủ khít / Bệnh cơ tim phì đại tắc nghẽn (HOCM)',
        forbiddenDrugOrAction: 'Dùng thuốc Giãn mạch Nitrat liều cao',
        dangerLevel: 'absolute',
        explanation: 'Giảm tiền gánh đột ngột ở bệnh nhân có tắc nghẽn đường ra thất trái gây trụy tuần hoàn và ngất.',
        recommendation: 'Tránh dùng Nitrat. Siêu âm tim tại giường để đánh giá chênh áp qua van trước khi dùng thuốc.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Hồi Sức Tích Cực Bằng Thở Máy CPAP Không Xâm Lấn + Lợi Tiểu Quai Tĩnh Mạch',
        approachType: 'standard-invasive',
        pros: [
          'Giảm 60% tỷ lệ phải đặt ống nội khí quản và giảm tử vong tại bệnh viện.',
          'Cải thiện tình trạng khó thở và sung huyết phổi trong vòng 30 - 60 phút.',
        ],
        cons: [
          'Bệnh nhân có cảm giác ngột ngạt hoặc khô niêm mạc do áp lực khí dương.',
        ],
        estimatedCost: 'medium',
        suitableFor: 'Mọi bệnh nhân phù phổi cấp do tim có suy hô hấp cấp SpO2 < 90%.',
      },
    ],
    cardioDetails: {
      ecgBiomarkers: 'Đo NT-proBNP (ngưỡng loại trừ suy tim cấp < 300 pg/mL, ngưỡng chẩn đoán > 450-1800 pg/mL theo tuổi). Đo Troponin loại trừ NMCT kèm theo.',
      antiplateletAnticoagulation: 'Enoxaparin 40mg/ngày tiêm dưới da dự phòng thuyên tắc huyết khối tĩnh mạch (VTE).',
      gdmtPillars: 'Khởi động sớm SGLT2i (Dapagliflozin 10mg) ngay trong đợt nằm viện; ARNI/ACEi + MRA khi hết sung huyết.',
      cardiacScores: ['Phân loại lâm sàng 4 kiểu hình huyết động (Ấm-Ướt, Lạnh-Ướt, Lạnh-Khô, Ấm-Khô)', 'Phân độ Killip I-IV'],
    },
    dischargeCriteria: [
      'Hết khó thở khi nằm đầu bằng, không còn ran ẩm ở phổi.',
      'Đã chuyển sang lợi tiểu quai đường uống với liều ổn định liên tục ≥ 24 giờ.',
      'Chức năng thận và điện giải đồ (K+, Na+, Creatinine) ổn định.',
      'Đã thiết lập phác đồ 4 trụ cột GDMT dung nạp tốt và có lịch tái khám sau 1 - 2 tuần.',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 3: SUY TIM MẠN HFrEF VỚI 4 TRỤ CỘT GDMT (ESC / AHA 2024) ═══
  {
    id: 'pddt-hfref-gdmt-4pillars',
    title: 'Phác đồ Điều trị Suy Tim Mạn Phân Suất Tống Máu Giảm (HFrEF — 4 Trụ Cột GDMT)',
    titleEn: 'Management of Heart Failure with Reduced Ejection Fraction (HFrEF 4 GDMT Pillars)',
    aliases: ['Suy tim mạn HFrEF', '4 Trụ cột GDMT', 'ARNI', 'SGLT2i', 'Sacubitril/Valsartan'],
    icd10: ['I50.2', 'I50.22', 'I50.23'],
    specialty: 'cardio',
    triageLevel: 'outpatient',
    guidelineSource: 'ESC / AHA / ACC Guidelines for the Management of Heart Failure (2023 / 2024)',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Liệu pháp 4 trụ cột bắt buộc khởi đầu sớm đồng thời cho mọi bệnh nhân HFrEF (LVEF ≤ 40%): (1) Thuốc ức chế thụ thể Neprilysin - Angiotensin (ARNI: Sacubitril/Valsartan), (2) Thuốc Chẹn Beta giao cảm (Bisoprolol/Carvedilol/Metoprolol succinate), (3) Thuốc Kháng Thụ Thể Mineralocorticoid (MRA: Spironolactone), (4) Thuốc ức chế SGLT2 (Dapagliflozin/Empagliflozin).',
    redFlags: [
      'Tăng cân nhanh > 2 kg trong 3 ngày (dấu hiệu ứ dịch tiềm tàng).',
      'Khó thở kịch phát về đêm, phải ngồi dậy để thở (Orthopnea).',
      'Ngất xỉu hoặc cơn tiền ngất (nguy cơ rối loạn nhịp thất đe dọa đột tử).',
      'Kali máu > 5.5 mEq/L hoặc Creatinine tăng vọt > 50% so với nền.',
    ],
    steps: [
      {
        stepId: 'step_1_pillar_sglt2i_arni',
        order: 1,
        phase: 'first-line',
        title: '1. Khởi Đầu Trụ Cột 1 & 2: SGLT2i + ARNI (Sacubitril/Valsartan)',
        timeframe: 'Tuần 1 - 2',
        description: 'Khởi đầu SGLT2i (Dapagliflozin 10mg hoặc Empagliflozin 10mg 1 lần/ngày) - không cần chỉnh liều, có hiệu quả bảo vệ tim thận độc lập với ĐTĐ. Song song khởi đầu ARNI (Sacubitril/Valsartan 24/26mg hoặc 49/51mg x 2 lần/ngày). Chú ý: Nếu chuyển từ ACEi sang ARNI, bắt buộc ngưng ACEi đủ 36 giờ để tránh phù mạch.',
        drugs: [
          {
            genericName: 'Dapagliflozin / Empagliflozin',
            tradeNames: ['Forxiga', 'Jardiance'],
            route: 'PO',
            maintenanceDose: '10 mg uống 1 lần/ngày vào buổi sáng',
            renalAdjustment: 'Có thể dùng đến eGFR 20 mL/phút/1.73m2',
            clinicalNotes: 'Giảm 25-30% tử vong tim mạch và nhập viện vì suy tim. Tác dụng phụ: Nhiễm nấm sinh dục nhẹ.',
          },
          {
            genericName: 'Sacubitril / Valsartan (ARNI)',
            tradeNames: ['Entresto'],
            route: 'PO',
            loadingDose: '24/26 mg (hoặc 49/51 mg) uống 2 lần/ngày',
            maintenanceDose: 'Tăng liều gấp đôi mỗi 2 - 4 tuần đến liều đích 97/103 mg x 2 lần/ngày',
            renalAdjustment: 'Khởi đầu liều thấp 24/26mg nếu eGFR < 30 mL/phút',
            clinicalNotes: 'Ưu tiên hơn ACEi/ARB để giảm tử vong và tái nhập viện.',
          },
        ],
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_pillar_bb_mra',
        order: 2,
        phase: 'first-line',
        title: '2. Khởi Đầu Trụ Cột 3 & 4: Chẹn Beta Giao Cảm + Kháng Aldosterone (MRA)',
        timeframe: 'Tuần 2 - 4',
        description: 'Khởi đầu thuốc chẹn Beta được chứng minh giảm tử vong (Bisoprolol 1.25mg/ngày, Carvedilol 3.125mg x 2 lần/ngày hoặc Metoprolol Succinate). Phối hợp Spironolactone 12.5 - 25mg/ngày (nếu K+ < 5.0 mEq/L và eGFR > 30).',
        drugs: [
          {
            genericName: 'Bisoprolol / Carvedilol',
            tradeNames: ['Concor', 'Dilatrend'],
            route: 'PO',
            loadingDose: 'Bisoprolol 1.25 mg/ngày (hoặc Carvedilol 3.125 mg x 2 lần/ngày)',
            maintenanceDose: 'Tăng liều mỗi 2 tuần đến liều đích Bisoprolol 10 mg/ngày hoặc Carvedilol 25 mg x 2 lần/ngày (đích nhịp tim 55 - 60 l/p)',
            clinicalNotes: 'Chỉ khởi đầu khi bệnh nhân không còn tình trạng sung huyết ứ dịch cấp.',
          },
          {
            genericName: 'Spironolactone (MRA)',
            tradeNames: ['Aldactone'],
            route: 'PO',
            loadingDose: '12.5 - 25 mg uống 1 lần/ngày',
            maintenanceDose: 'Tăng lên 50 mg/ngày nếu K+ < 5.0 mEq/L',
            renalAdjustment: 'Chống chỉ định khi eGFR < 30 hoặc Kali máu > 5.0 mEq/L',
            clinicalNotes: 'Kiểm tra Kali và Creatinine sau 1 tuần, 4 tuần và mỗi 3 tháng.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_titration_icd_crt',
        order: 3,
        phase: 'recovery',
        title: '3. Tối Ưu Hóa Liều Đích & Đánh Giá Chỉ Định Máy Phá Rung ICD / CRT',
        timeframe: 'Sau 3 - 6 tháng điều trị nội khoa tối ưu',
        description: 'Đo lại Siêu âm tim LVEF sau 3 tháng GDMT liều đích. Nếu LVEF vẫn ≤ 35% kèm triệu chứng NYHA II-III: Chỉ định cấy máy phá rung tự động (ICD) dự phòng đột tử; Nếu có Block nhánh trái QRS ≥ 130-150ms: Chỉ định máy tái đồng bộ cơ tim (CRT-D / CRT-P).',
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Đang dùng thuốc Ức chế Men Chuyển (ACEi như Enalapril, Perindopril)',
        forbiddenDrugOrAction: 'Uống ngay ARNI (Sacubitril/Valsartan) mà không có thời gian nghỉ (Washout period)',
        dangerLevel: 'absolute',
        explanation: 'Ức chế đồng thời ACE và Neprilysin làm tăng nồng độ Bradykinin đột ngột gây Phù mạch (Angioedema) đe dọa ngạt thở.',
        recommendation: 'BẮT BUỘC ngưng ACEi đủ ít nhất 36 GIỜ trước khi bắt đầu liều ARNI đầu tiên.',
      },
      {
        conflictWithCondition: 'Tăng Kali máu (K+ > 5.0 - 5.5 mEq/L) hoặc Suy thận nặng (eGFR < 30)',
        forbiddenDrugOrAction: 'Tăng liều MRA (Spironolactone) hoặc phối hợp thêm thuốc giữ Kali',
        dangerLevel: 'absolute',
        explanation: 'Nguy cơ rối loạn nhịp thất ác tính và ngừng tim do tăng Kali máu nặng.',
        recommendation: 'Tạm ngưng MRA hoặc giảm liều 50%, kiểm tra lại điện giải đồ sau 3-5 ngày. Cân nhắc dùng thuốc gắn Kali (Patiromer / Sodium Zirconium Cyclosilicate).',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Liệu Pháp 4 Trụ Cột GDMT Khởi Đầu Đồng Thời (Simultaneous Low-Dose Quadruple Therapy)',
        approachType: 'standard-invasive',
        pros: [
          'Giảm 60 - 70% nguy cơ tử vong do mọi nguyên nhân và kéo dài tuổi thọ trung bình thêm 5 - 6 năm.',
          'Cải thiện nhanh phân suất tống máu LVEF và chất lượng sống.',
        ],
        cons: [
          'Uống nhiều loại thuốc cùng lúc, cần theo dõi định kỳ huyết áp, Kali và Creatinine máu.',
        ],
        estimatedCost: 'medium',
        suitableFor: 'Mọi bệnh nhân suy tim mạn HFrEF (LVEF ≤ 40%).',
      },
    ],
    cardioDetails: {
      ecgBiomarkers: 'Siêu âm tim định kỳ đánh giá LVEF (mục tiêu cải thiện > 40-50%). Xét nghiệm NT-proBNP theo dõi đáp ứng điều trị.',
      antiplateletAnticoagulation: 'Kháng đông DOAC (Apixaban / Rivaroxaban / Dabigatran) nếu có kèm Rung nhĩ.',
      gdmtPillars: 'Liệu pháp 4 trụ cột chuẩn: ARNI (Sacubitril/Valsartan) + Beta-Blocker (Bisoprolol/Carvedilol) + MRA (Spironolactone) + SGLT2i (Dapagliflozin/Empagliflozin).',
      cardiacScores: ['Phân độ chức năng NYHA I-IV', 'Phân loại suy tim theo giai đoạn AHA Stage A-D', 'Chỉ định ICD/CRT khi LVEF <= 35%'],
    },
    dischargeCriteria: [
      'Bệnh nhân dung nạp tốt cả 4 nhóm thuốc trụ cột GDMT.',
      'Huyết áp tâm thu ổn định ≥ 95 - 100 mmHg, không có triệu chứng chóng mặt tư thế.',
      'Kali máu < 5.0 mEq/L và eGFR ổn định.',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 4: CƠN TĂNG HUYẾT ÁP CẤP CỨU (HYPERTENSIVE EMERGENCY - ESC/AHA 2024) ═══
  {
    id: 'pddt-hypertensive-emergency-aha',
    title: 'Phác đồ Xử trí Cơn Tăng Huyết Áp Cấp Cứu (Hypertensive Emergency)',
    titleEn: 'Management of Hypertensive Emergencies & Acute Organ Damage Protocol',
    aliases: ['Tăng huyết áp cấp cứu', 'Hypertensive Crisis', 'Nicardipine IV', 'Cơn THA'],
    icd10: ['I10', 'I11', 'I15', 'I67.4'],
    specialty: 'cardio',
    triageLevel: 'emergency',
    guidelineSource: 'ESC / ESH Guidelines for the management of arterial hypertension (2024) & AHA/ACC',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Phân biệt rõ Cơn THA Cấp cứu (Hypertensive Emergency: Huyết áp tăng cao kèm tổn thương cơ quan đích cấp tính mới xuất hiện -> Bắt buộc hạ áp bằng thuốc truyền tĩnh mạch) vs Cơn THA Cấp bách (Hypertensive Urgency: Không có tổn thương tạng -> Hạ áp từ từ bằng thuốc uống).',
    redFlags: [
      'Tổn thương cơ quan đích cấp tính: Bóc tách động mạch chủ ngực cấp, Phù phổi cấp do tim, Hội chứng vành cấp, Đột quỵ thiếu máu não/Xuất huyết não, Bệnh não do tăng huyết áp, Suy thận cấp tiến triển.',
      'Huyết áp tâm thu ≥ 180 mmHg và/hoặc Huyết áp tâm trương ≥ 120 mmHg.',
      'Sản phụ có Tiền sản giật nặng hoặc Sản giật (HA ≥ 160/110 mmHg).',
    ],
    steps: [
      {
        stepId: 'step_1_triage_target_organ',
        order: 1,
        phase: 'triage',
        title: '1. Nhận Diện Tổn Thương Cơ Quan Đích Cấp Tính (0 - 15 phút)',
        timeframe: 'Phút 0 - 15',
        description: 'Đo huyết áp 2 tay bằng băng đo phù hợp. Thăm khám tìm tổn thương cơ quan đích: Soi đáy mắt (phù gai thị/xuất huyết), ECG và men tim, X-quang/Siêu âm phổi, Creatinine máu, CT sọ não (nếu có dấu hiệu thần kinh khu trú).',
        conditionIf: 'Có tổn thương cơ quan đích cấp tính (Cấp cứu)',
        conditionThen: 'Nhập khoa Hồi sức cấp cứu (ICU), hạ áp bằng thuốc truyền tĩnh mạch có thể chỉnh liều nhanh.',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_iv_nicardipine_target',
        order: 2,
        phase: 'first-line',
        title: '2. Hạ Áp Tĩnh Mạch Bằng Nicardipine / Labetalol Theo Đích Chuẩn',
        timeframe: 'Giờ thứ 1 đến Giờ thứ 24',
        description: 'Quy tắc hạ áp an toàn chung: Giảm không quá 20 - 25% huyết áp động mạch trung bình (MAP) trong giờ đầu tiên. Sau đó hạ dần xuống 160/100 mmHg trong 2 - 6 giờ tiếp theo, và về mức bình thường sau 24 - 48 giờ. (Ngoại lệ: Bóc tách ĐMC hạ nhanh HA tâm thu < 120 mmHg và nhịp tim < 60 l/p trong 20 phút).',
        drugs: [
          {
            genericName: 'Nicardipine',
            tradeNames: ['Loxen'],
            route: 'IV',
            loadingDose: 'Khởi đầu 5 mg/giờ truyền tĩnh mạch liên tục qua bơm tiêm điện',
            maintenanceDose: 'Tăng 2.5 mg/giờ mỗi 5 - 15 phút (tối đa 15 mg/giờ) cho đến khi đạt HA mục tiêu, sau đó giảm liều duy trì 3 mg/giờ',
            isHighAlert: true,
            clinicalNotes: 'Thuốc chẹn kênh Canxi DHP chọn lọc mạch máu não và vành, tác dụng hạ áp êm dịu và chính xác.',
          },
          {
            genericName: 'Labetalol',
            tradeNames: ['Trandate'],
            route: 'IV',
            loadingDose: '20 mg tiêm tĩnh mạch chậm trong 2 phút, lặp lại 20 - 80 mg mỗi 10 phút (hoặc truyền liên tục 0.5 - 2 mg/phút)',
            isHighAlert: true,
            clinicalNotes: 'Chẹn đồng thời Alpha-1 và Beta, thuốc lựa chọn hàng đầu cho Thai phụ (Tiền sản giật) và Bóc tách ĐMC.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_transition_oral_antihypertensive',
        order: 3,
        phase: 'recovery',
        title: '3. Chuyển Đổi Sang Thuốc Hạ Áp Phối Hợp Đường Uống (SPC)',
        timeframe: 'Sau 12 - 24 giờ ổn định huyết áp',
        description: 'Gối thuốc hạ áp đường uống viên phối hợp liều cố định (Single Pill Combination: ACEi/ARB + CCB như Amlodipine/Valsartan hoặc Perindopril/Amlodipine) trước khi giảm dần và ngưng hẳn thuốc truyền tĩnh mạch.',
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Đang trong đợt Tăng huyết áp cấp cứu',
        forbiddenDrugOrAction: 'Dùng Nifedipine viên nang nhỏ giọt dưới lưỡi',
        dangerLevel: 'absolute',
        explanation: 'Nifedipine ngậm dưới lưỡi gây tụt huyết áp đột ngột không thể kiểm soát, dẫn đến thiếu máu não diện rộng (đột quỵ thiếu máu cục bộ) và nhồi máu cơ tim.',
        recommendation: 'TUYỆT ĐỐI KHÔNG dùng Nifedipine ngậm dưới lưỡi. Chỉ dùng thuốc hạ áp truyền tĩnh mạch có thể điều chỉnh liều (Nicardipine IV).',
      },
      {
        conflictWithCondition: 'Đột quỵ thiếu máu não cấp (Ischemic Stroke) không dùng r-tPA',
        forbiddenDrugOrAction: 'Hạ huyết áp tích cực xuống mức bình thường trong 48 - 72h đầu',
        dangerLevel: 'absolute',
        explanation: 'Hạ áp làm mất áp lực tưới máu vùng tranh tối tranh sáng (Penumbra) của não, gây mở rộng vùng nhồi máu não không hồi phục.',
        recommendation: 'Chỉ hạ áp khi HA > 220/120 mmHg (hoặc > 185/110 mmHg nếu có chỉ định dùng thuốc tiêu sợi huyết r-tPA).',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Nhập Khoa ICU Điều Trị Thuốc Hạ Áp Truyền Tĩnh Mạch (Nicardipine IV Titration)',
        approachType: 'standard-invasive',
        pros: [
          'Kiểm soát hạ áp chính xác từng mmHg, bảo vệ an toàn các cơ quan đích (não, tim, thận).',
        ],
        cons: [
          'Cần theo dõi sát monitor huyết áp liên tục tại phòng ICU.',
        ],
        estimatedCost: 'medium',
        suitableFor: 'Mọi trường hợp Cơn Tăng huyết áp cấp cứu có tổn thương tạng.',
      },
    ],
    cardioDetails: {
      ecgBiomarkers: 'Đo ECG 12 chuyển đạo tìm phì đại thất trái Sokolow-Lyon, thiếu máu cơ tim. Soi đáy mắt đánh giá độ IV (Phù gai thị).',
      antiplateletAnticoagulation: 'Không dùng kháng huyết khối thường quy trừ khi có hội chứng vành cấp hoặc đột quỵ thiếu máu não kèm theo.',
      gdmtPillars: 'Chuyển sang viên phối hợp đôi SPC (ACEi/ARB + CCB DHP) uống hàng ngày duy trì HA < 130/80 mmHg.',
      cardiacScores: ['Đích hạ MAP 20-25% trong giờ đầu', 'Ngoại lệ: Bóc tách ĐMC hạ HA tâm thu < 120 mmHg trong 20 phút'],
    },
    dischargeCriteria: [
      'Huyết áp kiểm soát ổn định liên tục ≥ 24 giờ bằng thuốc uống (HA < 140/90 mmHg).',
      'Không còn dấu hiệu tổn thương cơ quan đích tiến triển.',
      'Đã tìm và loại trừ các nguyên nhân Tăng huyết áp thứ phát (Hẹp ĐM thận, U tủy thượng thận, Cường Aldosterone).',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 5: RUNG NHĨ CẤP & CHIẾN LƯỢC TOÀN DIỆN AF-CARE (ESC 2024) ═══
  {
    id: 'pddt-atrial-fibrillation-care-esc',
    title: 'Phác đồ Chẩn đoán & Điều trị Rung Nhĩ theo Khuyến cáo ESC 2024 (Lộ trình AF-CARE)',
    titleEn: '2024 ESC Guidelines for the Management of Atrial Fibrillation (AF-CARE Pathway)',
    aliases: ['Rung nhĩ', 'Atrial Fibrillation', 'AF-CARE', 'Kháng đông DOAC', 'CHA2DS2-VA', 'Triệt đốt PVI'],
    icd10: ['I48', 'I48.0', 'I48.1', 'I48.2', 'I48.9'],
    specialty: 'cardio',
    triageLevel: 'emergency',
    guidelineSource: 'ESC/EACTS Guidelines for the management of atrial fibrillation (2024)',
    evidenceLevel: 'Class I, Level A/B/C',
    year: 2024,
    summary: 'Phác đồ toàn diện chuẩn hóa theo Lộ trình AF-CARE 2024: [C] Comorbidity - Quản lý bệnh đồng mắc tim mạch & lối sống; [A] Avoid stroke - Dự phòng đột quỵ bằng Kháng đông DOAC theo thang điểm CHA2DS2-VA (bỏ yếu tố giới tính); [R] Reduce symptoms - Kiểm soát tần số tim (< 110 bpm) hoặc Kiểm soát nhịp (Chuyển nhịp & Triệt đốt PVI đầu tay); [E] Evaluate/Monitor - Đánh giá định kỳ.',
    redFlags: [
      'Huyết động không ổn định cấp tính: Tụt huyết áp nghiêm trọng (HA tâm thu < 90 mmHg), đau ngực kiểu mạch vành cấp tính, phù phổi cấp, hoặc sốc tim -> SỐC ĐIỆN ĐỒNG BỘ CẤP CỨU NGAY.',
      'Dấu hiệu thần kinh khu trú cấp tính: Nghi ngờ đột quỵ thiếu máu não hoặc xuất huyết nội sọ mới.',
      'Huyết khối nhĩ trái / tiểu nhĩ trái: Ghi nhận trên siêu âm tim qua thực quản (TEE) trước chuyển nhịp hoặc triệt đốt.',
      'Rung nhĩ đáp ứng thất quá nhanh (> 150 - 180 l/p) có hội chứng tiền kích thích WPW (Phức bộ QRS giãn rộng không đều).',
    ],
    steps: [
      {
        stepId: 'step_1_hemodynamic_emergency',
        order: 1,
        phase: 'triage',
        title: '1. Tiếp Nhận Khẩn & Sốc Điện Chuyển Nhịp Đồng Bộ Cấp Cứu (0 - 15 phút)',
        timeframe: 'Phút 0 - 15',
        description: 'Đo ECG 12 chuyển đạo xác định rung nhĩ (mất sóng P, thay bằng sóng f lăn tăn 300-500 ck/p, khoảng R-R không đều). Đánh giá huyết động ngay: NẾU có tụt HA (HA tâm thu < 90 mmHg), đau thắt ngực cấp, phù phổi cấp hoặc sốc tim -> Tiêm an thần ngắn hạn và SỐC ĐIỆN ĐỒNG BỘ NGAY (100 - 200 Joules Biphasic). Khởi động kháng đông OAC / Heparin càng sớm càng tốt quanh thời điểm sốc điện.',
        conditionIf: 'Huyết động bất ổn (Sốc, Tụt HA, Phù phổi cấp)',
        conditionThen: 'Sốc điện đồng bộ cấp cứu ngay lập tức + Kháng đông khẩn cấp.',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_care_c_comorbidities',
        order: 2,
        phase: 'first-line',
        title: '2. [C] Quản Lý Toàn Diện Bệnh Đồng Mắc & Lối Sống (Comorbidity Management)',
        timeframe: 'Khởi động ngay',
        description: 'Hạ huyết áp tối ưu (đích 120-129/70-79 mmHg, ưu tiên ACEi/ARB); Điều trị suy tim tối ưu theo GDMT (đặc biệt chỉ định SGLT2i bất kể LVEF); Kiểm soát đường huyết chặt chẽ (Metformin/SGLT2i); Khuyến khích giảm cân tích cực (mục tiêu giảm ≥ 10% trọng lượng cơ thể nếu béo phì); Giảm tiêu thụ rượu xuống ≤ 3 đơn vị tiêu chuẩn (30g cồn)/tuần.',
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_care_a_avoid_stroke',
        order: 3,
        phase: 'first-line',
        title: '3. [A] Tránh Đột Quỵ Bằng Kháng Đông DOAC Theo Thang Điểm CHA2DS2-VA',
        timeframe: 'Đánh giá ngay',
        description: 'Tính điểm CHA2DS2-VA (C: Suy tim [1], H: Tăng HA [1], A2: Tuổi ≥ 75 [2], D: ĐTĐ [1], S2: Tiền sử Đột quỵ/TIA [2], V: Bệnh mạch máu [1], A: Tuổi 65-74 [1]). Chỉ định OAC khi CHA2DS2-VA ≥ 2 (Class I) hoặc = 1 (Class IIa). Bệnh cơ tim phì đại (HCM) hoặc Amyloidosis tim: Bắt buộc dùng OAC bất kể điểm số (Class I). Ưu tiên DOAC (Apixaban, Dabigatran, Rivaroxaban, Edoxaban) hơn VKA (Warfarin), trừ khi có van cơ học hoặc hẹp van hai lá vừa-nặng.',
        drugs: [
          {
            genericName: 'Apixaban',
            tradeNames: ['Eliquis'],
            route: 'PO',
            maintenanceDose: '5 mg uống 2 lần/ngày (Giảm xuống 2.5 mg x 2 lần/ngày nếu có ít nhất 2 trong 3 tiêu chí: Tuổi ≥ 80, Cân nặng ≤ 60kg, Creatinine ≥ 1.5 mg/dL [133 µmol/L])',
            renalAdjustment: 'eGFR < 15 hoặc lọc máu: Thận trọng 2.5 mg x 2 lần/ngày',
            hepaticAdjustment: 'Child-Pugh A: Không đổi; Child-Pugh B: Thận trọng; Child-Pugh C: Chống chỉ định',
            clinicalNotes: 'Nguy cơ xuất huyết tiêu hóa thấp nhất trong nhóm DOAC. Tránh tự ý giảm liều nếu không đủ tiêu chí.',
          },
          {
            genericName: 'Dabigatran',
            tradeNames: ['Pradaxa'],
            route: 'PO',
            maintenanceDose: '150 mg uống 2 lần/ngày (Cân nhắc giảm 110 mg x 2 lần/ngày nếu nguy cơ chảy máu cao hoặc CrCl 30-50 mL/phút)',
            renalAdjustment: 'CrCl < 30 mL/phút: Chống chỉ định tuyệt đối (thuốc thải 80% qua thận)',
            clinicalNotes: 'Tác dụng phụ: Khó tiêu, viêm dạ dày. Có thuốc đảo ngược đặc hiệu: Idarucizumab 5g IV.',
          },
          {
            genericName: 'Rivaroxaban',
            tradeNames: ['Xarelto'],
            route: 'PO',
            maintenanceDose: '20 mg uống 1 lần/ngày (BẮT BUỘC uống cùng bữa ăn lớn nhất để hấp thu tối đa; Giảm 15 mg/ngày nếu eGFR 15-49 mL/phút)',
            renalAdjustment: 'eGFR < 15 mL/phút: Chống chỉ định',
            hepaticAdjustment: 'Child-Pugh B và C: Chống chỉ định',
            clinicalNotes: 'Dùng 1 lần/ngày tiện lợi. Có thuốc đối kháng: Andexanet alfa.',
          },
          {
            genericName: 'Edoxaban',
            tradeNames: ['Lixiana'],
            route: 'PO',
            maintenanceDose: '60 mg uống 1 lần/ngày (Giảm 30 mg/ngày nếu CrCl 15-50 mL/phút hoặc Cân nặng ≤ 60kg hoặc dùng kèm thuốc ức chế P-gp mạnh)',
            renalAdjustment: 'CrCl > 95 mL/phút: Tránh dùng do tăng thải trừ làm giảm hiệu quả; CrCl < 15: Chống chỉ định',
            clinicalNotes: 'Ít tương tác thuốc nhất qua CYP3A4.',
          },
          {
            genericName: 'Warfarin',
            tradeNames: ['Coumadin', 'Sintrom'],
            route: 'PO',
            maintenanceDose: 'Liều cá nhân hóa chỉnh theo INR mục tiêu 2.0 - 3.0 (duy trì TTR > 70%)',
            clinicalNotes: 'Bắt buộc dùng cho Van tim nhân tạo cơ học hoặc Hẹp van 2 lá vừa-nặng. Thuốc đảo ngược: Phức hợp Prothrombin 4 yếu tố (4F-PCC) + Vitamin K.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_care_r_rate_rhythm',
        order: 4,
        phase: 'first-line',
        title: '4. [R] Giảm Triệu Chứng Bằng Kiểm Soát Tần Số Tim (Rate) Hoặc Chuyển Nhịp (Rhythm)',
        timeframe: 'Giờ 1 - 24',
        description: 'Kiểm soát tần số tim mục tiêu ban đầu < 110 bpm lúc nghỉ (Lenient rate control): Nếu LVEF ≤ 40%: Dùng Chẹn Beta (Bisoprolol/Carvedilol) và/hoặc Digoxin (CẤM Non-DHP CCB); Nếu LVEF > 40%: Chẹn Beta, Diltiazem, Verapamil hoặc Digoxin. Nếu Rung nhĩ mới < 48h & ổn định: Xem xét chờ tự chuyển nhịp ("Wait-and-see"). Nếu Rung nhĩ > 24-48h: BẮT BUỘC siêu âm TEE loại trừ huyết khối hoặc dùng DOAC đủ ≥ 3 tuần trước chuyển nhịp (tiếp tục DOAC ≥ 4 tuần sau chuyển nhịp).',
        drugs: [
          {
            genericName: 'Bisoprolol / Metoprolol succinate',
            route: 'PO',
            loadingDose: 'Bisoprolol 1.25 - 2.5 mg/ngày (hoặc Metoprolol 50 mg/ngày)',
            maintenanceDose: 'Chỉnh liều theo tần số tim đích < 110 bpm (tối đa Bisoprolol 10-20 mg/ngày)',
            clinicalNotes: 'Lựa chọn hàng đầu để kiểm soát tần số tim.',
          },
          {
            genericName: 'Diltiazem / Verapamil',
            route: 'PO',
            loadingDose: 'Diltiazem IV 0.25 mg/kg trong 2 phút (nếu cấp cứu)',
            maintenanceDose: 'Diltiazem ER 120 - 360 mg/ngày hoặc Verapamil ER 120 - 480 mg/ngày',
            clinicalNotes: 'CHỐNG CHỈ ĐỊNH TUYỆT ĐỐI khi LVEF ≤ 40% (suy tim giảm) vì gây ức chế co bóp cơ tim làm bùng phát sốc tim.',
          },
          {
            genericName: 'Digoxin',
            route: 'PO',
            loadingDose: 'IV 0.5 mg bolus (tổng 0.75 - 1.5 mg/24h chia liều)',
            maintenanceDose: '0.0625 - 0.25 mg/ngày (giảm liều khi suy thận eGFR < 30)',
            renalAdjustment: 'Bắt buộc giám sát nồng độ đáy huyết thanh đích < 1.2 ng/mL để tránh tăng tử vong',
            clinicalNotes: 'Dùng khi suy tim HFrEF hoặc phối hợp Chẹn Beta khi đơn trị liệu không đạt đích.',
          },
          {
            genericName: 'Amiodarone',
            tradeNames: ['Cordarone'],
            route: 'IV',
            loadingDose: '300 mg pha 250mL Glucose 5% truyền trong 30 - 60 phút, tiếp theo truyền duy trì 900 - 1200 mg/24h',
            maintenanceDose: 'Uống duy trì 200 mg/ngày',
            clinicalNotes: 'Thuốc chuyển nhịp duy nhất an toàn ở bệnh nhân có bệnh tim cấu trúc nặng, bệnh mạch vành hoặc suy tim HFrEF.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_5_care_e_ablation_refractory',
        order: 5,
        phase: 'refractory',
        title: '5. [E] Triệt Đốt Qua Ống Thông (PVI Ablation) & Đánh Giá Định Kỳ',
        timeframe: 'Lâu dài',
        description: 'Triệt đốt cô lập tĩnh mạch phổi (PVI) là lựa chọn hàng đầu cho Rung nhĩ kịch phát có triệu chứng dựa trên sự đồng thuận của BN (Class I, Level A); Triệt đốt cho Rung nhĩ dai dẳng kháng thuốc AAD (Class I, Level A); Triệt đốt sớm cho BN suy tim HFrEF nghi ngờ bệnh cơ tim do nhịp nhanh (Class I, Level B). Duy trì chống đông liên tục không ngắt quãng (uninterrupted OAC) quanh thủ thuật và ít nhất 2 tháng sau triệt đốt.',
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Rung nhĩ có hội chứng tiền kích thích (Hội chứng WPW: Wolff-Parkinson-White)',
        forbiddenDrugOrAction: 'Dùng Digoxin, Verapamil, Diltiazem hoặc Chẹn Beta đường tĩnh mạch',
        dangerLevel: 'absolute',
        explanation: 'Thuốc ức chế nút nhĩ thất làm tăng dẫn truyền xung động cực nhanh qua cầu Kent (đường phụ), kích hoạt Rung thất (VF) gây ngừng tim đột tử tức thì.',
        recommendation: 'Chỉ định SỐC ĐIỆN ĐỒNG BỘ CẤP CỨU hoặc dùng Procainamide, Ibutilide.',
      },
      {
        conflictWithCondition: 'Suy tim phân suất tống máu giảm (LVEF ≤ 40%)',
        forbiddenDrugOrAction: 'Chẹn kênh Canxi nhóm Non-DHP (Verapamil, Diltiazem)',
        dangerLevel: 'absolute',
        explanation: 'Tác dụng ức chế co bóp âm tính trực tiếp làm tụt huyết áp nặng và bùng phát phù phổi cấp / sốc tim.',
        recommendation: 'Chỉ dùng thuốc Chẹn Beta chọn lọc Beta-1 (Bisoprolol, Carvedilol, Metoprolol) và/hoặc Digoxin.',
      },
      {
        conflictWithCondition: 'Bệnh mạch vành / Sẹo nhồi máu cơ tim cũ / Bệnh tim cấu trúc nặng',
        forbiddenDrugOrAction: 'Thuốc chống loạn nhịp nhóm Class IC (Flecainide, Propafenone)',
        dangerLevel: 'absolute',
        explanation: 'Nguy cơ gây loạn nhịp thất ác tính đe dọa tính mạng (Proarrhythmia) và tăng tử vong theo thử nghiệm CAST.',
        recommendation: 'Chỉ dùng Amiodarone để chuyển nhịp và duy trì nhịp xoang.',
      },
      {
        conflictWithCondition: 'Bệnh nhân có chỉ định dùng DOAC nhưng không thỏa tiêu chí giảm liều',
        forbiddenDrugOrAction: 'Tự ý giảm liều DOAC (Inappropriate underdosing, ví dụ dùng Apixaban 2.5mg x 2 mà không đủ 2/3 criteria)',
        dangerLevel: 'absolute',
        explanation: 'Giảm liều sai quy chuẩn làm tăng vọt nguy cơ Đột quỵ thiếu máu não do huyết tắc mà hoàn toàn không làm giảm nguy cơ chảy máu.',
        recommendation: 'BẮT BUỘC dùng liều chuẩn (Apixaban 5mg x 2, Rivaroxaban 20mg x 1, Dabigatran 150mg x 2, Edoxaban 60mg x 1) trừ khi thỏa đủ tiêu chí giảm liều chính thức.',
      },
      {
        conflictWithCondition: 'Bệnh động mạch vành ổn định trên 12 tháng kèm Rung nhĩ',
        forbiddenDrugOrAction: 'Phối hợp kéo dài thuốc kháng tiểu cầu (Aspirin/Clopidogrel) cùng với Kháng đông OAC',
        dangerLevel: 'relative',
        explanation: 'Tăng gấp đôi nguy cơ xuất huyết tiêu hóa và xuất huyết nội sọ mà không tăng thêm lợi ích bảo vệ mạch vành.',
        recommendation: 'Ngừng hoàn toàn thuốc kháng tiểu cầu sau 12 tháng ổn định và duy trì ĐƠN TRỊ LIỆU bằng DOAC.',
      },
      {
        conflictWithCondition: 'Đột quỵ không rõ nguồn gốc (ESUS) chưa ghi nhận Rung nhĩ trên ECG',
        forbiddenDrugOrAction: 'Khởi đầu thuốc chống đông đường uống OAC theo kinh nghiệm',
        dangerLevel: 'relative',
        explanation: 'Không mang lại hiệu quả giảm tái phát đột quỵ nhưng làm tăng vọt nguy cơ chảy máu lớn (Class III, Level A).',
        recommendation: 'Chỉ dùng OAC khi đã ghi nhận rung nhĩ lâm sàng trên ECG hoặc thiết bị Holter/ILR.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Chiến Lược Kiểm Soát Nhịp Tích Cực Bằng Triệt Đốt Qua Ống Thông (PVI Catheter Ablation)',
        approachType: 'standard-invasive',
        pros: [
          'Khôi phục và duy trì nhịp xoang sinh lý, giải quyết triệt để triệu chứng mệt mỏi, khó thở và đánh trống ngực.',
          'Cải thiện phân suất tống máu LVEF và giảm tỷ lệ tái nhập viện ở bệnh nhân suy tim HFrEF.',
          'Ngăn ngừa quá trình xơ hóa và tái cấu trúc tâm nhĩ tiến triển.',
        ],
        cons: [
          'Thủ thuật xâm lấn, chi phí cao, có tỷ lệ tai biến nhỏ (tràn dịch màng tim, tổn thương mạch máu đùi).',
          'Vẫn cần duy trì chống đông DOAC ít nhất 2 tháng sau thủ thuật (hoặc lâu dài nếu CHA2DS2-VA cao).',
        ],
        estimatedCost: 'high',
        suitableFor: 'Rung nhĩ kịch phát có triệu chứng (khuyến nghị đầu tay Class I, Level A), BN trẻ tuổi, hoặc BN suy tim nghi ngờ bệnh cơ tim do nhịp nhanh.',
      },
      {
        optionName: 'Phương án 2: Chiến Lược Kiểm Soát Tần Số Tim Đơn Thuần (Lenient Rate Control) + Kháng Đông DOAC',
        approachType: 'conservative',
        pros: [
          'Tiếp cận đơn giản, an toàn, chi phí thấp, không cần can thiệp xâm lấn.',
          'Mục tiêu nhịp tim lúc nghỉ < 110 bpm đã được chứng minh không thua kém kiểm soát chặt chẽ về kết cục tim mạch gộp.',
        ],
        cons: [
          'Tim vẫn duy trì nhịp rung nhĩ vĩnh viễn, tâm nhĩ tiếp tục giãn rộng theo thời gian.',
          'Triệu chứng mệt mỏi khi gắng sức có thể vẫn còn tồn tại.',
        ],
        estimatedCost: 'low',
        suitableFor: 'Bệnh nhân rung nhĩ vĩnh viễn, người cao tuổi (≥ 70 tuổi), ít triệu chứng hoặc có nhiều bệnh lý nền nặng.',
      },
    ],
    cardioDetails: {
      ecgBiomarkers: 'ECG 12 chuyển đạo: Mất sóng P, thay bằng sóng f lăn tăn (300-500 ck/p), khoảng RR không đều. Siêu âm TEE loại trừ huyết khối tiểu nhĩ.',
      antiplateletAnticoagulation: 'DOAC (Apixaban, Dabigatran, Rivaroxaban, Edoxaban) là lựa chọn ưu tiên hàng đầu theo thang điểm CHA2DS2-VA.',
      gdmtPillars: 'Kiểm soát toàn diện bệnh đồng mắc: Hạ áp (ACEi/ARB), SGLT2i cho suy tim/ĐTĐ, Giảm cân >= 10%, Hạn chế rượu <= 3 đơn vị/tuần.',
      cardiacScores: [
        'Thang điểm CHA2DS2-VA (Kháng đông nếu >= 2 điểm ở nam/nữ, cân nhắc nếu = 1 điểm)',
        'Thang điểm triệu chứng EHRA sửa đổi (I: Không triệu chứng -> IV: Tàn phế)',
        'Thang điểm nguy cơ chảy máu: Đánh giá yếu tố thay đổi được (Không dùng HAS-BLED để từ chối OAC)',
      ],
    },
    dischargeCriteria: [
      'Huyết động hoàn toàn ổn định, không còn tụt HA, đau ngực hay suy tim cấp mất bù.',
      'Tần số thất lúc nghỉ kiểm soát đạt mục tiêu < 110 bpm và dung nạp tốt với thuốc.',
      'Đã bắt đầu kháng đông DOAC đúng liều lượng chuẩn xác và được tư vấn kỹ về tuân thủ điều trị.',
      'Đã lên lịch tái khám tim mạch và xét nghiệm chức năng thận (eGFR), điện giải đồ định kỳ mỗi 3 - 6 tháng.',
    ],
    updatedAt: '2026-08-22',
  },
];
