/**
 * CliniPortal 2.0 — Kho Phác Đồ Hồi Sức - Cấp Cứu
 * Path: src/content/protocols/registry/emergency-protocols.ts
 */

import { ClinicalProtocol } from '../protocol-types';

export const EMERGENCY_PROTOCOLS: ClinicalProtocol[] = [
  {
    id: 'pddt-sepsis-ssc-2021',
    title: 'Xử trí Nhiễm khuẩn huyết & Sốc Nhiễm khuẩn (Hour-1 Bundle — SSC 2021)',
    titleEn: 'Surviving Sepsis Campaign: Hour-1 Bundle Protocol for Sepsis & Septic Shock',
    aliases: ['Sốc nhiễm khuẩn', 'Sepsis', 'Hour-1 Bundle', 'Nhiễm trùng huyết'],
    icd10: ['R57.2', 'A41.9', 'A41'],
    specialty: 'emergency',
    triageLevel: 'emergency',
    guidelineSource: 'Surviving Sepsis Campaign (SSC 2021 / 2024 Updates) — Hội Hồi sức Cấp cứu Quốc tế & Bộ Y Tế',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Phác đồ 5 can thiệp tối khẩn bắt buộc hoàn thành trong 60 phút đầu tiên khi nhận diện Nhiễm khuẩn huyết / Sốc nhiễm khuẩn: Đo Lactate, cấy máu, kháng sinh phổ rộng, bù dịch tinh thể 30 ml/kg và vận mạch Noradrenaline.',
    redFlags: [
      'qSOFA ≥ 2 điểm: Nhịp thở ≥ 22 lần/phút, Rối loạn tri giác (GCS < 15), Huyết áp tâm thu ≤ 100 mmHg.',
      'Huyết động tụt sâu: MAP < 65 mmHg mặc dù đã bù dịch ban đầu.',
      'Lactate máu động mạch ≥ 4 mmol/L (dấu hiệu giảm tưới máu mô nặng).',
      'Thiểu niệu: Lượng nước tiểu < 0.5 ml/kg/giờ kéo dài trên 2 giờ.',
    ],
    steps: [
      {
        stepId: 'step_1_lactate_blood_culture',
        order: 1,
        phase: 'triage',
        title: '1. Đo Lactate Máu & Cấy Máu Trước Kháng Sinh (0 - 15 phút)',
        timeframe: 'Phút 0 - 15',
        description: 'Lấy máu xét nghiệm Lactate ngay lập tức. Cấy ít nhất 2 bộ máu (1 chai hiếu khí và 1 chai kỵ khí) từ 2 vị trí tĩnh mạch ngoại vi khác nhau. Tuyệt đối không trì hoãn kháng sinh quá 45 phút nếu cấy máu gặp khó khăn.',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_broad_abx',
        order: 2,
        phase: 'first-line',
        title: '2. Kháng Sinh Phổ Rộng Đường Tĩnh Mạch Liều Nạp (Trong 60 phút)',
        timeframe: 'Trong 60 phút đầu',
        description: 'Dùng ngay kháng sinh phổ rộng đường tĩnh mạch liều tấn công tối đa, bao phủ cả vi khuẩn Gram âm đa kháng và Gram dương (MRSA).',
        drugs: [
          {
            genericName: 'Piperacillin / Tazobactam',
            tradeNames: ['Tazocin', 'Zosyn'],
            route: 'IV',
            loadingDose: '4.5g IV truyền ngắt quãng trong 30 phút (sau đó duy trì truyền kéo dài 3 - 4 giờ)',
            maintenanceDose: '4.5g mỗi 6 - 8 giờ',
            renalAdjustment: 'eGFR < 50: 3.375g q6h; eGFR < 20: 2.25g q6h',
            clinicalNotes: 'Phổ rộng trực khuẩn Gram âm, Pseudomonas và kỵ khí.',
          },
          {
            genericName: 'Meropenem',
            tradeNames: ['Meronem'],
            route: 'IV',
            loadingDose: '1g - 2g IV tiêm tĩnh mạch chậm trong 30 phút',
            maintenanceDose: '1g mỗi 8 giờ (truyền kéo dài 3 giờ)',
            renalAdjustment: 'eGFR 26-50: 1g q12h; eGFR 10-25: 500mg q12h; eGFR < 10: 500mg q24h',
            clinicalNotes: 'Lựa chọn hàng đầu khi nghi ngờ vi khuẩn sinh ESBL hoặc sốc nhiễm khuẩn nặng.',
          },
          {
            genericName: 'Vancomycin',
            route: 'IV',
            loadingDose: '25 - 30 mg/kg (tối đa 2g) truyền tĩnh mạch chậm trong 1 - 2 giờ',
            maintenanceDose: '15 - 20 mg/kg mỗi 8 - 12 giờ',
            renalAdjustment: 'Chỉnh liều chặt chẽ theo nồng độ đáy Trough level (đích 15 - 20 mcg/mL) hoặc AUC/MIC.',
            isHighAlert: true,
            clinicalNotes: 'Bao phủ MRSA. Bắt buộc truyền chậm để tránh Hội chứng Người đỏ (Red Man Syndrome).',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_fluid_resus',
        order: 3,
        phase: 'first-line',
        title: '3. Bù Dịch Tinh Thể Nhanh (30 mL/kg trong 3 Giờ Đầu)',
        timeframe: 'Giờ 1 - 3',
        description: 'Truyền dịch tinh thể đẳng trương (ưu tiên Ringer Lactate / Acetate hơn NaCl 0.9%) với liều chuẩn 30 mL/kg cân nặng thực tế khi có tụt HA (MAP < 65 mmHg) hoặc Lactate ≥ 4 mmol/L.',
        drugs: [
          {
            genericName: 'Ringer Lactate / Ringer Acetate / Plasmalyte',
            route: 'IV',
            maintenanceDose: '30 mL/kg xả nhanh trong 3 giờ đầu',
            clinicalNotes: 'Dung dịch cân bằng (Balanced Crystalloids) giúp giảm tỷ lệ tử vong và suy thận cấp so với NaCl 0.9%.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_vasopressor',
        order: 4,
        phase: 'refractory',
        title: '4. Thuốc Vận Mạch Noradrenaline Duy trì MAP ≥ 65 mmHg',
        timeframe: 'Ngay khi bù dịch chưa đạt đích',
        description: 'Bắt đầu truyền Noradrenaline qua catheter tĩnh mạch trung tâm liều khởi đầu 0.05 - 0.1 mcg/kg/phút, chỉnh liều mỗi 5-10 phút để duy trì đích MAP ≥ 65 mmHg. Nếu liều Noradrenaline > 0.25 mcg/kg/phút, phối hợp thêm Vasopressin 0.03 đơn vị/phút hoặc Adrenaline.',
        drugs: [
          {
            genericName: 'Noradrenaline (Norepinephrine)',
            tradeNames: ['Levophed'],
            route: 'IV',
            loadingDose: 'Khởi đầu 0.05 - 0.1 mcg/kg/phút',
            maintenanceDose: '0.1 - 1.0 mcg/kg/phút (titrate theo MAP ≥ 65)',
            isHighAlert: true,
            clinicalNotes: 'Vận mạch đầu tay trong sốc nhiễm khuẩn. Tránh thoát mạch gây hoại tử mô.',
          },
          {
            genericName: 'Hydrocortisone',
            route: 'IV',
            maintenanceDose: '200 mg/ngày (chia 50mg mỗi 6 giờ IV hoặc truyền liên tục)',
            clinicalNotes: 'Chỉ định khi sốc kháng trị cần Noradrenaline liều cao kéo dài.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_5_target_evaluation',
        order: 5,
        phase: 'recovery',
        title: '5. Đánh Giá Hồi Sức Đạt Đích & Đo lại Lactate',
        timeframe: 'Giờ 2 - 4',
        description: 'Đo lại Lactate máu sau 2 - 4 giờ để đánh giá độ thanh thải (đích giảm > 20% mỗi 2h). Đánh giá tưới máu ngoại vi (CRT), độ bão hòa oxy máu tĩnh mạch trung tâm (ScvO2 ≥ 70%) và lượng nước tiểu ≥ 0.5 mL/kg/h.',
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Bệnh tim thiếu máu cục bộ / Nhồi máu cơ tim',
        forbiddenDrugOrAction: 'Dopamin liều cao làm thuốc vận mạch đầu tay',
        dangerLevel: 'absolute',
        explanation: 'Dopamin gây loạn nhịp tim nhanh và tăng tiêu thụ oxy cơ tim nghiêm trọng so với Noradrenaline.',
        recommendation: 'Chỉ dùng Noradrenaline làm vận mạch đầu tay. Phối hợp Dobutamin nếu có suy chức năng co bóp thất trái.',
      },
      {
        conflictWithCondition: 'Suy tim cấp ứ huyết / Bệnh thận mạn giai đoạn cuối (N18.5)',
        forbiddenDrugOrAction: 'Xả mù quáng dịch truyền không kiểm soát huyết động',
        dangerLevel: 'relative',
        explanation: 'Dễ gây phù phổi cấp và suy hô hấp mất bù do ứ dịch thể tích.',
        recommendation: 'Đánh giá đáp ứng bù dịch động qua nghiệm pháp nâng chân thụ động (PLR), biến thiên thể tích nhát bóp (SVV) hoặc siêu âm IVC.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Hồi sức Tích cực Đầy đủ tại Khoa ICU (Invasive Monitoring & Organ Support)',
        approachType: 'standard-invasive',
        pros: [
          'Tối ưu hóa khả năng sống còn nhờ kiểm soát huyết động xâm lấn (CVP, HA động mạch) và lọc máu liên tục (CRRT).',
          'Theo dõi khí máu, lactate và điều chỉnh kháng sinh theo TDM thời gian thực.',
        ],
        cons: [
          'Chi phí điều trị cao, can thiệp thủ thuật xâm lấn nhiều.',
          'Nguy cơ nhiễm trùng bệnh viện đa kháng liên quan đến thở máy và catheter.',
        ],
        estimatedCost: 'high',
        suitableFor: 'Mọi bệnh nhân sốc nhiễm khuẩn có tụt HA kháng dịch truyền hoặc tổn thương đa tạng.',
      },
      {
        optionName: 'Phương án 2: Điều trị Kháng sinh Tĩnh mạch & Hồi sức Không Xâm lấn tại Khoa Thường',
        approachType: 'conservative',
        pros: [
          'Giảm gánh nặng chi phí, hạn chế tối đa các can thiệp xâm lấn không cần thiết.',
        ],
        cons: [
          'Không thể theo dõi huyết động động học liên tục, nguy cơ bỏ lỡ thời điểm suy sụp tuần hoàn.',
        ],
        estimatedCost: 'low',
        suitableFor: 'Nhiễm khuẩn huyết mức độ nhẹ, huyết động ổn định, Lactate < 2 mmol/L, đáp ứng tốt sau bù dịch ban đầu.',
      },
    ],
    emergencyDetails: {
      hemodynamicTargets: [
        'Huyết áp động mạch trung bình (MAP) >= 65 mmHg',
        'Lactate máu động mạch < 2 mmol/L (đào thải > 20% mỗi 2h)',
        'Độ bão hòa oxy máu tĩnh mạch trung tâm ScvO2 >= 70%',
        'Lượng nước tiểu >= 0.5 mL/kg/giờ',
      ],
      inotropesVasopressors: [
        'Noradrenaline: Vận mạch đầu tay (0.05 - 1.0 mcg/kg/phút)',
        'Vasopressin: Phối hợp liều cố định 0.03 UI/phút nếu liều Noradrenaline > 0.25 mcg/kg/phút',
        'Dobutamin: Phối hợp nếu suy giảm sức co bóp cơ tim hoặc ScvO2 < 70%',
      ],
      resuscitationFluid: 'Dung dịch tinh thể cân bằng (Ringer Lactate / Acetate) liều nạp 30 mL/kg trong 3 giờ đầu',
      emergencyScores: ['qSOFA >= 2', 'SOFA score', 'APACHE II', 'GCS'],
    },
    dischargeCriteria: [
      'Huyết động ổn định hoàn toàn mà không cần thuốc vận mạch (MAP ≥ 65 mmHg liên tục > 24h).',
      'Lactate máu về mức bình thường (< 2 mmol/L).',
      'Kiểm soát triệt để ổ nhiễm khuẩn nguồn (Source control hoàn tất).',
      'Bạch cầu máu và CRP/Procalcitonin có xu hướng giảm rõ rệt.',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 2: CẤP CỨU PHẢN VỆ (THÔNG TƯ 51/2017/TT-BYT) ═══
  {
    id: 'pddt-anaphylaxis-tt51-byt',
    title: 'Phác đồ Cấp cứu & Xử trí Phản vệ (Thông tư 51/2017/TT-BYT)',
    titleEn: 'Management of Anaphylaxis Protocol (Circular 51/2017/TT-BYT Vietnam MOH)',
    aliases: ['Sốc phản vệ', 'Phản vệ cấp', 'Anaphylaxis', 'Thông tư 51'],
    icd10: ['T78.2', 'T78.0', 'T88.6'],
    specialty: 'emergency',
    triageLevel: 'emergency',
    guidelineSource: 'Thông tư số 51/2017/TT-BYT Bộ Y Tế Việt Nam',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Quy tắc vàng: Adrenaline là thuốc thiết yếu duy nhất cứu sống người bệnh phản vệ từ Độ II trở lên. Tiêm bắp ngay vào mặt trước ngoài đùi, không chần chừ, lặp lại mỗi 3 - 5 phút nếu chưa cải thiện.',
    redFlags: [
      'Khó thở thanh quản: Khàn tiếng, thở rít thanh quản (Stridor), nghẹn họng.',
      'Suy hô hấp cấp: Co kéo cơ hô hấp, SpO2 < 90%, thở nhanh nông hoặc ngắt quãng.',
      'Trụy mạch / Tụt huyết áp: Mạch nhanh nhỏ hoặc không bắt được, HA tụt kẹt, ngất xỉu, vã mồ hôi, da tái lạnh.',
      'Rối loạn tri giác: Lú lẫn, co giật, hôn mê, đại tiểu tiện không tự chủ.',
    ],
    steps: [
      {
        stepId: 'step_1_stop_antigen_adrenaline',
        order: 1,
        phase: 'triage',
        title: '1. Ngừng Tiếp Xúc Dị Nguyên & TIÊM BẮP ADRENALINE NGAY (Giây thứ 0)',
        timeframe: 'Ngay lập tức',
        description: 'Ngừng ngay đường truyền thuốc/dịch hoặc dị nguyên nghi ngờ. Đặt bệnh nhân nằm tại chỗ, đầu thấp, chân cao (nếu khó thở thì ngồi nửa nằm). Tiêm bắp Adrenaline 1mg/1mL ngay vào mặt trước ngoài đùi: Người lớn 1/2 ống (0.5mg), Trẻ em > 30kg: 1/2 ống, Trẻ 10-30kg: 1/3 ống (0.3mg), Trẻ < 10kg: 1/4 - 1/5 ống (0.1 - 0.2mg).',
        drugs: [
          {
            genericName: 'Adrenaline (Epinephrine) 1mg/1mL',
            route: 'IM',
            loadingDose: '0.5 mg (1/2 ống) tiêm bắp sâu mặt trước ngoài đùi',
            maintenanceDose: 'Lặp lại mỗi 3 - 5 phút/lần nếu HA chưa lên hoặc khó thở còn tiếp diễn (tối đa 3 liều tiêm bắp trước khi chuyển truyền TM)',
            isHighAlert: true,
            clinicalNotes: 'TUYỆT ĐỐI KHÔNG tiêm dưới da. Mặt trước ngoài đùi cho nồng độ đỉnh trong máu nhanh gấp 5 lần tiêm bắp cánh tay.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_airway_oxygen',
        order: 2,
        phase: 'first-line',
        title: '2. Kiểm Soát Đường Thở & Thở Oxy Liều Cao',
        timeframe: 'Phút 1 - 5',
        description: 'Thở oxy qua mặt nạ có túi dự trữ 6 - 10 L/phút để duy trì SpO2 ≥ 95%. Nếu có phù nề thanh quản nặng (thở rít dữ dội): Chuẩn bị đặt nội khí quản khẩn hoặc mở khí quản cấp cứu.',
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_iv_adrenaline_fluid',
        order: 3,
        phase: 'refractory',
        title: '3. Thiết Lập Đường Truyền Adrenaline Tĩnh Mạch & Bù Dịch Nhanh',
        timeframe: 'Sau 2 - 3 liều tiêm bắp không đáp ứng',
        description: 'Thiết lập đường truyền tĩnh mạch Adrenaline liên tục qua bơm tiêm điện (khởi đầu 0.1 mcg/kg/phút, chỉnh liều theo MAP ≥ 65 mmHg). Song song xả nhanh dịch tinh thể (NaCl 0.9% hoặc Ringer Lactate): Người lớn 1 - 2 Lít trong 10-20 phút đầu, Trẻ em 10 - 20 mL/kg.',
        drugs: [
          {
            genericName: 'Adrenaline truyền tĩnh mạch liên tục',
            route: 'IV',
            loadingDose: 'Pha 2 ống Adrenaline 1mg vào 500mL NaCl 0.9% (hoặc pha bơm tiêm điện 50mL)',
            maintenanceDose: 'Khởi đầu 0.1 - 0.2 mcg/kg/phút (hoặc 10 - 20 giọt/phút), chỉnh liều theo huyết áp',
            isHighAlert: true,
            clinicalNotes: 'Theo dõi monitor điện tim liên tục để phát hiện loạn nhịp tim.',
          },
          {
            genericName: 'Methylprednisolone / Diphenhydramine',
            route: 'IV',
            maintenanceDose: 'Methylprednisolone 1 - 2 mg/kg IV + Kháng Histamin H1 (Diphenhydramine/Dimedrol 10-20mg tiêm bắp/IV)',
            clinicalNotes: 'Thuốc hỗ trợ bậc 2 giúp ngăn ngừa phản vệ pha 2 (Biphasic reaction), KHÔNG THỂ thay thế Adrenaline trong cấp cứu ban đầu.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_4_biphasic_monitoring',
        order: 4,
        phase: 'recovery',
        title: '4. Theo Dõi Phản Vệ Pha 2 & Xuất Viện An Toàn',
        timeframe: 'Theo dõi 24 - 72 giờ',
        description: 'Theo dõi sát bệnh nhân tại khoa Hồi sức cấp cứu ít nhất 24 giờ sau khi đã ngừng hoàn toàn Adrenaline để phát hiện phản vệ pha 2 (xuất hiện sau 1 - 8 giờ kể từ đợt ban đầu). Hướng dẫn bệnh nhân tránh dị nguyên và cấp đơn bút tiêm Adrenaline tự động (EpiPen) nếu có điều kiện.',
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Bệnh tim thiếu máu cục bộ / Tăng huyết áp / Người cao tuổi',
        forbiddenDrugOrAction: 'Chần chừ hoặc không dám tiêm Adrenaline khi có phản vệ từ Độ II',
        dangerLevel: 'absolute',
        explanation: 'Phản vệ gây tử vong nhanh chóng do ngạt thở và giãn mạch trụy tuần hoàn, Adrenaline là thuốc duy nhất cứu sống người bệnh. Không có chống chỉ định tuyệt đối của Adrenaline trong cấp cứu phản vệ đe dọa tính mạng.',
        recommendation: 'BẮT BUỘC tiêm Adrenaline đúng liều. Theo dõi sát monitor điện tim.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Xử Trí Chuẩn Theo Thông Tư 51/BYT (Adrenaline Tiêm Bắp Ngay + Nhập Viện Theo Dõi 24h)',
        approachType: 'standard-invasive',
        pros: [
          'Cứu sống bệnh nhân ngay lập tức, tỷ lệ hồi phục hoàn toàn > 98% nếu tiêm Adrenaline sớm trong 5 phút đầu.',
          'Phát hiện và xử trí kịp thời phản vệ pha 2 nguy hiểm.',
        ],
        cons: [
          'Bệnh nhân có thể có cảm giác hồi hộp, tim đập nhanh, run tay thoáng qua sau tiêm Adrenaline.',
        ],
        estimatedCost: 'low',
        suitableFor: 'Mọi trường hợp phản vệ từ Độ II trở lên.',
      },
    ],
    emergencyDetails: {
      hemodynamicTargets: ['Huyết áp trở về bình thường theo lứa tuổi', 'SpO2 >= 95%'],
      inotropesVasopressors: ['Adrenaline: Thuốc thiết yếu số 1'],
      resuscitationFluid: 'NaCl 0.9% xả nhanh 1 - 2 Lít ở người lớn (10-20 mL/kg ở trẻ em)',
      emergencyScores: ['Phân độ phản vệ Độ I đến Độ IV theo TT 51/2017/TT-BYT'],
    },
    dischargeCriteria: [
      'Không còn bất kỳ triệu chứng hô hấp hay tuần hoàn nào liên tục ≥ 24 giờ sau khi ngừng Adrenaline.',
      'Sinh hiệu ổn định hoàn toàn.',
      'Đã xác định và tư vấn dị nguyên gây dị ứng, hướng dẫn cấp cứu nếu tái phát.',
    ],
    updatedAt: '2026-08-22',
  },
];
