/**
 * CliniPortal 2.0 — Tủ Sách Phác Đồ Nội Tiêu Hóa - Gan Mật
 * Path: src/content/protocols/registry/gi-protocols.ts
 *
 * Ngăn tủ chuyên sâu Tiêu hóa: XHTH vỡ giãn TMTQ, Loét dạ dày, Viêm tụy cấp, Xơ gan mất bù & SBP.
 */

import { ClinicalProtocol } from '../protocol-types';

export const GI_PROTOCOLS: ClinicalProtocol[] = [
  // ═══ NGĂN 1: XUẤT HUYẾT TIÊU HÓA DO VỠ GIÃN TĨNH MẠCH THỰC QUẢN (BAVENO VII) ═══
  {
    id: 'pddt-ugib-variceal-baveno-vii',
    title: 'Phác đồ Xử trí Xuất huyết Tiêu hóa do Vỡ giãn Tĩnh mạch Thực quản (Baveno VII / QĐ 3010/BYT)',
    titleEn: 'Baveno VII Consensus: Acute Variceal Bleeding Management Protocol',
    aliases: ['Xuất huyết do vỡ giãn TMTQ', 'XHTH xơ gan', 'Variceal Bleeding', 'Baveno VII'],
    icd10: ['I85.0', 'K92.2', 'K74'],
    specialty: 'gi',
    triageLevel: 'emergency',
    guidelineSource: 'Baveno VII Consensus (2022) & Quyết định 3010/QĐ-BYT Bộ Y Tế Việt Nam',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Bộ 4 can thiệp cốt lõi ngay khi tiếp nhận: Ổn định huyết động (Hb đích 7-8 g/dL), Thuốc co mạch tạng sớm (Terlipressin/Octreotide), Kháng sinh dự phòng Ceftriaxone 7 ngày, và Nội soi can thiệp thắt vòng cao su EVL trong vòng 12 giờ.',
    redFlags: [
      'Nôn ra máu đỏ tươi ồ ạt hoặc đi cầu phân máu đen lượng lớn kèm tụt huyết áp.',
      'Sốc mất máu: Mạch nhanh > 120 l/p, HA tâm thu < 90 mmHg hoặc HA kẹt, CRT ≥ 3s.',
      'Rối loạn tri giác / Bệnh não gan tiến triển do ứ đọng máu trong ống tiêu hóa.',
      'Nguy cơ trào ngược sặc phổi gây suy hô hấp tối khẩn ở bệnh nhân hôn mê.',
    ],
    steps: [
      {
        stepId: 'step_1_resus_airway',
        order: 1,
        phase: 'triage',
        title: '1. Hồi sức Huyết động Mục tiêu & Bảo vệ Đường thở (0 - 15 phút)',
        timeframe: 'Phút 0 - 15',
        description: 'Cho bệnh nhân nằm đầu thấp nghiêng một bên hoặc đặt nội khí quản bảo vệ đường thở nếu nôn máu dữ dội/hôn mê (GCS ≤ 8). Thiết lập 2 đường truyền tĩnh mạch lớn. Truyền Hồng cầu lắng duy trì Hb mục tiêu 7 - 8 g/dL (Hct 21 - 24%). TUYỆT ĐỐI TRÁNH truyền máu quá mức làm tăng áp lực tĩnh mạch cửa gây chảy máu bùng phát.',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_vasoactive_abx',
        order: 2,
        phase: 'first-line',
        title: '2. Khởi Động Thuốc Co Mạch Tạng & Kháng Sinh Dự Phòng Sớm',
        timeframe: 'Ngay khi nghi ngờ XHTH do tăng ALTM cửa (Trước khi nội soi)',
        description: 'Bắt đầu ngay Terlipressin hoặc Octreotide/Somatostatin để giảm áp lực dòng chảy tĩnh mạch cửa. Dùng ngay Ceftriaxone tĩnh mạch để giảm nguy cơ nhiễm trùng tái phát và tử vong.',
        drugs: [
          {
            genericName: 'Terlipressin',
            tradeNames: ['Glypressin'],
            route: 'IV',
            loadingDose: '2 mg tiêm tĩnh mạch bolus mỗi 4 giờ trong 48 giờ đầu',
            maintenanceDose: 'Giảm xuống 1 mg mỗi 4 giờ khi đã kiểm soát chảy máu (duy trì 2 - 5 ngày)',
            isHighAlert: true,
            clinicalNotes: 'Thuốc co mạch tạng lựa chọn hàng đầu, cải thiện sống còn và bảo vệ chức năng thận.',
          },
          {
            genericName: 'Octreotide',
            tradeNames: ['Sandostatin'],
            route: 'IV',
            loadingDose: '50 mcg tiêm tĩnh mạch bolus',
            maintenanceDose: 'Truyền tĩnh mạch liên tục 50 mcg/giờ trong 3 - 5 ngày',
            clinicalNotes: 'Lựa chọn thay thế Terlipressin. Tác dụng phụ: Tăng/hạ đường huyết thoáng qua.',
          },
          {
            genericName: 'Ceftriaxone',
            tradeNames: ['Rocephin'],
            route: 'IV',
            loadingDose: '1g IV mỗi 24 giờ trong 7 ngày',
            maintenanceDose: '1g/ngày',
            clinicalNotes: 'BẮT BUỘC dùng cho mọi bệnh nhân xơ gan có XHTH để phòng ngừa nhiễm trùng báng SBP và tử vong.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_endoscopy_evl',
        order: 3,
        phase: 'first-line',
        title: '3. Nội Soi Tiêu Hóa Cầm Máu Bằng Thắt Vòng Cao Su (EVL)',
        timeframe: 'Trong vòng 12 giờ sau khi ổn định huyết động',
        description: 'Tiến hành nội soi thực quản - dạ dày can thiệp thắt vòng cao su (Endoscopic Variceal Ligation - EVL). Nếu chảy máu từ giãn tĩnh mạch phình vị dạ dày (GOV2/IGV1): Tiêm xơ mô sinh học Histoacryl (Cyanoacrylate).',
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_refractory_tips',
        order: 4,
        phase: 'refractory',
        title: '4. Xử Trí Chảy Máu Thất Bại / Kháng Trị: TIPS Cứu Vãn hoặc Chèn Bóng',
        timeframe: 'Khi thất bại với EVL lần 2 hoặc chảy máu ồ ạt tái diễn',
        description: 'Đặt sonde chèn bóng Sengstaken-Blakemore / Linton-Nachlas tạm thời (tối đa 24h) làm cầu nối để chuyển làm Thông nối cửa - chủ qua tĩnh mạch cảnh (TIPS cứu vãn) hoặc đặt Stent kim loại tự bung thực quản (Danis Stent).',
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_5_secondary_prophylaxis',
        order: 5,
        phase: 'recovery',
        title: '5. Dự Phòng Tái Phát Thứ Phát: Phối Hợp EVL + Chẹn Beta Không Chọn Lọc',
        timeframe: 'Từ ngày thứ 5 trở đi sau khi ngưng thuốc co mạch tạng',
        description: 'Khởi đầu thuốc chẹn Beta không chọn lọc (Carvedilol 6.25 - 12.5 mg/ngày hoặc Propranolol) kết hợp nội soi thắt lại vòng cao su mỗi 2 - 4 tuần cho đến khi triệt tiêu hoàn toàn búi giãn.',
        drugs: [
          {
            genericName: 'Carvedilol',
            route: 'PO',
            loadingDose: '6.25 mg uống 1 lần/ngày lúc no',
            maintenanceDose: 'Tăng lên 12.5 mg/ngày sau 3 - 7 ngày nếu dung nạp tốt (đích HA tâm thu ≥ 90 mmHg)',
            clinicalNotes: 'Carvedilol hạ áp lực tĩnh mạch cửa mạnh hơn Propranolol nhờ thêm tác dụng chẹn thụ thể Alpha-1.',
          },
        ],
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Hạ huyết áp nặng / Nhiễm trùng dịch báng (SBP) đang tiến triển / Suy thận cấp AKI',
        forbiddenDrugOrAction: 'Khởi đầu thuốc chẹn Beta giao cảm liều cao ngay trong đợt xuất huyết cấp',
        dangerLevel: 'absolute',
        explanation: 'Chẹn beta làm giảm cung lượng tim và huyết áp làm nặng thêm tình trạng giảm tưới máu thận, khởi phát Hội chứng Gan Thận (HRS).',
        recommendation: 'Chỉ khởi đầu Chẹn Beta sau khi đã kiểm soát xuất huyết ổn định ≥ 48-72h và huyết động ổn định.',
      },
      {
        conflictWithCondition: 'Rối loạn đông máu trong xơ gan (INR kéo dài)',
        forbiddenDrugOrAction: 'Truyền huyết tương tươi đông lạnh (FFP) thường quy để chỉnh INR',
        dangerLevel: 'relative',
        explanation: 'Baveno VII khuyến cáo không truyền FFP thường quy vì làm tăng thể tích tuần hoàn và áp lực cửa gây chảy máu bùng phát nặng hơn.',
        recommendation: 'Chỉ truyền Hồng cầu lắng đạt đích Hb 7-8 g/dL và Tiểu cầu nếu < 50.000 kèm chảy máu khó cầm.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Nội soi Can thiệp Thắt vòng EVL + Thuốc Co mạch tạng Terlipressin',
        approachType: 'standard-invasive',
        pros: [
          'Tỷ lệ cầm máu thành công ban đầu đạt > 90%.',
          'Bảo tồn tối đa chức năng gan, ít biến chứng bệnh não gan hơn phẫu thuật.',
        ],
        cons: [
          'Nguy cơ chảy máu tái phát từ vết loét sau thắt vòng cao su (5 - 10%).',
        ],
        estimatedCost: 'medium',
        suitableFor: 'Mọi bệnh nhân có xuất huyết do vỡ giãn tĩnh mạch thực quản.',
      },
      {
        optionName: 'Phương án 2: Đặt Thông nối Cửa - Chủ Qua Gan (TIPS Sớm / Pre-emptive TIPS trong 72h)',
        approachType: 'alternative',
        pros: [
          'Giảm triệt để áp lực tĩnh mạch cửa, giảm tỷ lệ tái xuất huyết xuống dưới 10% và tăng tỷ lệ sống còn.',
        ],
        cons: [
          'Nguy cơ xuất hiện hoặc làm nặng thêm Bệnh não gan (Hepatic Encephalopathy) do máu không qua gan khử độc.',
          'Chi phí can thiệp can thiệp mạch cao.',
        ],
        estimatedCost: 'high',
        suitableFor: 'Bệnh nhân nguy cơ thất bại cao: Child-Pugh C (10-13 điểm) hoặc Child-Pugh B có chảy máu hoạt động lúc nội soi.',
      },
    ],
    giDetails: {
      endoscopyProtocol: 'EVL thắt vòng cao su thực quản trong 12h + Terlipressin IV 2mg q4h x 48h + Ceftriaxone 1g/ngày x 7 ngày',
      liverFunctionStaging: 'Phân loại Child-Pugh A/B/C, MELD-Na score và Thang điểm Bệnh não gan West Haven (Độ I-IV)',
      ascitesSbpManagement: 'Chọc tháo dịch báng chẩn đoán nếu có báng bụng, dùng Cefotaxime 2g q8h + Albumin 1.5g/kg ngày 1 và 1g/kg ngày 3',
    },
    dischargeCriteria: [
      'Không có dấu hiệu tái xuất huyết liên tục ≥ 48 - 72 giờ.',
      'Huyết động ổn định, Hb duy trì > 8 g/dL không cần truyền máu thêm.',
      'Đã hoàn thành đợt kháng sinh dự phòng 7 ngày.',
      'Đã khởi đầu chẹn Beta không chọn lọc dung nạp tốt và hẹn lịch nội soi thắt lại sau 2 - 4 tuần.',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 2: VIÊM TỤY CẤP (ACUTE PANCREATITIS - ATLANTA 2012 / IAP 2025) ═══
  {
    id: 'pddt-acute-pancreatitis-atlanta',
    title: 'Phác đồ Chẩn đoán & Hồi sức Viêm Tụy Cấp (Atlanta / IAP 2025)',
    titleEn: 'International Association of Pancreatology Guidelines on Acute Pancreatitis',
    aliases: ['Viêm tụy cấp', 'Acute Pancreatitis', 'Atlanta Guidelines', 'IAP Guidelines'],
    icd10: ['K85', 'K85.0', 'K85.9'],
    specialty: 'gi',
    triageLevel: 'emergency',
    guidelineSource: 'International Association of Pancreatology (IAP / APA 2025) & Bộ Y Tế',
    evidenceLevel: 'Class I, Level A',
    year: 2025,
    summary: 'Chẩn đoán xác định khi có 2/3 tiêu chuẩn (Đau bụng tụy cấp, Amylase/Lipase tăng ≥ 3 lần giới hạn trên, Hình ảnh học CT/Siêu âm). Bù dịch Ringer Lactate có định hướng mục tiêu, Giảm đau đa mô thức, Dinh dưỡng đường ruột sớm trong 24-72h, KHÔNG dùng kháng sinh dự phòng thường quy.',
    redFlags: [
      'Dấu hiệu suy tạng (Thang điểm Marshall sửa đổi ≥ 2 điểm kéo dài > 48h): Huyết áp tụt, PaO2/FiO2 ≤ 300, Creatinine ≥ 170 µmol/L.',
      'Dấu hiệu viêm hệ thống rầm rộ (SIRS dương tính kéo dài > 48h).',
      'Dấu hiệu xuất huyết sau phúc mạc: Dấu Cullen (bầm máu quanh rốn), Dấu Grey-Turner (bầm máu 2 bên mạn sườn).',
      'Hematocrit tăng cao > 44% (cô đặc máu nặng) hoặc BUN > 20 mg/dL.',
    ],
    steps: [
      {
        stepId: 'step_1_diagnosis_triage',
        order: 1,
        phase: 'triage',
        title: '1. Chẩn Đoán Xác Định & Phân Tầng Mức Độ Nặng (0 - 15 phút)',
        timeframe: 'Phút 0 - 15',
        description: 'Xác định chẩn đoán (Đau bụng thượng vị lan ra sau lưng + Lipase/Amylase ≥ 3 lần). Phân loại mức độ nặng theo Atlanta sửa đổi: Nhẹ (không suy tạng), Trung bình nặng (suy tạng thoáng qua < 48h hoặc biến chứng tại chỗ), Nặng (suy tạng kéo dài > 48h).',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_goal_directed_fluid',
        order: 2,
        phase: 'first-line',
        title: '2. Bù Dịch Ringer Lactate Định Hướng Mục Tiêu (Goal-Directed Fluid)',
        timeframe: 'Trong 24 giờ đầu',
        description: 'Bù dịch tinh thể (ưu tiên Ringer Lactate hơn NaCl 0.9%) tốc độ 200 - 250 mL/giờ (hoặc bolus 10 - 20 mL/kg nếu có tụt HA/cô đặc máu). Đánh giá lại mỗi 4 - 6 giờ: Đích Hct < 44%, BUN giảm, Nước tiểu ≥ 0.5 - 1 mL/kg/h, MAP ≥ 65 mmHg. Tránh truyền dịch ồ ạt quá mức (> 4 - 5 L/24h) gây tăng áp lực ổ bụng và suy hô hấp.',
        drugs: [
          {
            genericName: 'Ringer Lactate',
            route: 'IV',
            maintenanceDose: '200 - 250 mL/giờ trong 24 giờ đầu (titrate theo Hct và nước tiểu)',
            clinicalNotes: 'Ringer Lactate có tính kháng viêm và giảm nguy cơ SIRS so với NaCl 0.9%.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_analgesia_nutrition',
        order: 3,
        phase: 'first-line',
        title: '3. Kiểm Soát Đau Đa Mô Thức & Khởi Động Dinh Dưỡng Đường Ruột Sớm',
        timeframe: 'Trong 24 - 72 giờ đầu',
        description: 'Giảm đau hiệu quả bằng Paracetamol IV + NSAIDs (nếu không suy thận) hoặc Opioid (Fentanyl / Morphine). Khởi động cho ăn qua đường miệng sớm (thức ăn mềm, ít béo) ngay khi bệnh nhân hết đau bụng và hết nôn ói. Nếu không ăn được: Đặt ống thông nuôi ăn qua dạ dày/hỗng tràng.',
        drugs: [
          {
            genericName: 'Paracetamol',
            route: 'IV',
            maintenanceDose: '1g IV truyền ngắt quãng mỗi 6 giờ khi đau',
            clinicalNotes: 'Nền tảng giảm đau bậc 1.',
          },
          {
            genericName: 'Fentanyl / Morphine',
            route: 'IV',
            loadingDose: 'Fentanyl 25 - 50 mcg IV tiêm chậm hoặc Morphine 2 - 5 mg IV',
            clinicalNotes: 'Giảm đau cơn đau cấp dữ dội. Morphine không làm tăng biến chứng cơ vòng Oddi như quan niệm cũ.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_no_prophylactic_abx',
        order: 4,
        phase: 'refractory',
        title: '4. Quản Lý Hoại Tử Nhiễm Trùng: Kháng Sinh Trúng Đích & Can Thiệp Tối Thiểu (Step-Up)',
        timeframe: 'Tuần thứ 2 - 4 của bệnh',
        description: 'TUYỆT ĐỐI KHÔNG dùng kháng sinh dự phòng thường quy cho viêm tụy cấp hoại tử vô trùng. Chỉ dùng kháng sinh ngấm tốt mô tụy (Meropenem 1g q8h hoặc Ciprofloxacin + Metronidazole) khi nghi ngờ hoại tử nhiễm trùng (sốt cao sau tuần 1, có khí trong ổ hoại tử trên CT). Can thiệp dẫn lưu qua da/nội soi trước khi phẫu thuật mở (Chiến lược Step-Up Approach).',
        isAlert: true,
        flowchartNodeType: 'alert',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Viêm tụy cấp thể phù nề hoặc hoại tử vô trùng',
        forbiddenDrugOrAction: 'Chỉ định Kháng sinh Dự phòng thường quy',
        dangerLevel: 'absolute',
        explanation: 'Nhiều thử nghiệm RCT chứng minh kháng sinh dự phòng không giảm tỷ lệ tử vong hay nhiễm trùng nhưng làm tăng nguy cơ nhiễm nấm và vi khuẩn đa kháng.',
        recommendation: 'Chỉ dùng kháng sinh khi có bằng chứng nhiễm trùng rõ ràng (cấy máu/dịch hoại tử dương tính hoặc có khí trên CT).',
      },
      {
        conflictWithCondition: 'Viêm tụy cấp do Tăng Triglyceride máu (Triglyceride > 11.3 mmol/L hoặc > 1000 mg/dL)',
        forbiddenDrugOrAction: 'Bù dịch đơn thuần mà không hạ Triglyceride khẩn cấp',
        dangerLevel: 'absolute',
        explanation: 'Axit béo tự do gây độc trực tiếp và tiếp tục phá hủy nhu mô tụy nặng nề.',
        recommendation: 'Chỉ định truyền Insulin tĩnh mạch liên tục 0.05 - 0.1 UI/kg/h + Glucose 5% để duy trì đường huyết 150-200 mg/dL và hạ Triglyceride < 500 mg/dL (hoặc Thay huyết tương lọc máu cấp).',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Dinh Dưỡng Đường Ruột Sớm (Oral / Enteral Feeding trong 24-72h)',
        approachType: 'standard-invasive',
        pros: [
          'Bảo vệ hàng rào niêm mạc ruột, ngăn ngừa vi khuẩn đường ruột chuyển vị gây nhiễm trùng hoại tử tụy.',
          'Giảm rõ rệt biến chứng suy tạng và tỷ lệ tử vong so with nhịn ăn kéo dài.',
        ],
        cons: [
          'Bệnh nhân có thể cảm thấy chướng bụng nhẹ.',
        ],
        estimatedCost: 'low',
        suitableFor: 'Mọi bệnh nhân viêm tụy cấp mức độ nhẹ đến nặng.',
      },
      {
        optionName: 'Phương án 2: Nuôi Ăn Hoàn Toàn Bằng Đường Tĩnh Mạch (TPN)',
        approachType: 'conservative',
        pros: [
          'Áp dụng được khi ruột bị liệt hoàn toàn không thể dung nạp thức ăn.',
        ],
        cons: [
          'Làm teo nhung mao niêm mạc ruột, tăng nguy cơ nhiễm trùng huyết liên quan đến đường truyền catheter tĩnh mạch và chi phí rất cao.',
        ],
        estimatedCost: 'high',
        suitableFor: 'Chỉ dành cho bệnh nhân không thể dung nạp dinh dưỡng đường ruột sau 5 - 7 ngày.',
      },
    ],
    giDetails: {
      pancreatitisFluid: 'Ringer Lactate 200-250 mL/h trong 24h đầu, đích Hct < 44%, nước tiểu >= 0.5-1 mL/kg/h, tránh quá tải dịch > 4L',
    },
    dischargeCriteria: [
      'Hết đau bụng hoàn toàn, ăn uống ngon miệng bằng đường miệng.',
      'Không có triệu chứng sốt hoặc dấu hiệu suy tạng.',
      'Đã xác định và điều trị nguyên nhân gốc rễ (Cắt túi mật trong cùng đợt nằm viện nếu do sỏi mật, hoặc hạ Triglyceride máu).',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 3: BỆNH NÃO GAN & DỰ PHÒNG TÁI PHÁT (HEPATIC ENCEPHALOPATHY - EASL 2022) ═══
  {
    id: 'pddt-hepatic-encephalopathy-easl',
    title: 'Phác đồ Chẩn đoán, Xử trí & Dự phòng Bệnh Não Gan (EASL 2022 / AASLD)',
    titleEn: 'EASL Clinical Practice Guidelines on the Management of Hepatic Encephalopathy',
    aliases: ['Bệnh não gan', 'Hepatic Encephalopathy', 'Hôn mê gan', 'Lactulose', 'Rifaximin', 'LOLA', 'Covert HE', 'HE Post-TIPS'],
    icd10: ['K72.9', 'K72.7', 'K74'],
    specialty: 'gi',
    triageLevel: 'emergency',
    guidelineSource: 'EASL Clinical Practice Guidelines on the management of hepatic encephalopathy (2022)',
    evidenceLevel: 'Class I, Level A / LoE 1-5',
    year: 2024,
    summary: 'Quy trình tiếp cận toàn diện theo EASL 2022: Bảo vệ đường thở khi GCS < 8 hoặc West Haven Grade III-IV; Nhận diện và điều trị triệt để các yếu tố thúc đẩy (chiếm 90% thành công: SBP, XHTH, rối loạn điện giải, táo bón, dùng an thần); Disaccharide không hấp thu (Lactulose PO/PR duy trì 2-3 phân mềm/ngày); Phối hợp Rifaximin 550mg x 2 khi tái phát >= 1 đợt trong 6 tháng; Bổ sung LOLA truyền TM liều cao và Oral BCAA chống teo cơ sarcopenia; Sàng lọc Covert HE và dự phòng sau TIPS.',
    redFlags: [
      'Điểm Hôn Mê Glasgow (GCS) < 8 hoặc West Haven Grade III-IV: Nguy cơ cao mất phản xạ bảo vệ đường thở, đe dọa tử vong do hít sặc -> ĐẶT NỘI KHÍ QUẢN CẤP CỨU NGAY.',
      'Sinh hiệu bất ổn: Tụt huyết áp, sốc nhiễm trùng, mạch nhanh nhỏ.',
      'Xuất huyết tiêu hóa do vỡ giãn tĩnh mạch thực quản đang tiến triển (máu trong ruột là nguồn sinh NH3 khổng lồ).',
      'Suy thận cấp, thiểu niệu/vô niệu hoặc Tăng/Hạ Kali máu nặng đe dọa ngừng tim.',
      'Mất định hướng không gian/thời gian tiến triển nhanh hoặc co giật, hôn mê sâu.',
    ],
    steps: [
      {
        stepId: 'step_1_airway_triage_abc',
        order: 1,
        phase: 'triage',
        title: '1. Tiếp Cận Khẩn Cấp A-B-C, Bảo Vệ Đường Thở & Xét Nghiệm Ammonia Máu (0 - 15 phút)',
        timeframe: 'Phút 0 - 15 tiếp nhận',
        description: 'Đánh giá đường thở, nhịp thở và tuần hoàn (A-B-C). Đo đường huyết mao mạch tại giường (loại trừ hạ đường huyết). NẾU bệnh nhân có West Haven Grade III-IV hoặc GCS < 8: Đặt nội khí quản bảo vệ đường thở khẩn cấp phòng ngừa sặc phổi, đặt sonde dạ dày hút sạch máu (nếu có XHTH), và bơm rửa đại tràng bằng Lactulose thụt giữ trực tràng. Xét nghiệm cấp: Ammonia máu, Ure, Creatinine, Điện giải đồ, Khí máu động mạch, Đông máu toàn bộ PT/INR, Bilirubin, Cấy máu & Dịch màng bụng.',
        conditionIf: 'Grade III-IV hoặc GCS < 8 (Hôn mê, sững sờ)',
        conditionThen: 'Đặt nội khí quản bảo vệ đường thở ngay + Chuyển khoa Hồi sức tích cực (ICU).',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_precipitating_factors',
        order: 2,
        phase: 'first-line',
        title: '2. Nhận Diện & Điều Trị Triệt Để Yếu Tố Thúc Đẩy (Precipitating Factors — 90% Thành Công)',
        timeframe: 'Giờ 1 - 6',
        description: 'Truy tìm và xử trí triệt để yếu tố khởi phát: (1) Nhiễm trùng: Cấy máu/dịch báng và dùng kháng sinh phổ rộng Ceftriaxone 1g/ngày; (2) Xuất huyết tiêu hóa: Bù thể tích, Terlipressin/Octreotide, EVL thắt búi giãn; (3) Táo bón: Thụt tháo đại tràng; (4) Rối loạn nước - điện giải: TẠM NGỪNG LỢI TIỂU (Furosemide, Spironolactone), bù dịch NaCl 0.9%/Ringer và chỉnh hạ Kali/Natri; (5) Thuốc: Ngừng ngay toàn bộ thuốc an thần, benzodiazepin, opioid.',
        isAlert: true,
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_firstline_lactulose',
        order: 3,
        phase: 'first-line',
        title: '3. Liệu Pháp Bậc 1: Disaccharide Không Hấp Thu (Lactulose Đường Uống / Thụt Trực Tràng)',
        timeframe: 'Khởi động ngay lập tức',
        description: 'Lactulose (hoặc Lactitol) là lựa chọn ưu tiên hàng đầu (LoE 1, Khuyến cáo mạnh). Đường uống (PO): Liều tấn công 15 - 30 mL (10 - 20 g) mỗi 1 - 2 giờ đến khi đi tiêu phân mềm; sau đó duy trì 15 - 30 mL x 2 - 3 lần/ngày, chỉnh liều đạt mục tiêu 2 - 3 bãi phân mềm/ngày. Nếu bệnh nhân hôn mê/không uống được: Thụt giữ trực tràng (300 mL Lactulose + 700 mL nước ấm) giữ trong 30-60 phút mỗi 4 - 6 giờ.',
        drugs: [
          {
            genericName: 'Lactulose',
            tradeNames: ['Duphalac'],
            route: 'PO',
            loadingDose: '15 - 30 mL uống mỗi 1 - 2 giờ đến khi đi tiêu phân mềm (hoặc Thụt giữ trực tràng 300 mL + 700 mL nước ấm)',
            maintenanceDose: '15 - 30 mL uống 2 - 3 lần/ngày (chỉnh liều đạt đích 2 - 3 bãi phân mềm/ngày)',
            clinicalNotes: 'CẢNH BÁO: Tránh lạm dụng gây tiêu chảy quá mức (> 4-5 lần/ngày) gây mất nước, hạ Kali và kiềm chuyển hóa làm HE bùng phát nặng hơn.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_secondline_rifaximin_lola',
        order: 4,
        phase: 'refractory',
        title: '4. Liệu Pháp Bậc 2 & Dự Phòng Thứ Phát: Phối Hợp Rifaximin + LOLA Truyền Tĩnh Mạch',
        timeframe: 'Khi tái phát hoặc không đáp ứng hoàn toàn với Lactulose',
        description: 'NẾU tái phát ≥ 1 đợt Overt HE trong vòng 6 tháng (hoặc đáp ứng kém với Lactulose đơn trị): BẮT BUỘC phối hợp thêm Rifaximin 550 mg x 2 lần/ngày (LoE 2, Khuyến cáo mạnh). Phối hợp giúp giảm 58% nguy cơ tái phát và giảm 40% tử vong. NẾU hôn mê sâu Grade III-IV kháng trị: Phối hợp truyền tĩnh mạch L-Ornithine L-Aspartate (LOLA) 20 - 30 g/ngày pha 500 mL G5% truyền chậm trong 4 - 6 giờ.',
        drugs: [
          {
            genericName: 'Rifaximin',
            tradeNames: ['Normix'],
            route: 'PO',
            maintenanceDose: '550 mg uống 2 lần/ngày (hoặc 400 mg x 3 lần/ngày) đồng trị liệu lâu dài cùng Lactulose',
            clinicalNotes: 'Kháng sinh không hấp thu toàn thân (< 0.4%). Không cần chỉnh liều theo thận. Tuyệt đối KHÔNG ngưng Lactulose khi thêm Rifaximin.',
          },
          {
            genericName: 'L-Ornithine L-Aspartate (LOLA)',
            tradeNames: ['Hepa-Merz'],
            route: 'IV',
            loadingDose: '20 - 30 g/ngày pha 500 mL Glucose 5% hoặc NaCl 0.9% truyền tĩnh mạch chậm trong 4 - 6 giờ',
            maintenanceDose: 'Chuyển sang gói uống 5 - 10 g x 3 lần/ngày sau khi tri giác hồi phục',
            renalAdjustment: 'CHỐNG CHỈ ĐỊNH TUYỆT ĐỐI khi suy thận nặng (eGFR < 30 mL/phút hoặc Creatinine > 1.5 mg/dL)',
            clinicalNotes: 'Kích hoạt chu trình ure tại gan và tăng tổng hợp glutamine thải amoniac ở cơ vân.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_5_covert_he_tips_bcaa',
        order: 5,
        phase: 'recovery',
        title: '5. Sàng Lọc Covert HE, Bổ Sung BCAA Chống Teo Cơ & Dự Phòng Sau TIPS',
        timeframe: 'Lâu dài',
        description: 'Sàng lọc Covert HE bằng Animal Naming Test (ANT) hoặc EncephalApp Stroop Test; điều trị bằng Lactulose liều thấp. Bổ sung Oral BCAA 0.2 - 0.25 g/kg/ngày kèm 1 bữa phụ trước khi đi ngủ (late-night snack) để chống teo cơ (sarcopenia). Nếu chuẩn bị đặt TIPS: Khởi trị Rifaximin dự phòng 14 ngày trước thủ thuật. Nếu HE sau TIPS kháng trị + MELD < 11: Cân nhắc thuyên tắc luồng thông tĩnh mạch cửa - chủ tự phát (SPSS embolization) hoặc đánh giá Ghép Gan.',
        drugs: [
          {
            genericName: 'Axit amin chuỗi nhánh (Oral BCAA)',
            route: 'PO',
            maintenanceDose: '0.2 - 0.25 g/kg/ngày chia 3 lần uống cùng bữa ăn và bắt buộc có 1 liều kèm bữa ăn phụ ban đêm (late-night snack)',
            clinicalNotes: 'Tăng khối lượng cơ vân để phục hồi khả năng thanh thải amoniac ngoài gan, cạnh tranh với axit amin thơm qua hàng rào máu não.',
          },
        ],
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Bệnh nhân xơ gan có Bệnh não gan (HE)',
        forbiddenDrugOrAction: 'Kiêng đạm quá mức trong chế độ ăn (Protein restriction < 0.8 g/kg/ngày)',
        dangerLevel: 'absolute',
        explanation: 'Kiêng đạm thúc đẩy dị hóa protein cơ bắp, làm nặng thêm tình trạng teo cơ (sarcopenia). Vì cơ vân là cơ quan duy nhất còn lại để thải độc amoniac ngoài gan, teo cơ sẽ làm mất khả năng thanh thải NH3 khiến HE bùng phát liên tục và kháng trị.',
        recommendation: 'BẮT BUỘC duy trì lượng đạm 1.2 - 1.5 g/kg/ngày. Ưu tiên đạm thực vật, đạm sữa hoặc bổ sung Oral BCAA.',
      },
      {
        conflictWithCondition: 'Đang điều trị phối hợp Lactulose + Rifaximin ổn định',
        forbiddenDrugOrAction: 'Ngừng đột ngột Lactulose khi thấy tri giác đã tỉnh táo hoặc vì bệnh nhân than phiền đầy hơi',
        dangerLevel: 'absolute',
        explanation: 'Ngừng Lactulose đột ngột sẽ phá vỡ cân bằng vi sinh đường ruột và pH đại tràng, kích hoạt đợt bùng phát HE lâm sàng nghiêm trọng (Breakthrough OHE).',
        recommendation: 'Duy trì phối hợp đồng thời cả 2 thuốc. Hướng dẫn bệnh nhân tự chỉnh giảm nhẹ liều Lactulose để giữ đúng 2-3 bãi phân mềm/ngày thay vì ngưng hẳn.',
      },
      {
        conflictWithCondition: 'Bệnh nhân có suy thận nặng (eGFR < 30 mL/phút hoặc Creatinine > 1.5 mg/dL)',
        forbiddenDrugOrAction: 'Chỉ định L-Ornithine L-Aspartate (LOLA) truyền tĩnh mạch hoặc đường uống liều cao',
        dangerLevel: 'absolute',
        explanation: 'Suy giảm chức năng thận làm tích lũy axit amin, gây độc trực tiếp lên hệ thần kinh và làm trầm trọng thêm hội chứng gan thận.',
        recommendation: 'Chống chỉ định tuyệt đối LOLA khi eGFR < 30 mL/phút. Kiểm tra chức năng thận trước khi kê đơn.',
      },
      {
        conflictWithCondition: 'Đợt Bệnh não gan cấp tính bùng phát',
        forbiddenDrugOrAction: 'Tiếp tục dùng thuốc Lợi tiểu (Furosemide, Spironolactone) liều cao',
        dangerLevel: 'absolute',
        explanation: 'Lợi tiểu gây mất nước và hạ Kali máu nghiêm trọng. Hạ Kali kích thích thận tăng sản xuất amoniac; kiềm chuyển hóa do mất nước chuyển ion NH4+ thành khí NH3 tự do thấm nhanh qua hàng rào máu não gây hôn mê sâu.',
        recommendation: 'TẠM NGỪNG NGAY thuốc lợi tiểu khi có đợt HE cấp. Bù dịch và điều chỉnh Kali máu về mức bình thường trước khi dùng lại lợi tiểu liều thấp.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Liệu Pháp Phối Hợp Tiêu Chuẩn Tối Ưu (Lactulose + Rifaximin 550mg x 2)',
        approachType: 'standard-invasive',
        pros: [
          'Hiệu quả dự phòng tái phát tối ưu nhất (giảm 58% nguy cơ tái phát HE, RR 0.42).',
          'Giảm 40% nguy cơ tử vong do mọi nguyên nhân và giảm đáng kể số lần tái nhập viện.',
          'Cải thiện chất lượng cuộc sống (QoL) của cả người bệnh và người chăm sóc.',
        ],
        cons: [
          'Chi phí điều trị cao (Rifaximin là thuốc đắt tiền cần dùng duy trì lâu dài).',
        ],
        estimatedCost: 'high',
        suitableFor: 'Bệnh nhân có tiền sử tái phát HE (≥ 1 đợt trong 6 tháng), bệnh nhân chuẩn bị đặt TIPS, hoặc bệnh nhân có điều kiện kinh tế.',
      },
      {
        optionName: 'Phương án 2: Liệu Pháp Đơn Trị Bảo Tồn (Lactulose Đơn Độc + Tối Ưu Dinh Dưỡng)',
        approachType: 'conservative',
        pros: [
          'Chi phí cực kỳ rẻ, dễ tiếp cận tại mọi tuyến y tế.',
          'Hiệu quả tốt trong dự phòng thứ phát sau đợt HE đầu tiên.',
        ],
        cons: [
          'Tỷ lệ tái phát HE cao hơn rõ rệt so với phác đồ phối hợp (47% vs 20% trong 14 tháng).',
          'Tác dụng phụ tiêu hóa (đầy hơi, chướng bụng, tiêu chảy) có thể gây khó chịu.',
        ],
        estimatedCost: 'low',
        suitableFor: 'Bệnh nhân sau đợt HE đầu tiên chưa có tái phát, bệnh nhân có hoàn cảnh kinh tế khó khăn, hoặc bệnh nhân dung nạp tốt với Lactulose.',
      },
      {
        optionName: 'Phương án 3: Liệu Pháp Hỗ Trợ Hướng Cơ Vân & Can Thiệp Mạch (Oral BCAA + LOLA + Thuyên Tắc SPSS)',
        approachType: 'alternative',
        pros: [
          'Tăng cường thải độc amoniac qua cơ vân, phục hồi thể trạng và khối cơ cho bệnh nhân teo cơ (sarcopenia).',
          'Thuyên tắc luồng thông cửa - chủ (SPSS embolization) giải quyết triệt để nguyên nhân HE sau TIPS.',
        ],
        cons: [
          'BCAA có vị khó uống; thủ thuật thuyên tắc SPSS đòi hỏi can thiệp mạch chuyên sâu và chỉ làm khi MELD < 11.',
        ],
        estimatedCost: 'medium',
        suitableFor: 'Bệnh nhân xơ gan teo cơ nặng, HE dai dẳng/kháng trị, hoặc có luồng thông cửa - chủ tự phát lớn.',
      },
    ],
    giDetails: {
      liverFunctionStaging: 'Phân loại West Haven (Covert: MHE/Grade I; Overt: Grade II-IV), Thang điểm Glasgow GCS, Phân loại Child-Pugh A/B/C, MELD-Na score',
      ascitesSbpManagement: 'Chọc tháo dịch báng chẩn đoán loại trừ SBP, cấy máu/dịch, tạm ngừng lợi tiểu Furosemide/Spironolactone ngay',
      endoscopyProtocol: 'Đặt sonde dạ dày rửa sạch máu bằng Lactulose nếu có XHTH, nội soi thắt búi giãn EVL trong 12h',
    },
    dischargeCriteria: [
      'Tri giác hồi phục hoàn toàn về mức nền (West Haven Grade 0 hoặc I, định hướng tốt).',
      'Các yếu tố thúc đẩy (nhiễm trùng, xuất huyết tiêu hóa, rối loạn điện giải) đã được kiểm soát triệt để.',
      'Đi tiêu ổn định 2 - 3 bãi phân mềm/ngày với liều duy trì Lactulose.',
      'Bệnh nhân ăn uống đường miệng tốt, đảm bảo cung cấp đủ đạm 1.2 - 1.5 g/kg/ngày (kèm bữa ăn phụ ban đêm).',
      'Đã tư vấn kỹ về việc tuân thủ thuốc lâu dài, cảnh báo nguy cơ lái xe và lên lịch tái khám định kỳ mỗi 1 - 3 tháng.',
    ],
    updatedAt: '2026-08-22',
  },
];
