/**
 * CliniPortal 2.0 — Kho Phác Đồ Truyền Nhiễm & Vi Sinh
 * Path: src/content/protocols/registry/infectious-protocols.ts
 */

import { ClinicalProtocol } from '../protocol-types';

export const INFECTIOUS_PROTOCOLS: ClinicalProtocol[] = [
  {
    id: 'pddt-dengue-byt-2023',
    title: 'Phác đồ Chẩn đoán, Phân tầng & Hồi sức Sốt xuất huyết Dengue',
    titleEn: 'Dengue Hemorrhagic Fever Clinical Management & Shock Resuscitation Protocol',
    aliases: ['Sốt xuất huyết Dengue', 'SXHD', 'DHF Protocol', 'Sốc Dengue'],
    icd10: ['A91', 'A90'],
    specialty: 'infectious',
    triageLevel: 'emergency',
    guidelineSource: 'Quyết định số 2760/QĐ-BYT (2023) — Bộ Y Tế Việt Nam',
    evidenceLevel: 'Class I, Level A',
    year: 2023,
    summary: 'Phân tầng 3 mức độ lâm sàng (SXHD thông thường, SXHD có dấu hiệu cảnh báo và SXHD nặng/Sốc), phác đồ bù dịch động học từng giờ, chỉ định dịch cao phân tử và kiểm soát quá tải tuần hoàn.',
    redFlags: [
      'Huyết động nguy kịch: Mạch nhanh nhỏ, khó bắt; HA kẹt (hiệu số HA ≤ 20 mmHg) hoặc tụt HA; CRT ≥ 3s; chi lạnh ẩm.',
      'Dấu hiệu cảnh báo: Vật vã, lừ đừ, đau bụng nhiều vùng gan, nôn ói ≥ 3 lần/h, xuất huyết niêm mạc, tiểu ít.',
      'Cận lâm sàng cờ đỏ: Hct tăng cao kèm tiểu cầu giảm nhanh, men gan AST/ALT ≥ 400 U/L.',
      'Cơ địa nguy cơ cao: Phụ nữ mang thai, trẻ nhũ nhi (< 12 tháng), dư cân/béo phì, người cao tuổi (≥ 60 tuổi), bệnh nhân Thalassemia.',
    ],
    steps: [
      {
        stepId: 'step_1_triage',
        order: 1,
        phase: 'triage',
        title: 'Tiếp nhận Khẩn & Phân tầng Nguy cơ (0 - 15 phút)',
        timeframe: 'Phút 0 - 15',
        description: 'Đánh giá nhanh tri giác, dấu hiệu sinh tồn (Mạch, HA, Nhịp thở, Nhiệt độ), đo CRT tại giường và làm xét nghiệm Hct tại giường kèm đếm tiểu cầu khẩn. Thở oxy gọng mũi 1 - 6 L/phút nếu có suy hô hấp hoặc sốc.',
        conditionIf: 'Mạch = 0, HA = 0 hoặc HA kẹt/tụt nặng (Sốc nguy kịch)',
        conditionThen: 'Cho nằm đầu thấp, bơm trực tiếp dịch tinh thể 15 - 20 ml/kg trong 15 phút, chuyển khẩn sang Bước 3.',
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_mild_outpatient',
        order: 2,
        phase: 'first-line',
        title: 'SXHD Thông thường (Độ 1) — Điều trị Ngoại trú',
        timeframe: 'Ngày 1 - 7',
        description: 'Chỉ định điều trị ngoại trú và theo dõi sát hàng ngày tại y tế cơ sở. Hướng dẫn bù nước bằng Oresol đường uống, nước hoa quả. Hạ sốt bằng Paracetamol đơn chất. Dặn dò tái khám khẩn khi có bất kỳ dấu hiệu cảnh báo nào.',
        drugs: [
          {
            genericName: 'Paracetamol',
            tradeNames: ['Efferalgan', 'Panadol', 'Hapacol'],
            route: 'PO',
            maintenanceDose: '10 - 15 mg/kg/lần mỗi 4 - 6 giờ (khi sốt ≥ 38.5°C)',
            maxDose24h: '60 mg/kg/24 giờ (tối đa 3g/ngày ở người lớn)',
            hepaticAdjustment: 'Chống chỉ định khi AST/ALT ≥ 400 U/L hoặc có suy gan cấp',
            clinicalNotes: 'TUYỆT ĐỐI CẤM Aspirin, Ibuprofen và các NSAIDs vì nguy cơ xuất huyết tiêu hóa ồ ạt và toan máu.',
          },
        ],
        flowchartNodeType: 'stable',
      },
      {
        stepId: 'step_3_warning_inpatient',
        order: 3,
        phase: 'first-line',
        title: 'SXHD Có Dấu hiệu Cảnh báo (Độ 2) — Bù dịch Tinh thể Động học',
        timeframe: 'Giờ 1 - 24',
        description: 'Nhập viện điều trị nội trú bắt buộc. Truyền dịch tinh thể đẳng trương (Ringer Lactate hoặc NaCl 0.9%): Trẻ em 6-7 ml/kg/h (1-3h đầu) -> giảm xuống 5 ml/kg/h (2-4h) -> 3 ml/kg/h -> 1.5 ml/kg/h. Người lớn 6 ml/kg/h -> 3 ml/kg/h -> 1.5 ml/kg/h. Đo lại Hct mỗi 2-4h.',
        drugs: [
          {
            genericName: 'Ringer Lactate / Ringer Acetate / NaCl 0.9%',
            route: 'IV',
            maintenanceDose: '1.5 - 7 ml/kg/giờ theo đáp ứng lâm sàng và động học Hct',
            hepaticAdjustment: 'Thay Ringer Lactate bằng Ringer Acetate hoặc NaCl 0.9% nếu AST/ALT ≥ 1000 U/L hoặc Thalassemia.',
            clinicalNotes: 'Theo dõi sát lượng nước tiểu (đích ≥ 0.5 - 1 ml/kg/h) và nhịp thở để tránh phù phổi cấp.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_4_shock_resus',
        order: 4,
        phase: 'refractory',
        title: 'Hồi sức SỐC SXHD / Sốc Nguy kịch (Độ 3)',
        timeframe: 'Giờ đầu chống sốc',
        description: 'Thiết lập 2 đường truyền kim lớn (18G-20G). Trẻ em: 20 ml/kg/15 phút (nếu sốc nặng) hoặc 20 ml/kg/h (sốc thường). Người lớn: 15 ml/kg/15 phút (nếu sốc nặng) hoặc 15 ml/kg/h. Đánh giá lại Hct và sinh hiệu ngay sau 1 giờ.',
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_5_colloid_bleeding',
        order: 5,
        phase: 'refractory',
        title: 'Xử trí Sốc trơ (Cao Phân Tử) vs Xuất huyết nội ẩn',
        timeframe: 'Khi không đáp ứng sau 1 giờ bù dịch',
        description: 'Nếu Hct còn cao (> 40%): Đổi sang Dịch Cao Phân Tử (Dextran 40 / HES 200) 10-20 ml/kg/h, đo CVP và huyết áp động mạch xâm lấn. Nếu Hct tụt > 20% kèm tụt HA: Nghi ngờ xuất huyết nội, truyền Hồng cầu lắng 5-10 ml/kg, đặt sonde dạ dày qua đường miệng.',
        drugs: [
          {
            genericName: 'Dextran 40 / HES 200.000 Da',
            route: 'IV',
            maintenanceDose: '10 - 20 ml/kg/giờ x 1 giờ, giảm dần liều theo bậc thang',
            maxDose24h: 'Không vượt quá tổng liều tích lũy 60 ml/kg',
            renalAdjustment: 'Cân nhắc ngưng hoặc giảm liều nếu Creatinine tăng vọt hoặc vô niệu',
            isHighAlert: true,
            clinicalNotes: 'Nếu tổng CPT ≥ 60 ml/kg kèm Albumin < 2.5 g/dL: Phối hợp Albumin 5-10% liều 1 g/kg trong 4-6h.',
          },
          {
            genericName: 'Dopamin / Noradrenaline',
            route: 'IV',
            loadingDose: 'Khởi đầu Dopamin 5-10 mcg/kg/phút hoặc Noradrenaline 0.05-0.1 mcg/kg/phút',
            maintenanceDose: 'Chỉnh liều theo MAP ≥ 65 mmHg và CVP > 15 cmH2O',
            isHighAlert: true,
            clinicalNotes: 'Chỉ định khi CVP > 15 cmH2O kèm sức co bóp cơ tim giảm hoặc sốc giãn mạch.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_6_recovery',
        order: 6,
        phase: 'recovery',
        title: 'Giai đoạn Hồi phục (Ngày 6 - 7) & Chống Quá tải dịch',
        timeframe: 'Ngày 6 - 7',
        description: 'Hết sốt ≥ 48h, tiểu nhiều, mạch HA ổn định, Hct giảm sinh lý do tái hấp thu dịch lòng mạch. Khẩn cấp giảm liều nhanh và ngưng hoàn toàn dịch truyền tĩnh mạch. TUYỆT ĐỐI KHÔNG truyền thêm dịch hoặc máu vì sẽ gây phù phổi cấp tử vong.',
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Viêm loét dạ dày tá tràng / Tiền sử xuất huyết tiêu hóa (K25, K26)',
        forbiddenDrugOrAction: 'Aspirin, Ibuprofen, Diclofenac, Naproxen và mọi thuốc NSAIDs',
        dangerLevel: 'absolute',
        explanation: 'NSAIDs ức chế kết tập tiểu cầu không hồi phục và gây tổn thương niêm mạc dạ dày, kết hợp với giảm tiểu cầu của Dengue gây xuất huyết tiêu hóa ồ ạt đe dọa tính mạng.',
        recommendation: 'Chỉ dùng Paracetamol đơn chất đúng liều (10-15 mg/kg mỗi 4-6h). Phối hợp thêm PPI (Esomeprazole 40mg) để bảo vệ niêm mạc.',
      },
      {
        conflictWithCondition: 'Thai kỳ (Z34, O99)',
        forbiddenDrugOrAction: 'Khởi phát chuyển dạ hoặc mổ lấy thai trong giai đoạn nguy hiểm (ngày 3 - 6)',
        dangerLevel: 'absolute',
        explanation: 'Nguy cơ băng huyết sau sinh mất kiểm soát do giảm tiểu cầu nặng và rối loạn đông máu.',
        recommendation: 'Dùng thuốc cắt cơn co tử cung trì hoãn đến giai đoạn hồi phục (ngày 7 trở đi). Bắt buộc tính dịch truyền theo CÂN NẶNG HIỆU CHỈNH.',
      },
      {
        conflictWithCondition: 'Rối loạn đông máu / Giảm tiểu cầu nặng',
        forbiddenDrugOrAction: 'Đặt ống thông dạ dày (sonde dạ dày) qua đường mũi',
        dangerLevel: 'absolute',
        explanation: 'Chấn thương niêm mạc cuốn mũi gây chảy máu mũi dữ dội không thể nhét bấc cầm máu.',
        recommendation: 'Nếu có chỉ định đặt sonde dạ dày (như nôn ra máu), BẮT BUỘC đặt qua ĐƯỜNG MIỆNG.',
      },
      {
        conflictWithCondition: 'Thalassemia / Bệnh huyết tán mạn tính (D56)',
        forbiddenDrugOrAction: 'Dùng Ringer Lactate liều cao kéo dài & đánh giá Hct theo ngưỡng người bình thường',
        dangerLevel: 'relative',
        explanation: 'Thalassemia có Hct nền thấp sinh lý (20-25%) và gan dễ ứ sắt. Ringer Lactate làm tăng gánh chuyển hóa gan.',
        recommendation: 'Chẩn đoán cô đặc máu khi Hct tăng 20% so với Hct nền của chính bệnh nhân. Ưu tiên NaCl 0.9% hoặc Ringer Acetate.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Nhập viện Hồi sức Tích cực & Bù dịch Tĩnh mạch theo Động học',
        approachType: 'standard-invasive',
        pros: [
          'Cứu sống bệnh nhân trong các tình huống nguy kịch thông qua bù đắp kịp thời thể tích lòng mạch.',
          'Theo dõi sát động học Hct tại giường mỗi 2-4h để ngăn ngừa biến chứng sốc không hồi phục.',
          'Sẵn sàng can thiệp truyền máu và dung dịch cao phân tử khi có sốc trơ hoặc xuất huyết nặng.',
        ],
        cons: [
          'Nguy cơ quá tải dịch tuần hoàn gây phù phổi cấp hoặc suy tim cấp nếu không theo dõi sát.',
          'Tăng chi phí và thời gian nằm viện hồi sức ICU.',
          'Nguy cơ nhiễm trùng liên quan đến đường truyền tĩnh mạch.',
        ],
        estimatedCost: 'medium',
        suitableFor: 'Bệnh nhân có Dấu hiệu cảnh báo, Sốc SXHD, hoặc có cơ địa nguy cơ cao (thai phụ, béo phì, Thalassemia).',
      },
      {
        optionName: 'Phương án 2: Bù dịch Đường uống Ngoại trú Tích cực (Oresol / Nước hoa quả)',
        approachType: 'conservative',
        pros: [
          'Tránh hoàn toàn tai biến quá tải dịch truyền và phù phổi cấp.',
          'Tiết kiệm chi phí y tế tối đa, tạo sự thoải mái cho bệnh nhân tại nhà.',
          'Không có nguy cơ nhiễm trùng bệnh viện hay tai biến do đường truyền.',
        ],
        cons: [
          'Đòi hỏi tuân thủ tái khám và đo Hct nghiêm ngặt hàng ngày.',
          'Có nguy cơ bỏ lỡ thời điểm vàng nếu bệnh nhân tiến triển âm thầm vào sốc giảm thể tích.',
        ],
        estimatedCost: 'low',
        suitableFor: 'Bệnh nhân SXHD thông thường Độ 1, còn uống tốt, không có dấu hiệu cảnh báo và không có bệnh lý nền nguy cơ.',
      },
    ],
    infectiousDetails: {
      diseaseDayPhase: 'Ngày 1-3 (Sốt cao liên tục) -> Ngày 4-6 (Nguy hiểm: Thoát huyết tương, Sốc, Xuất huyết) -> Ngày 7-8 (Hồi phục & Tái hấp thu dịch)',
      hctPlateletKinetic: 'Đo Hct tại giường trước và sau mỗi đợt bù dịch. Báo động khi Hct tăng > 20% hoặc Tiểu cầu < 50.000/mm3.',
      antimicrobialStewardship: 'KHÔNG dùng kháng sinh thường quy. Chỉ dùng khi có bằng chứng bội nhiễm vi khuẩn rõ ràng.',
      isolationPrecautions: 'Nằm mùng (màn) chống muỗi vằn Aedes aegypti đốt lây truyền chéo trong bệnh viện.',
    },
    dischargeCriteria: [
      'Hết sốt ít nhất 2 ngày (48 giờ) liên tục mà không cần dùng thuốc hạ sốt.',
      'Tỉnh táo, tiếp xúc tốt, ăn uống ngon miệng.',
      'Sinh hiệu ổn định hoàn toàn (Mạch và HA bình thường).',
      'Không khó thở, không có biểu hiện quá tải tuần hoàn / tràn dịch màng phổi.',
      'Hct ổn định ở mức bình thường và số lượng tiểu cầu hồi phục > 50.000/mm³.',
    ],
    updatedAt: '2026-08-22',
  },

  // ═══ NGĂN 2: SỐT RÉT NẶNG & SỐT RÉT ÁC TÍNH (ARTESUNATE TĨNH MẠCH) ═══
  {
    id: 'pddt-severe-malaria-byt',
    title: 'Phác đồ Chẩn đoán & Điều trị Sốt Rét Nặng / Sốt Rét Ác Tính (Bộ Y Tế / WHO)',
    titleEn: 'Severe Malaria & Cerebral Malaria Clinical Management Protocol',
    aliases: ['Sốt rét ác tính', 'Severe Malaria', 'Artesunate IV', 'Sốt rét thể não'],
    icd10: ['B50', 'B50.0', 'B50.8'],
    specialty: 'infectious',
    triageLevel: 'emergency',
    guidelineSource: 'Hướng dẫn chẩn đoán và điều trị bệnh Sốt rét — Bộ Y Tế Việt Nam & WHO Guidelines for Malaria',
    evidenceLevel: 'Class I, Level A',
    year: 2024,
    summary: 'Thuốc diệt ký sinh trùng đầu tay cứu sống: Artesunate tiêm tĩnh mạch liều 2.4 mg/kg tại các thời điểm 0h, 12h, 24h và sau đó mỗi 24h cho đến khi bệnh nhân uống được (chuyển sang ACT đường uống đủ 3 ngày). Hồi sức chống hạ đường huyết, toan chuyển hóa và suy thận cấp.',
    redFlags: [
      'Sốt rét thể não: Hôn mê, lơ mơ, co giật liên tục.',
      'Toan chuyển hóa nặng: Thở sâu Kussmaul, pH < 7.35, Bicarbonate < 15 mmol/L, Lactate ≥ 4 mmol/L.',
      'Hạ đường huyết nghiêm trọng: Đường huyết < 2.2 mmol/L (< 40 mg/dL) (đặc biệt khi dùng Quinine hoặc phụ nữ mang thai).',
      'Mật độ ký sinh trùng máu rất cao: Thể tư dưỡng P. falciparum ≥ 10% hồng cầu (hoặc > 200.000 KST/µL).',
      'Đái huyết cầu tố (Sốt rét tiểu huyết sắc tố): Nước tiểu đỏ nâu sẫm hoặc đen như nước vối, vô niệu.',
    ],
    steps: [
      {
        stepId: 'step_1_artesunate_iv_stat',
        order: 1,
        phase: 'triage',
        title: '1. TIÊM TĨNH MẠCH ARTESUNATE LIỀU TẤN CÔNG NGAY (Giờ thứ 0)',
        timeframe: 'Phút 0 - 15 tiếp nhận',
        description: 'Lấy lam máu nhuộm Giemsa hoặc test nhanh chẩn đoán sốt rét. Tiêm tĩnh mạch chậm Artesunate 2.4 mg/kg ngay lập tức (Trẻ em < 20kg dùng liều 3.0 mg/kg). Tuyệt đối không trì hoãn tiêm Artesunate khi đã nghi ngờ sốt rét ác tính.',
        drugs: [
          {
            genericName: 'Artesunate bột tiêm tĩnh mạch',
            route: 'IV',
            loadingDose: '2.4 mg/kg IV chậm tại thời điểm 0h, lặp lại lúc 12h và 24h (Trẻ < 20kg: 3 mg/kg/liều)',
            maintenanceDose: '2.4 mg/kg IV 1 lần/ngày cho đến khi tỉnh táo và uống được',
            isHighAlert: true,
            clinicalNotes: 'Pha bột Artesunate với 1mL dung dịch Natri Bicarbonate 5% đi kèm cho tan hoàn toàn, sau đó pha loãng với 5mL NaCl 0.9% trước khi tiêm.',
          },
        ],
        isAlert: true,
        flowchartNodeType: 'start',
      },
      {
        stepId: 'step_2_glucose_hypoglycemia',
        order: 2,
        phase: 'first-line',
        title: '2. Kiểm Soát Hạ Đường Huyết & Cân Bằng Nước Điện Giải',
        timeframe: 'Giờ 1 - 24',
        description: 'Đo đường huyết mao mạch tại giường ngay. Nếu đường huyết < 40 mg/dL (2.2 mmol/L): Bơm tĩnh mạch chậm Glucose 30% 1 - 2 mL/kg (hoặc Glucose 10% 2 - 5 mL/kg ở trẻ em), sau đó duy trì truyền Glucose 5% hoặc 10%.',
        drugs: [
          {
            genericName: 'Glucose 30% / Glucose 10%',
            route: 'IV',
            loadingDose: '1 - 2 mL/kg Glucose 30% IV bolus',
            maintenanceDose: 'Duy trì Glucose 5% - 10% theo đường huyết mao mạch',
            clinicalNotes: 'KST Sốt rét tiêu thụ glucose mạnh kết hợp với suy gan và thuốc gây hạ đường huyết tái phát thường xuyên.',
          },
        ],
        flowchartNodeType: 'action',
      },
      {
        stepId: 'step_3_refractory_renal_crrt',
        order: 3,
        phase: 'refractory',
        title: '3. Xử Trí Suy Thận Cấp, Đái Huyết Cầu Tố & Lọc Máu Cấp Cứu',
        timeframe: 'Khi có biến chứng suy tạng',
        description: 'Theo dõi thể tích nước tiểu từng giờ. Nếu bệnh nhân vô niệu/thiểu niệu, Creatinine tăng vọt hoặc toan chuyển hóa nặng (pH < 7.2): Khẩn cấp tiến hành Lọc máu liên tục (CRRT) hoặc Chạy thận nhân tạo ngắt quãng (IHD). Truyền máu khi Hb < 7 g/dL.',
        isAlert: true,
        flowchartNodeType: 'alert',
      },
      {
        stepId: 'step_4_oral_act_course',
        order: 4,
        phase: 'recovery',
        title: '4. Chuyển Đổi Sang Thuốc ACT Đường Uống Đủ Liệu Trình 3 Ngày',
        timeframe: 'Khi bệnh nhân tỉnh táo và uống được',
        description: 'Sau khi tiêm Artesunate ít nhất 24 giờ (tối thiểu 3 liều) và bệnh nhân dung nạp được đường uống: Chuyển sang uống 1 đợt thuốc ACT phối hợp đầy đủ 3 ngày (Dihydroartemisinin - Piperaquine hoặc Artemether - Lumefantrine).',
        drugs: [
          {
            genericName: 'Dihydroartemisinin + Piperaquine phosphate',
            tradeNames: ['Arterakine', 'CV Artecan'],
            route: 'PO',
            maintenanceDose: 'Uống đủ liều chuẩn theo cân nặng x 1 lần/ngày trong 3 ngày liên tiếp',
            clinicalNotes: 'Bắt buộc uống đủ 3 ngày để diệt sạch ký sinh trùng thể phân liệt còn sót lại, chống tái phát và kháng thuốc.',
          },
        ],
        flowchartNodeType: 'stable',
      },
    ],
    contraindications: [
      {
        conflictWithCondition: 'Sốt rét ác tính có toan chuyển hóa hoặc suy thận cấp',
        forbiddenDrugOrAction: 'Bù dịch ồ ạt quá mức (> 30-40 mL/kg/ngày)',
        dangerLevel: 'absolute',
        explanation: 'Thành mạch phổi trong sốt rét nặng bị tổn thương tính thấm nặng nề, bù dịch quá nhiều sẽ kích hoạt Phù phổi cấp tổn thương (ARDS) không do tim với tỷ lệ tử vong > 80%.',
        recommendation: 'Chỉ bù dịch duy trì thận trọng, duy trì CVP thấp (3-5 cmH2O), theo dõi sát nhịp thở và nghe phổi.',
      },
    ],
    sharedDecisionOptions: [
      {
        optionName: 'Phương án 1: Artesunate Đường Tĩnh Mạch (Khuyến nghị đầu tay tuyệt đối theo WHO/BYT)',
        approachType: 'standard-invasive',
        pros: [
          'Giảm 35% tỷ lệ tử vong ở người lớn và giảm 22% ở trẻ em so với Quinine tiêm mạch.',
          'Diệt ký sinh trùng nhanh hơn, ít tác dụng phụ hạ đường huyết và độc tính tim mạch hơn Quinine.',
        ],
        cons: [
          'Cần theo dõi nguy cơ thiếu máu tán huyết muộn sau điều trị (Post-artesunate delayed hemolysis) vào tuần thứ 2 - 4.',
        ],
        estimatedCost: 'low',
        suitableFor: 'Mọi bệnh nhân sốt rét nặng/sốt rét ác tính.',
      },
    ],
    infectiousDetails: {
      diseaseDayPhase: 'Giai đoạn cấp tính kịch phát (Cần Artesunate IV ngay) -> Giai đoạn lui bệnh (Chuyển ACT uống 3 ngày)',
      hctPlateletKinetic: 'Theo dõi KST máu và Hb mỗi 12-24h cho đến khi lam máu âm tính liên tiếp 2 lần.',
      antimicrobialStewardship: 'Artesunate IV -> Dihydroartemisinin-Piperaquine uống 3 ngày. Phối hợp Primaquine liều duy nhất để diệt giao bào P. falciparum ngăn lây truyền.',
      isolationPrecautions: 'Nằm mùng chống muỗi Anopheles đốt truyền bệnh.',
    },
    dischargeCriteria: [
      'Lam máu nhuộm Giemsa âm tính với KST sốt rét liên tiếp 2 ngày.',
      'Tỉnh táo hoàn toàn, ăn uống tốt, hết sốt.',
      'Đã hoàn thành đủ liệu trình thuốc ACT đường uống 3 ngày.',
    ],
    updatedAt: '2026-08-22',
  },
];
