/**
 * CliniPortal 2.0 — Kho Guidelines Static Metadata Registry
 * Path: src/content/ebm/guidelines/kho-guidelines-registry.ts
 *
 * Cung cấp metadata phân loại chi tiết (Design, Specialty, Impact, ICD-10, ConditionKey)
 * cho toàn bộ tài liệu lâm sàng trong thư mục kho-guidelines/
 * Dùng làm nguồn dữ liệu EBM cơ sở cho SOAP & Tra cứu EBM nhanh.
 */

import { Study } from './guidelines-types';

export const KHO_GUIDELINES_STATIC: Study[] = [
  // --- TIM MẠCH & CHUYỂN HÓA (CARDIO / METABOLIC) ---
  {
    id: '2024-esc-af',
    title: 'ESC 2024 Guidelines: Chẩn đoán và Quản lý Rung nhĩ (AF)',
    titleEn: '2024 ESC Guidelines for the management of atrial fibrillation',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2024,
    organization: 'Hội Tim mạch Châu Âu (ESC)',
    journal: 'Eur Heart J',
    file: '2024-esc-atrial-fibrillation.html',
    conditionKey: 'af',
    icd10: ['I48', 'I48.0', 'I48.9'],
    intervention: 'Chiến lược CARE (Comorbidity, Avoid stroke/DOAC, Reduce symptoms, Evaluate/Monitor), Kháng đông DOAC, Kiểm soát nhịp/tần số',
    primaryEndpoint: 'Giảm đột quỵ thiếu máu não, tử vong tim mạch, cải thiện chất lượng sống',
    summary: 'Khuyến cáo thực hành toàn diện về rung nhĩ: Phân tầng CHA2DS2-VA (bỏ giới tính), ưu tiên DOAC hơn VKA, chỉ định triệt đốt catheter sớm, quản lý bệnh đồng mắc tích cực.',
    detailedConclusion: 'Áp dụng đường dẫn AF-CARE: Kiểm soát yếu tố nguy cơ tim mạch, kháng đông đường uống DOAC cho hầu hết bệnh nhân có điểm nguy cơ, kiểm soát tần số tim < 110 bpm lúc nghỉ.'
  },
  {
    id: '2025-aha-acc-hypertension',
    title: 'AHA/ACC 2025: Hướng dẫn Quản lý và Điều trị Tăng huyết áp Toàn diện',
    titleEn: '2025 AHA/ACC/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2025,
    organization: 'AHA/ACC',
    journal: 'Circulation',
    file: '2025-aha-acc-hypertension.html',
    conditionKey: 'hypertension',
    icd10: ['I10', 'I11', 'I15'],
    intervention: 'Phối hợp thuốc hạ áp liều cố định sớm (SPC: ACEi/ARB + CCB/Thiazide-like), mục tiêu HA < 130/80 mmHg, lối sống DASH',
    primaryEndpoint: 'Giảm biến cố tim mạch chính (MACE), tử vong tim mạch, đột quỵ và suy thận',
    summary: 'Ngưỡng chẩn đoán THA ≥ 130/80 mmHg. Khởi trị phối hợp đôi (Single Pill Combination) ngay từ độ 1 có nguy cơ hoặc độ 2. Tối ưu hóa hạ áp ban đêm.',
    detailedConclusion: 'Mục tiêu chung < 130/80 mmHg cho đa số bệnh nhân; ưu tiên dạng viên phối hợp liều cố định để tăng tuân thủ; theo dõi HA tại nhà (HBPM).'
  },
  {
    id: '2015-nejm-empareg-outcome',
    title: 'EMPA-REG OUTCOME: Thử nghiệm lâm sàng Empagliflozin trên biến cố tim mạch ở BN ĐTĐ típ 2',
    titleEn: 'Empagliflozin, Cardiovascular Outcomes, and Mortality in Type 2 Diabetes',
    sourceType: 'intl-study',
    specialty: 'cardio',
    design: 'rct',
    impact: 'practice-changing',
    year: 2015,
    organization: 'Boehringer Ingelheim & Eli Lilly / NEJM',
    journal: 'N Engl J Med',
    file: '2015-nejm-empareg-outcome.html',
    conditionKey: 'heart-failure',
    icd10: ['E11', 'I50', 'I25'],
    intervention: 'Empagliflozin 10mg hoặc 25mg/ngày vs Placebo trên nền điều trị chuẩn',
    primaryEndpoint: '3-point MACE (Tử vong do tim mạch, nhồi máu cơ tim không tử vong, đột quỵ không tử vong)',
    keyResults: 'Giảm 14% 3-point MACE (HR 0.86, p=0.04), giảm 38% tử vong tim mạch (HR 0.62, p<0.001), giảm 35% nhập viện vì suy tim (HR 0.65, p=0.002).',
    summary: 'Cột mốc lịch sử mở ra kỷ nguyên SGLT2i trong bảo vệ tim mạch - thận bất kể tình trạng kiểm soát đường huyết.',
    detailedConclusion: 'SGLT2i là trụ cột bắt buộc ở bệnh nhân ĐTĐ típ 2 kèm bệnh tim mạch xơ vữa hoặc suy tim nhằm giảm tử vong và nhập viện.'
  },
  {
    id: '2026-aha-acc-ckm',
    title: 'AHA/ACC 2026: Hội chứng Tim mạch - Thận - Chuyển hóa (CKM Syndrome)',
    titleEn: 'Cardiovascular-Kidney-Metabolic (CKM) Syndrome: A Presidential Advisory',
    sourceType: 'intl-guideline',
    specialty: 'cardio',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'American Heart Association (AHA)',
    journal: 'Circulation',
    file: '2026-aha-acc-ckm-syndrome.html',
    conditionKey: 'cad',
    icd10: ['E11', 'I50', 'N18', 'E66'],
    intervention: 'Phân tầng 5 giai đoạn CKM (Giai đoạn 0-4), đa trị liệu sớm SGLT2i, GLP-1RA, Finerenone, Statin, ức chế RAAS',
    primaryEndpoint: 'Phòng ngừa tiến triển suy tim, suy thận giai đoạn cuối và tử vong tim mạch',
    summary: 'Khung tiếp cận hợp nhất sức khỏe tim mạch, thận và chuyển hóa; sàng lọc eGFR + UACR định kỳ; cá thể hóa can thiệp theo giai đoạn CKM.',
    detailedConclusion: 'Tích hợp SGLT2i và GLP-1RA/nsMRA từ sớm ở giai đoạn 2 và 3 để làm chậm suy thoái cơ quan đích.'
  },
  {
    id: '2026-jcva-soc-tim',
    title: 'JCVA 2026: Hồi sức và Tiếp cận Sốc tim (Cardiogenic Shock) Đa mô thức',
    titleEn: 'Multidisciplinary Management of Cardiogenic Shock in the Modern Era',
    sourceType: 'intl-guideline',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Society of Cardiovascular Anesthesiologists',
    journal: 'Intensive Care Med',
    file: '2026-jcva-soc-tim.html',
    conditionKey: 'heart-failure',
    icd10: ['R57.0', 'I50', 'I21'],
    intervention: 'Phân loại SCAI shock stage A-E, theo dõi PAC/huyết động xâm lấn, can thiệp MCS (ECMO, Impella, IABP) sớm',
    primaryEndpoint: 'Sống còn 30 ngày, phục hồi tưới máu mô và chức năng thất',
    summary: 'Nhấn mạnh kích hoạt Shock Team nhanh chóng, phân loại SCAI, hồi sức thuốc vận mạch/tăng co bóp có định hướng huyết động (Norepinephrine + Dobutamine/Milrinone).',
    detailedConclusion: 'Hạ lactate, duy trì MAP ≥ 65 mmHg, cân nhắc hỗ trợ tuần hoàn cơ học (MCS) sớm trước khi suy đa tạng không hồi phục.'
  },
  {
    id: '2026-dash-diet-hypertension',
    title: 'Tổng quan Chế độ ăn DASH và Can thiệp Lối sống trong Kiểm soát Huyết áp',
    titleEn: 'DASH Dietary Pattern and Lifestyle Modifications for Blood Pressure Control',
    sourceType: 'intl-study',
    specialty: 'cardio',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'AHA / NHLBI',
    journal: 'Circulation',
    file: '2026-dash-diet-hypertension.html',
    conditionKey: 'hypertension',
    icd10: ['I10', 'E66'],
    intervention: 'Chế độ ăn giàu rau quả, kali, giảm natri (< 2300mg/ngày, tối ưu < 1500mg/ngày), hạn chế rượu bia',
    primaryEndpoint: 'Mức giảm HA tâm thu và tâm trương',
    summary: 'Chế độ ăn DASH kết hợp giảm muối giúp giảm huyết áp tâm thu 8-14 mmHg, tương đương hiệu quả của 1 loại thuốc hạ áp đơn trị liệu.',
    detailedConclusion: 'Khuyến cáo áp dụng cho mọi giai đoạn THA và tiền THA.'
  },
  {
    id: '2026-nejm-ngat',
    title: 'NEJM 2026: Tiếp cận và Phân tầng Nguy cơ Ngất (Syncope) tại Cấp cứu',
    titleEn: 'Evaluation and Management of Syncope in the Emergency Department',
    sourceType: 'intl-study',
    specialty: 'cardio',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'NEJM Review Article',
    journal: 'N Engl J Med',
    file: '2026-nejm-ngat.html',
    conditionKey: 'cad',
    icd10: ['R55', 'I45', 'I49'],
    intervention: 'Phân tầng nguy cơ cao (Red flags ECG/lâm sàng), siêu âm tim, theo dõi Holter, nghiệm pháp bàn nghiêng',
    primaryEndpoint: 'Phát hiện nguyên nhân tim mạch đe dọa tính mạng (loạn nhịp, hẹp van nặng, bệnh cơ tim)',
    summary: 'Quy trình tiếp cận ngất tại khoa cấp cứu: Phân biệt ngất do phản xạ, hạ HA tư thế và ngất do nguyên nhân tim mạch; tiêu chí chỉ định nhập viện an toàn.',
    detailedConclusion: 'Bệnh nhân có cờ đỏ tim mạch hoặc bất thường ECG cần nhập viện theo dõi telemetry và làm siêu âm tim khẩn.'
  },

  // --- HÔ HẤP & BỆNH PHỔI (PULMONOLOGY) ---
  {
    id: '2026-byt-viem-phoi-cong-dong',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Viêm phổi Mắc phải Cộng đồng ở Người lớn',
    titleEn: 'National Guidelines on Management of Community-Acquired Pneumonia in Adults',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-viem-phoi-cong-dong.html',
    conditionKey: 'pneumonia',
    icd10: ['J18', 'J18.9', 'J15', 'J13'],
    intervention: 'Phân tầng CURB-65 / CRB-65 / PSI, phác đồ kháng sinh kinh nghiệm (Amoxicillin/Clavulanate + Macrolide hoặc FQ hô hấp), cấy vi sinh',
    primaryEndpoint: 'Tỷ lệ lui bệnh lâm sàng, hạ sốt, giảm tỷ lệ tử vong và biến chứng SHH',
    summary: 'Hướng dẫn chuẩn quốc gia về CAP: Chỉ định nhập viện ngoại trú/nội trú/ICU theo CURB-65, thời điểm chuyển kháng sinh uống, quản lý CAP nặng kèm cờ đỏ.',
    detailedConclusion: 'Bệnh nhân ngoại trú: Beta-lactam phối hợp Macrolide hoặc Doxycycline; nội trú thường: Beta-lactam tiêm + Macrolide/FQ; ICU: Beta-lactam phổ rộng + FQ/Macrolide ± Kháng MRSA/Pseudomonas nếu có yếu tố nguy cơ.'
  },
  {
    id: '2026-byt-copd',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Bệnh phổi Tắc nghẽn Mạn tính (COPD)',
    titleEn: 'National Guidelines on Management of Chronic Obstructive Pulmonary Disease',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-copd.html',
    conditionKey: 'copd',
    icd10: ['J44', 'J44.0', 'J44.1', 'J44.9'],
    intervention: 'Phân nhóm GOLD ABE, đo chức năng thông khí (FEV1/FVC < 0.70 sau test giãn phế quản), điều trị bộ ba LAMA+LABA+ICS, xử trí đợt cấp (SABA/SAMA + Corticosteroid toàn thân + Kháng sinh)',
    primaryEndpoint: 'Giảm đợt cấp, bảo tồn chức năng phổi, giảm tử vong',
    summary: 'Cập nhật GOLD ABE, vai trò đếm bạch cầu ái toan máu (Eosinophils) định hướng chỉ định ICS, kỹ thuật hít dụng cụ và phục hồi chức năng hô hấp.',
    detailedConclusion: 'Đợt cấp COPD: Khí dung SABA+SAMA, Prednisolone 40mg/ngày x 5 ngày, kháng sinh khi có đủ 3 triệu chứng Anthonisen hoặc cần thở máy.'
  },
  {
    id: '2026-gina-asthma',
    title: 'GINA 2026: Chiến lược Toàn cầu về Quản lý và Phòng ngừa Hen suyễn (Asthma)',
    titleEn: 'Global Strategy for Asthma Management and Prevention (GINA 2026)',
    sourceType: 'intl-guideline',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Global Initiative for Asthma (GINA)',
    journal: 'Eur Respir J',
    file: '2026-gina-asthma.html',
    conditionKey: 'asthma',
    icd10: ['J45', 'J45.0', 'J45.9'],
    intervention: 'Đường dẫn 1 (Ưu tiên): ICS-Formoterol cắt cơn và duy trì (MART); Đường dẫn 2: SABA cắt cơn + ICS duy trì; Liệu pháp sinh học cho hen nặng',
    primaryEndpoint: 'Kiểm soát triệu chứng, ngăn ngừa cơn kịch phát hen nặng và tử vong',
    summary: 'GINA nhấn mạnh KHÔNG sử dụng SABA đơn độc. Lựa chọn ưu tiên là ICS-Formoterol liều thấp khi cần ở bậc 1-2 và duy trì/cắt cơn ở bậc 3-5.',
    detailedConclusion: 'Mọi bệnh nhân hen đều cần điều trị chứa ICS để kiểm soát tình trạng viêm mạn tính phế quản.'
  },
  {
    id: '2026-jrs-copd',
    title: 'JRS 2026: Hướng dẫn Quản lý COPD Hội Hô hấp Nhật Bản',
    titleEn: 'Japanese Respiratory Society Guidelines for the Management of COPD 2026',
    sourceType: 'intl-guideline',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'informative',
    year: 2026,
    organization: 'Japanese Respiratory Society (JRS)',
    journal: 'Eur Respir J',
    file: '2026-jrs-copd.html',
    conditionKey: 'copd',
    icd10: ['J44'],
    intervention: 'LAMA/LABA phối hợp sớm, đặc thù cá thể hóa trên quần thể người cao tuổi và thể trạng người Châu Á',
    primaryEndpoint: 'Chất lượng cuộc sống, ngăn ngừa suy giảm khối cơ (sarcopenia) và đợt cấp',
    summary: 'Nhấn mạnh dinh dưỡng, phục hồi chức năng và tiếp cận đặc thù trên bệnh nhân COPD cao tuổi Châu Á.',
    detailedConclusion: 'Tối ưu thuốc giãn phế quản tác dụng kéo dài kép (LAMA/LABA) kết hợp can thiệp thể chất đa phương diện.'
  },
  {
    id: '2023-byt-benh-phoi-mo-ke',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị Bệnh phổi Mô kẽ (ILD)',
    titleEn: 'National Guidelines on Interstitial Lung Disease Diagnosis and Treatment',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-benh-phoi-mo-ke.html',
    conditionKey: 'interstitial-lung',
    icd10: ['J84', 'J84.1', 'J84.9'],
    intervention: 'HRCT lồng ngực độ phân giải cao, thảo luận đa chuyên khoa (MDD), thuốc chống xơ (Nintedanib, Pirfenidone), ức chế miễn dịch cho CTD-ILD',
    primaryEndpoint: 'Làm chậm tốc độ suy giảm dung tích sống gắng sức (FVC), giảm đợt cấp',
    summary: 'Tiếp cận chẩn đoán phân biệt ILD tự phát (IPF), bệnh phổi kẽ liên quan bệnh mô liên kết (CTD-ILD), viêm phổi quá mẫn (HP).',
    detailedConclusion: 'Chỉ định thuốc chống xơ hóa phổi sớm cho bệnh nhân xơ phổi tiến triển (PPF).'
  },
  {
    id: '2024-byt-lao-p1',
    title: 'BYT 2024 (Phần 1): Hướng dẫn Chẩn đoán và Điều trị Bệnh Lao Nhạy cảm',
    titleEn: 'National Guidelines for the Diagnosis and Treatment of Tuberculosis (Part 1: Drug-Susceptible TB)',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam / Chương trình Chống Lao Quốc gia',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-lao-p1.html',
    conditionKey: 'tb',
    icd10: ['A15', 'A16'],
    intervention: 'GeneXpert MTB/RIF, Phác đồ A1 (2RHZE/4RHE) ở người lớn, phác đồ điều trị lao tiềm ẩn (TPT)',
    primaryEndpoint: 'Tỷ lệ khỏi bệnh, âm hóa đờm, phòng ngừa lây nhiễm cộng đồng',
    summary: 'Chuẩn quốc gia về chẩn đoán lao bằng sinh học phân tử nhanh, theo dõi độc tính thuốc kháng lao (men gan, axit uric, thị lực).',
    detailedConclusion: 'Tuân thủ nghiêm ngặt điều trị có kiểm soát trực tiếp (DOTS) đủ liệu trình 6 tháng.'
  },
  {
    id: '2024-byt-lao-p2',
    title: 'BYT 2024 (Phần 2): Hướng dẫn Chẩn đoán và Điều trị Lao Kháng thuốc (DR-TB)',
    titleEn: 'National Guidelines for the Diagnosis and Treatment of Drug-Resistant Tuberculosis (Part 2)',
    sourceType: 'vn-moh',
    specialty: 'pulmo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-lao-p2.html',
    conditionKey: 'tb',
    icd10: ['A15', 'Z16.24'],
    intervention: 'Phác đồ BPaL / BPaLM (Bedaquiline, Pretomanid, Linezolid ± Moxifloxacin) đường uống ngắn hạn 6 tháng',
    primaryEndpoint: 'Tỷ lệ thành công điều trị MDR/RR-TB, giảm tác dụng phụ so với phác đồ dài hạn',
    summary: 'Bước đột phá áp dụng phác đồ toàn thuốc uống ngắn hạn cho lao đa kháng và siêu kháng thuốc.',
    detailedConclusion: 'Theo dõi sát ECG (QTc) khi dùng Bedaquiline và công thức máu (Linezolid).'
  },

  // --- HỒI SỨC CẤP CỨU & NHIỄM TRÙNG NẶNG (ICU / CRITICAL CARE) ---
  {
    id: '2026-ssc-sepsis',
    title: 'Surviving Sepsis Campaign (SSC) 2026: Hướng dẫn Quốc tế Xử trí Nhiễm khuẩn huyết & Sốc nhiễm khuẩn',
    titleEn: 'Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2026',
    sourceType: 'intl-guideline',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'SCCM / ESICM (Surviving Sepsis Campaign)',
    journal: 'Crit Care Med',
    file: '2026-ssc-sepsis.html',
    conditionKey: 'icu',
    icd10: ['A41', 'R65.2', 'R57.2'],
    intervention: 'Gói 1 giờ (Hour-1 Bundle): Đo Lactate, cấy máu trước KS, KS phổ rộng trong 1h đầu, truyền dịch tinh thể 30ml/kg trong 3h, Norepinephrine vận mạch duy trì MAP ≥ 65 mmHg',
    primaryEndpoint: 'Giảm tỷ lệ tử vong nội viện 28 ngày và suy đa tạng',
    summary: 'Cập nhật tiêu chuẩn Sepsis-3, cá thể hóa truyền dịch bằng các chỉ số động đáp ứng bù dịch (PLR, PPV, siêu âm Vena Cava), kiểm soát ổ nhiễm (Source control).',
    detailedConclusion: 'Bắt đầu kháng sinh phổ rộng ngay trong giờ đầu tiên. Bù dịch có kiểm soát và dùng Norepinephrine sớm qua catheter ngoại vi an toàn nếu chưa có CVC.'
  },
  {
    id: '2021-ssc-soc-nhiem-khuan',
    title: 'SSC 2021: Tóm tắt Khuyến cáo Sốc nhiễm khuẩn và Hồi sức Huyết động',
    titleEn: 'Surviving Sepsis Campaign 2021 Guidelines Summary',
    sourceType: 'intl-guideline',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2021,
    organization: 'SCCM / ESICM',
    journal: 'Crit Care Med',
    file: '2021-ssc-soc-nhiem-khuan-sepsis3.html',
    conditionKey: 'icu',
    icd10: ['A41.9', 'R57.2'],
    intervention: 'Hồi sức dịch ban đầu, Vasopressin liều cố định 0.03 U/min phối hợp Norepinephrine, Hydrocortisone liều sinh lý nếu sốc kháng trị',
    primaryEndpoint: 'Tử vong 28 ngày',
    summary: 'Khuyến cáo nền tảng về phác đồ phối hợp vận mạch và hồi sức thể tích tuần hoàn.',
    detailedConclusion: 'Tránh quá tải dịch sau giai đoạn hồi sức ban đầu; hạ bậc kháng sinh (de-escalation) theo kết quả vi sinh.'
  },
  {
    id: '2016-jama-sepsis-3',
    title: 'JAMA 2016: Đồng thuận Quốc tế Định nghĩa Nhiễm khuẩn huyết và Sốc nhiễm khuẩn (Sepsis-3)',
    titleEn: 'The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2016,
    organization: 'SCCM / ESICM Taskforce',
    journal: 'JAMA',
    file: '2016-jama-sepsis-3-consensus.html',
    conditionKey: 'icu',
    icd10: ['A41', 'R65.2'],
    intervention: 'Thang điểm SOFA (tăng ≥ 2 điểm xác định Sepsis), sàng lọc nhanh bằng qSOFA tại khoa phòng thường',
    primaryEndpoint: 'Độ chính xác dự báo tử vong nội viện',
    summary: 'Định nghĩa lại Sepsis là rối loạn chức năng cơ quan đe dọa tính mạng do đáp ứng mất điều hòa của cơ thể với nhiễm trùng.',
    detailedConclusion: 'Bỏ tiêu chuẩn SIRS trong định nghĩa Sepsis; sử dụng SOFA score để đánh giá mức độ tổn thương cơ quan đích.'
  },
  {
    id: '2026-byt-nhap-vien-cap-cuu',
    title: 'BYT 2026: Hướng dẫn Tiêu chuẩn Phân loại & Chỉ định Nhập viện Cấp cứu',
    titleEn: 'National Emergency Triage and Admission Indication Criteria',
    sourceType: 'vn-moh',
    specialty: 'icu',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-chi-dinh-nhap-vien-cap-cuu.html',
    conditionKey: 'icu',
    icd10: ['R68.8', 'Z03.8'],
    intervention: 'Phân loại tam giác cấp cứu (Emergency Triage), dấu hiệu sinh tồn bất thường (NEWS2), tiêu chuẩn chuyển khoa ICU/HDU/nội trú',
    primaryEndpoint: 'An toàn người bệnh, giảm tử vong tránh được tại phòng cấp cứu',
    summary: 'Văn bản quy chuẩn phân loại độ ưu tiên cấp cứu cấp quốc gia, cờ đỏ lâm sàng bắt buộc nhập viện cấp cứu nội khoa và hồi sức.',
    detailedConclusion: 'Bắt buộc rà soát các dấu hiệu đe dọa tính mạng (đường thở, hô hấp, tuần hoàn, ý thức) trước khi quyết định xử trí ngoại trú.'
  },
  {
    id: '2026-icu-khang-sinh-bn-nang',
    title: 'Chiến lược Dược động học/Dược lực học (PK/PD) Kháng sinh cho Bệnh nhân Nặng tại ICU',
    titleEn: 'PK/PD Optimization of Antibiotics in Critically Ill Patients',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'practice-changing',
    year: 2026,
    organization: 'ESICM Critical Care Review',
    journal: 'Intensive Care Med',
    file: '2026-icu-khang-sinh-cho-bn-nang.html',
    conditionKey: 'icu',
    icd10: ['A41', 'Z16'],
    intervention: 'Liều nạp (Loading dose), truyền kéo dài / truyền liên tục Beta-lactam, theo dõi nồng độ thuốc trị liệu (TDM)',
    primaryEndpoint: 'Đạt mục tiêu PK/PD (100% fT > MIC hoặc fT > 4xMIC), tăng tỷ lệ diệt khuẩn',
    summary: 'Xử lý biến đổi thể tích phân bố (Vd) tăng và độ thanh thải thận tăng (ARC) ở bệnh nhân sốc nhiễm khuẩn hồi sức.',
    detailedConclusion: 'Luôn dùng liều nạp đầy đủ trong 24h đầu bất kể chức năng thận; truyền kéo dài 3-4h cho Beta-lactam để tối ưu hiệu quả.'
  },
  {
    id: '2026-icu-ca-the-hoa-beta-lactam',
    title: 'Cá thể hóa Liều Beta-lactam và Phối hợp Kháng sinh theo Hướng dẫn IDSA/ESCMID',
    titleEn: 'Personalized Beta-Lactam Dosing Strategies in the ICU',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'ESCMID / ESICM',
    journal: 'Lancet Infect Dis',
    file: '2026-icu-ca-the-hoa-beta-lactam.html',
    conditionKey: 'icu',
    icd10: ['A41', 'Z16'],
    intervention: 'Phối hợp Colistin, Meropenem, Ceftazidime/Avibactam, Piperacillin/Tazobactam liều cá thể hóa',
    primaryEndpoint: 'Kiểm soát nhiễm khuẩn đa kháng (CRKP, CRAB, CRPA)',
    summary: 'Tối ưu phác đồ kháng sinh chống vi khuẩn Gram âm đa kháng đường ruột và không lên men tại khoa hồi sức.',
    detailedConclusion: 'Kết hợp TDM và phương pháp truyền liên tục để đạt nồng độ mục tiêu không gây độc thận.'
  },
  {
    id: '2026-icm-namsap-ards',
    title: 'ICM 2026: Thông khí Nằm sấp và Chiến lược Bảo vệ Phổi trong ARDS Nặng',
    titleEn: 'Prone Positioning and Lung-Protective Ventilation in Moderate-to-Severe ARDS',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'practice-changing',
    year: 2026,
    organization: 'European Society of Intensive Care Medicine (ESICM)',
    journal: 'Intensive Care Med',
    file: '2026-icm-namsap-ards.html',
    conditionKey: 'pneumonia',
    icd10: ['J80', 'J96.0'],
    intervention: 'Thông khí nằm sấp ≥ 16 giờ/ngày, thể tích khí lưu thông thấp (Vt 4-6 ml/kg PBW), Pplat < 30 cmH2O, Driving pressure < 14 cmH2O',
    primaryEndpoint: 'Giảm tỷ lệ tử vong 28 ngày và 90 ngày ở bệnh nhân ARDS có PaO2/FiO2 < 150',
    summary: 'Can thiệp nằm sấp sớm giúp đồng đều thông khí - tưới máu phổi, mở các phế nang xẹp vùng lưng và cải thiện sống còn rõ rệt.',
    detailedConclusion: 'Bắt đầu nằm sấp sớm trong vòng 24-48 giờ đầu ở ARDS từ vừa đến nặng có chỉ định.'
  },
  {
    id: '2026-mbm-tongquan-ards',
    title: 'Tổng quan Tiếp cận Chẩn đoán và Điều trị Suy hô hấp Cấp tiến triển (ARDS)',
    titleEn: 'Clinical Review: Diagnosis and Modern Phenotyping of ARDS',
    sourceType: 'intl-study',
    specialty: 'icu',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'ATS / ESICM Review',
    journal: 'Am J Respir Crit Care Med',
    file: '2026-mbm-tongquan-ards.html',
    conditionKey: 'pneumonia',
    icd10: ['J80'],
    intervention: 'Định nghĩa Berlin cải biên (Global Definition), phân biệt ARDS dưới kiểu hình viêm cao (Hyperinflammatory) vs viêm thấp',
    primaryEndpoint: 'Tối ưu hóa phác đồ điều trị dịch và PEEP',
    summary: 'Cung cấp cơ sở sinh lý bệnh, vai trò thuốc giãn cơ ngắn ngày, huy động phế nang và ECMO VV trong ARDS kháng trị.',
    detailedConclusion: 'Kiểm soát hạn chế dịch (Conservative fluid strategy) sau khi đã hồi sức sốc ổn định.'
  },

  // --- NỘI TIẾT & CHUYỂN HÓA (ENDOCRINOLOGY) ---
  {
    id: '2026-ada-diabetes',
    title: 'ADA 2026: Tiêu chuẩn Chăm sóc Y tế trong Bệnh Đái tháo đường (Standards of Care)',
    titleEn: 'Standards of Care in Diabetes—2026 (American Diabetes Association)',
    sourceType: 'intl-guideline',
    specialty: 'endo',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Hiệp hội Đái tháo đường Hoa Kỳ (ADA)',
    journal: 'Diabetes Care',
    file: '2026-ada-diabetes.html',
    conditionKey: 'diabetes-t2d',
    icd10: ['E11', 'E11.9', 'E10', 'E11.2'],
    intervention: 'Mục tiêu HbA1c < 7.0% (cá thể hóa 6.5-8.0%), SGLT2i và GLP-1RA độc lập với HbA1c cho BN có ASCVD/HF/CKD, Tirzepatide (GIP/GLP-1 RA) kép',
    primaryEndpoint: 'Bảo vệ tim thận mạch, giảm cân, phòng ngừa biến chứng vi mạch và mạch máu lớn',
    summary: 'Khuyến cáo kim chỉ nam toàn cầu về ĐTĐ: Ưu tiên bảo vệ cơ quan đích (Tim - Thận - Cân nặng) song hành cùng kiểm soát đường huyết.',
    detailedConclusion: 'Bệnh nhân ĐTĐ típ 2 có nguy cơ tim mạch cao hoặc suy tim/bệnh thận: Bắt buộc chỉ định SGLT2i và/hoặc GLP-1RA không phụ thuộc HbA1c nền.'
  },
  {
    id: '2025-byt-than-kinh-dtđ',
    title: 'BYT 2025: Hướng dẫn Chẩn đoán và Điều trị Biến chứng Thần kinh Đái tháo đường',
    titleEn: 'National Guidelines on Diagnosis and Treatment of Diabetic Neuropathy',
    sourceType: 'vn-moh',
    specialty: 'endo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2025-byt-benh-than-kinh-dai-thao-duong.html',
    conditionKey: 'diabetes-t2d',
    icd10: ['E11.4', 'G63.2'],
    intervention: 'Sàng lọc khám bàn chân bằng Monofilament 10g + âm thoa 128Hz, thuốc giảm đau thần kinh (Duloxetine, Pregabalin, Gabapentin), chăm sóc phòng loét',
    primaryEndpoint: 'Giảm đau thần kinh, ngăn ngừa loét bàn chân và đoạn chi',
    summary: 'Quy trình sàng lọc định kỳ bệnh thần kinh ngoại biên và tự chủ ở bệnh nhân ĐTĐ, phân tầng nguy cơ bàn chân đái tháo đường.',
    detailedConclusion: 'Kiểm soát đường huyết chặt chẽ để làm chậm tiến triển tổn thương sợi thần kinh; điều trị đau bằng Duloxetine hoặc Pregabalin liều tăng dần.'
  },
  {
    id: '2026-jcem-bao-giap',
    title: 'JCEM 2026: Hướng dẫn Chẩn đoán và Xử trí Cấp cứu Bão giáp (Thyroid Storm)',
    titleEn: 'Emergency Management and Contemporary Diagnosis of Thyroid Storm',
    sourceType: 'intl-guideline',
    specialty: 'endo',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Endocrine Society / ATA',
    journal: 'JCEM',
    file: '2026-jcem-bao-giap.html',
    conditionKey: 'thyroid',
    icd10: ['E05.5', 'E05.0'],
    intervention: 'Thang điểm Burch-Wartofsky (BWPS ≥ 45 điểm), Phác đồ 5 bước: Kháng giáp tổng hợp (PTU/Thiamazole) -> Iod vô cơ (Lugol) sau 1h -> Chẹn beta (Propranolol) -> Corticosteroid (Hydrocortisone) -> Hạ nhiệt/Hỗ trợ',
    primaryEndpoint: 'Cắt đứt cơn bão giáp, ổn định huyết động và nhịp tim, giảm tử vong',
    summary: 'Cấp cứu nội tiết tối khẩn: Phối hợp đồng thời phong bế tổng hợp hormone giáp, ức chế giải phóng hormone mới, chẹn thụ thể giao cảm và ức chế chuyển T4 thành T3.',
    detailedConclusion: 'Không bao giờ cho Iod trước thuốc kháng giáp tổng hợp (tránh hiệu ứng Jod-Basedow). Dùng Hydrocortisone để phòng ngừa suy thượng thận cấp tương đối.'
  },
  {
    id: '2020-nutrients-lowcarb-vs-lowfat',
    title: 'Nghiên cứu So sánh Chế độ ăn Low-Carb vs Low-Fat trong Giảm cân và Kiểm soát Chuyển hóa',
    titleEn: 'Effects of Low-Carbohydrate vs Low-Fat Diets on Metabolic Parameters and Weight Loss',
    sourceType: 'intl-study',
    specialty: 'nutri',
    design: 'meta',
    impact: 'informative',
    year: 2020,
    organization: 'Nutrients Meta-Analysis',
    journal: 'Nat Med',
    file: '2020-nutrients-lowcarb-vs-lowfat.html',
    conditionKey: 'obesity',
    icd10: ['E66', 'E11'],
    intervention: 'Chế độ ăn giảm Carbohydrate (< 50-130g/ngày) vs Giảm chất béo (< 30% tổng năng lượng)',
    primaryEndpoint: 'Mức giảm cân nặng, HbA1c, Triglyceride và cải thiện nhạy cảm Insulin',
    summary: 'Chế độ ăn Low-Carb cho thấy ưu thế vượt trội trong 6 tháng đầu về giảm cân nhanh và kiểm soát đường huyết sau ăn, sau 12 tháng phụ thuộc chủ yếu vào mức độ tuân thủ năng lượng nạp vào.',
    detailedConclusion: 'Cá thể hóa chế độ ăn dựa trên sự ưa thích và khả năng duy trì lâu dài của bệnh nhân.'
  },

  // --- THẬN HỌC & TIẾT NIỆU (NEPHROLOGY) ---
  {
    id: '2024-kdigo-ckd',
    title: 'KDIGO 2024: Hướng dẫn Lâm sàng Thực hành Đánh giá & Quản lý Bệnh Thận Mạn (CKD)',
    titleEn: 'KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease',
    sourceType: 'intl-guideline',
    specialty: 'renal',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2024,
    organization: 'Kidney Disease: Improving Global Outcomes (KDIGO)',
    journal: 'Kidney Int',
    file: '2024-kdigo-ckd.html',
    conditionKey: 'ckd',
    icd10: ['N18', 'N18.3', 'N18.9'],
    intervention: 'Phân loại CGA (Cause, eGFR G1-G5, Albuminuria A1-A3), Trụ cột 4 thuốc bảo vệ thận: ACEi/ARB + SGLT2i + nsMRA (Finerenone) + GLP-1RA / Statin',
    primaryEndpoint: 'Làm chậm tốc độ suy giảm eGFR, giảm biến cố tim mạch và nhu cầu lọc máu',
    summary: 'Định hướng toàn diện mới nhất: Tầm quan trọng của xét nghiệm UACR nước tiểu; SGLT2i là chỉ định nền tảng cho CKD có eGFR ≥ 20 ml/min/1.73m2 bất kể có ĐTĐ hay không.',
    detailedConclusion: 'Duy trì điều trị SGLT2i liên tục cho đến khi bắt đầu lọc máu hoặc ghép thận; chấp nhận eGFR giảm tạm thời < 30% khi khởi đầu ức chế RAAS/SGLT2i.'
  },

  // --- TRUYỀN NHIỄM & VI RÚT & NẤM (INFECTIOUS DISEASES) ---
  {
    id: '2026-idsa-amr',
    title: 'IDSA 2026: Hướng dẫn Điều trị Nhiễm khuẩn Vi khuẩn Gram Âm Kháng thuốc (AMR Guidance)',
    titleEn: 'Infectious Diseases Society of America 2026 Guidance on the Treatment of Antimicrobial-Resistant Gram-Negative Infections',
    sourceType: 'intl-guideline',
    specialty: 'infect',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Hiệp hội Bệnh Truyền nhiễm Hoa Kỳ (IDSA)',
    journal: 'Clin Infect Dis',
    file: '2026-idsa-amr.html',
    conditionKey: 'icu',
    icd10: ['A41', 'Z16'],
    intervention: 'Ceftazidime-avibactam, Meropenem-vaborbactam, Imipenem-relebactam, Cefiderocol cho CRE, DTR-Pseudomonas aeruginosa, CR-Acinetobacter baumannii (Ampicillin-sulbactam liều cao)',
    primaryEndpoint: 'Lui bệnh vi sinh, sống còn 30 ngày',
    summary: 'Cập nhật phân loại enzyme Carbapenemase (KPC, NDM, OXA-48) và phác đồ kháng sinh thế hệ mới tối ưu cho từng loại men kháng.',
    detailedConclusion: 'Nhiễm NDM (Metallo-beta-lactamase): Phối hợp Ceftazidime/Avibactam + Aztreonam để vượt qua cơ chế kháng thuốc.'
  },
  {
    id: '2024-byt-aspergillus-cpa',
    title: 'BYT 2024: Hướng dẫn Chẩn đoán và Điều trị Bệnh Nhiễm Nấm Aspergillus Phổi Mạn tính (CPA)',
    titleEn: 'National Guidelines for the Diagnosis and Treatment of Chronic Pulmonary Aspergillosis',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-aspergillus-cpa.html',
    conditionKey: 'invasive-fungal',
    icd10: ['B44', 'B44.0', 'B44.9'],
    intervention: 'Huyết thanh học kháng thể Aspergillus IgG, CT lồng ngực (hình ảnh lục lạc - Fungus ball/hang), Itraconazole / Voriconazole uống kéo dài ≥ 6 tháng',
    primaryEndpoint: 'Kiểm soát triệu chứng ho ra máu, ngăn phá hủy nhu mô phổi',
    summary: 'Chỉ dẫn chi tiết phân biệt CPA trên nền di chứng lao phổi, chỉ định phẫu thuật cắt thùy phổi khi ho ra máu đe dọa tính mạng.',
    detailedConclusion: 'Kháng nấm đường uống Itraconazole 200mg x 2 lần/ngày (theo dõi nồng độ thuốc TDM) tối thiểu 6 tháng.'
  },
  {
    id: '2023-byt-sot-xuat-huyet',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị Sốt xuất huyết Dengue',
    titleEn: 'National Guidelines on Management of Dengue Hemorrhagic Fever',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-sot-xuat-huyet-dengue.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A90', 'A91'],
    intervention: 'Theo dõi dấu hiệu cảnh báo (Warning signs), theo dõi Hct và tiểu cầu, phác đồ truyền dịch chống sốc theo giờ (Điện giải -> Cao phân tử Dextran/HES)',
    primaryEndpoint: 'Kịp thời phát hiện sốc, tái lập thể tích tuần hoàn, giảm tử vong do sốc thoát huyết tương',
    summary: 'Quy chuẩn phân độ: SXH Dengue, SXH Dengue có dấu hiệu cảnh báo, và SXH Dengue nặng; sơ đồ truyền dịch chi tiết từng giờ.',
    detailedConclusion: 'Chỉ định truyền dịch đúng thời điểm khi có dấu hiệu cảnh báo/sốc, tránh quá tải dịch giai đoạn hồi phục.'
  },
  {
    id: '2023-byt-sot-ret',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị Bệnh Sốt Rét',
    titleEn: 'National Guidelines on Malaria Treatment and Elimination',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-sot-ret.html',
    conditionKey: 'infect',
    icd10: ['B50', 'B51', 'B54'],
    intervention: 'Thuốc Artemisinin phối hợp (ACT: Dihydroartemisinin-Piperaquine, Pyronaridine-Artesunate), Artesunate tiêm tĩnh mạch cho sốt rét ác tính, Primaquine diệt thể giao bào/thể ngủ',
    primaryEndpoint: 'Sạch ký sinh trùng, cắt đứt lây truyền, cứu sống bệnh nhân sốt rét ác tính',
    summary: 'Hướng dẫn điều trị sốt rét thông thường do P. falciparum, P. vivax và xử trí các thể sốt rét ác tính (não, đái huyết cầu tố, suy thận).',
    detailedConclusion: 'Artesunate tiêm TM khẩn cấp cho mọi ca sốt rét nặng ác tính; xét nghiệm G6PD trước khi dùng Primaquine liều cao.'
  },
  {
    id: '2024-byt-tay-chan-mieng',
    title: 'BYT 2024: Hướng dẫn Chẩn đoán và Điều trị Bệnh Tay Chân Miệng (HFMD)',
    titleEn: 'National Guidelines on Hand-Foot-Mouth Disease Management',
    sourceType: 'vn-moh',
    specialty: 'pedia',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-taychanmieng.html',
    conditionKey: 'hfmd',
    icd10: ['B08.4'],
    intervention: 'Phân độ lâm sàng 1, 2a, 2b (nhóm 1, nhóm 2), độ 3, độ 4. Chỉ định Phenobarbital uống/tiêm, IVIG (Immunoglobulin miễn dịch), Milrinone trợ tim hạ áp',
    primaryEndpoint: 'Ngăn ngừa biến chứng viêm não, phù phổi cấp và suy tuần hoàn do EV71',
    summary: 'Nhận biết sớm dấu hiệu giật mình chới với, sốt cao khó hạ, rung giật nhãn cầu để phân độ và điều trị tích cực kịp thời.',
    detailedConclusion: 'Độ 2b nhóm 2 trở lên: Điều trị nội trú phòng cấp cứu/ICU, chỉ định IVIG khi có triệu chứng thần kinh tiến triển.'
  },
  {
    id: '2025-byt-soi',
    title: 'BYT 2025: Hướng dẫn Giám sát, Chẩn đoán và Xử trí Bệnh Sởi (Measles)',
    titleEn: 'National Guidelines on Measles Diagnosis, Treatment and Outbreak Control',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2025-byt-soi.html',
    conditionKey: 'measles',
    icd10: ['B05', 'B05.9'],
    intervention: 'Cách ly hô hấp, bổ sung Vitamin A liều cao (2 ngày liên tiếp), kháng sinh khi có bội nhiễm phổi/tai',
    primaryEndpoint: 'Phòng ngừa biến chứng viêm phổi, viêm não và tử vong',
    summary: 'Quy trình xử trí sởi mùa dịch, vai trò thiết yếu của Vitamin A giảm biến chứng mù lòa và tử vong ở trẻ em.',
    detailedConclusion: 'Bổ sung Vitamin A ngay khi chẩn đoán cho mọi trẻ mắc sởi theo lứa tuổi.'
  },
  {
    id: '2025-byt-cum-mua',
    title: 'BYT 2025: Hướng dẫn Chẩn đoán và Điều trị Cúm Mùa (Influenza)',
    titleEn: 'National Guidelines on Seasonal Influenza Diagnosis and Management',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2025-byt-cummua.html',
    conditionKey: 'flu',
    icd10: ['J09', 'J10', 'J11'],
    intervention: 'Thuốc ức chế Neuraminidase (Oseltamivir - Tamiflu) chỉ định sớm trong 48 giờ đầu cho đối tượng nguy cơ cao',
    primaryEndpoint: 'Rút ngắn thời gian bệnh, giảm tỷ lệ viêm phổi cúm và suy hô hấp',
    summary: 'Phân loại cúm không biến chứng và cúm có biến chứng/nguy cơ cao (người già, phụ nữ có thai, bệnh phổi mạn).',
    detailedConclusion: 'Khởi đầu Oseltamivir càng sớm càng tốt, không cần chờ kết quả PCR khẳng định ở nhóm nguy cơ cao.'
  },
  {
    id: '2023-byt-covid19',
    title: 'BYT 2023: Hướng dẫn Chẩn đoán và Điều trị COVID-19 (Cập nhật)',
    titleEn: 'National Guidelines on Diagnosis and Treatment of COVID-19',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-covid19.html',
    conditionKey: 'covid19',
    icd10: ['U07.1'],
    intervention: 'Kháng virus (Nirmatrelvir/Ritonavir - Paxlovid, Molnupiravir), Dexamethasone cho ca thở oxy, kháng đông dự phòng LMWH',
    primaryEndpoint: 'Ngăn diễn tiến nặng, giảm tử vong',
    summary: 'Chuyển đổi COVID-19 sang bệnh truyền nhiễm nhóm B, quản lý tập trung nhóm nguy cơ cao và xử trí cơn bão cytokine.',
    detailedConclusion: 'Paxlovid trong 5 ngày đầu cho bệnh nhân nguy cơ cao; Dexamethasone 6mg/ngày chỉ dùng khi bệnh nhân có giảm SpO2.'
  },
  {
    id: '2025-who-viem-mang-nao',
    title: 'WHO 2025: Lộ trình Toàn cầu và Phác đồ Xử trí Cấp cứu Viêm màng não Vi khuẩn',
    titleEn: 'WHO Global Roadmap to Defeat Meningitis and Emergency Management',
    sourceType: 'intl-guideline',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2025,
    organization: 'Tổ chức Y tế Thế giới (WHO)',
    journal: 'Lancet Infect Dis',
    file: '2025-who-viem-mang-nao.html',
    conditionKey: 'neuro',
    icd10: ['G00', 'G00.9'],
    intervention: 'Chọc dò dịch não tủy (CSF) khẩn, Dexamethasone 10mg TM trước hoặc cùng liều kháng sinh đầu tiên, Ceftriaxone/Cefotaxime liều màng não + Vancomycin + Ampicillin (nếu nghi ngờ Listeria)',
    primaryEndpoint: 'Giảm di chứng điếc, tổn thương thần kinh vĩnh viễn và tử vong',
    summary: 'Tiếp cận cấp cứu viêm màng não: Không trì hoãn kháng sinh nếu phải chờ chụp CT scan sọ não; dùng Corticoid trước để giảm phản ứng viêm do ly giải vi khuẩn.',
    detailedConclusion: 'Dexamethasone TM 0.15 mg/kg mỗi 6 giờ x 4 ngày (đặc biệt hiệu quả trong viêm màng não do Phế cầu).'
  },
  {
    id: '2023-byt-marburg',
    title: 'BYT 2023: Hướng dẫn Giám sát và Phòng chống Bệnh do Vi rút Marburg',
    titleEn: 'National Guidelines on Marburg Virus Disease Surveillance and Response',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2023,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2023-byt-marburg.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A98.3'],
    intervention: 'Cách ly nghiêm ngặt cấp 4, phòng hộ PPE toàn thân, hồi sức bù dịch điện giải tích cực, điều trị triệu chứng',
    primaryEndpoint: 'Kiểm soát lây nhiễm chéo bệnh viện, duy trì tưới máu cơ quan',
    summary: 'Hướng dẫn phòng ngừa và kiểm soát bệnh sốt xuất huyết do vi rút Marburg có tỷ lệ tử vong cao.',
    detailedConclusion: 'Tuân thủ nghiêm ngặt kiểm soát nhiễm khuẩn và xử lý chất thải sinh học lây nhiễm cao.'
  },
  {
    id: '2026-byt-ebola',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Bệnh Sốt xuất huyết do Vi rút Ebola',
    titleEn: 'National Guidelines on Ebola Virus Disease Clinical Management',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-ebola.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A98.4'],
    intervention: 'Kháng thể đơn dòng (Inmazeb, Ebanga), tối ưu hóa hồi sức dịch và thăng bằng kiềm toan',
    primaryEndpoint: 'Giảm tỷ lệ tử vong ở bệnh nhân nhiễm Ebolavirus',
    summary: 'Cập nhật liệu pháp kháng thể đặc hiệu và nguyên tắc an toàn sinh học tuyệt đối.',
    detailedConclusion: 'Truyền kháng thể đơn dòng sớm kết hợp hồi sức hỗ trợ tích cực.'
  },
  {
    id: '2026-byt-nipah',
    title: 'BYT 2026: Hướng dẫn Giám sát, Chẩn đoán và Điều trị Bệnh do Vi rút Nipah',
    titleEn: 'National Guidelines on Nipah Virus Encephalitis Management',
    sourceType: 'vn-moh',
    specialty: 'infect',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-nipah.html',
    conditionKey: 'hemorrhagic-fever',
    icd10: ['A98'],
    intervention: 'Hồi sức hô hấp, chống co giật, thuốc kháng virus thử nghiệm (Ribavirin, Remdesivir)',
    primaryEndpoint: 'Kiểm soát viêm não cấp và suy hô hấp',
    summary: 'Hướng dẫn ứng phó bệnh truyền nhiễm lây từ động vật (dơi ăn quả) sang người gây viêm não tử vong cao.',
    detailedConclusion: 'Chẩn đoán xác định bằng RT-PCR; hồi sức nâng đỡ chức năng sống tại phòng cách ly áp lực âm.'
  },

  // --- TIÊU HÓA & GAN MẬT (GASTROENTEROLOGY & HEPATOLOGY) ---
  {
    id: '2026-byt-viem-gan-b',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Điều trị Bệnh Viêm gan Vi rút B (Cập nhật Toàn diện)',
    titleEn: 'National Guidelines on Chronic Hepatitis B Diagnosis and Management (2026 Update)',
    sourceType: 'vn-moh',
    specialty: 'gi',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam (QĐ-BYT)',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-viem-gan-b.html',
    conditionKey: 'hepatitis-b',
    icd10: ['B18.0', 'B18.1', 'B16'],
    intervention: 'Chỉ định thuốc kháng virus uống (NUCs: Tenofovir Alafenamide - TAF, Tenofovir Disoproxil - TDF, Entecavir - ETV), mở rộng tiêu chuẩn điều trị, tầm soát ung thư gan HCC bằng AFP + Siêu âm định kỳ 6 tháng',
    primaryEndpoint: 'Ức chế virus HBV-DNA dưới ngưỡng phát hiện, bình thường hóa ALT, ngăn ngừa xơ gan và HCC',
    summary: 'Quy chuẩn quốc gia mới nhất: Mở rộng chỉ định điều trị NUCs cho bệnh nhân có HBV-DNA cao và ALT tăng nhẹ hoặc có xơ hóa gan F ≥ 2, dự phòng lây truyền mẹ con từ tuần thai 24-28.',
    detailedConclusion: 'Ưu tiên TAF/TDF/ETV là thuốc hàng đầu có hàng rào kháng thuốc cao; không tự ý ngừng thuốc kháng virus khi chưa đạt tiêu chuẩn ngừng an toàn.'
  },
  {
    id: '2026-byt-tom-tat-viem-gan-b',
    title: 'BYT 2026: Tóm tắt Lưu đồ Tiếp cận và Xử trí Nhanh Viêm gan B',
    titleEn: 'Quick Clinical Algorithm for Hepatitis B Management',
    sourceType: 'vn-moh',
    specialty: 'gi',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-tom-tat-viem-gan-b.html',
    conditionKey: 'hepatitis-b',
    icd10: ['B18.1'],
    intervention: 'Lưu đồ 3 bước: Xác định HBsAg -> Đo tải lượng HBV DNA & Men gan -> Đánh giá mức độ xơ hóa (FIB-4 / FibroScan) để quyết định khởi trị',
    primaryEndpoint: 'Hỗ trợ quyết định lâm sàng nhanh cho bác sĩ tuyến cơ sở và đa khoa',
    summary: 'Bảng tra cứu nhanh liều lượng TDF, TAF, ETV và hiệu chỉnh liều theo mức lọc cầu thận eGFR.',
    detailedConclusion: 'Bệnh nhân xơ gan còn bù hoặc mất bù có HBsAg (+) cần điều trị NUCs suốt đời bất kể nồng độ ALT và HBV-DNA.'
  },
  {
    id: '2026-apasl-viem-gan-b',
    title: 'APASL 2026: Đồng thuận Khu vực Châu Á - Thái Bình Dương về Quản lý Viêm gan B',
    titleEn: 'APASL 2026 Consensus Guidelines on the Management of Hepatitis B Virus Infection',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2026,
    organization: 'Asian Pacific Association for the Study of the Liver (APASL)',
    journal: 'J Hepatol',
    file: '2026-apasl-viem-gan-b.html',
    conditionKey: 'hepatitis-b',
    icd10: ['B18.1'],
    intervention: 'Chiến lược Treat-all (Mở rộng tối đa điều trị), theo dõi nồng độ HBsAg định lượng (qHBsAg), tiêu chuẩn "khỏi bệnh chức năng" (Functional Cure)',
    primaryEndpoint: 'Mất HBsAg huyết thanh, giảm tỷ lệ ung thư biểu mô tế bào gan ở chủng tộc Châu Á',
    summary: 'Hướng dẫn thực hành từ hội gan mật hàng đầu châu lục, phù hợp đặc thù dịch tễ học và kiểu gen HBV tại Việt Nam.',
    detailedConclusion: 'Khuyến khích điều trị sớm để bảo vệ tế bào gan và ngăn biến chứng xơ gan tiến triển.'
  },
  {
    id: '2024-byt-vgsvc',
    title: 'BYT 2024: Hướng dẫn Chẩn đoán và Điều trị Viêm gan Vi rút C (HCV)',
    titleEn: 'National Guidelines on Hepatitis C Diagnosis and Treatment with Direct-Acting Antivirals (DAAs)',
    sourceType: 'vn-moh',
    specialty: 'gi',
    design: 'guideline',
    impact: 'regulatory',
    year: 2024,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2024-byt-vgsvc.html',
    conditionKey: 'hepatitis-c',
    icd10: ['B18.2'],
    intervention: 'Thuốc kháng virus tác động trực tiếp toàn pangenotypic (Sofosbuvir/Velpatasvir x 12 tuần hoặc Glecaprevir/Pibrentasvir x 8 tuần)',
    primaryEndpoint: 'Đạt đáp ứng virus bền vững ở tuần thứ 12 sau điều trị (SVR12 > 95-98%) - Khỏi bệnh vi sinh',
    summary: 'Phác đồ điều trị viêm gan C đơn giản hóa không cần xác định kiểu gen (Genotype) cho hầu hết các trường hợp, điều trị an toàn trên cả bệnh nhân suy thận.',
    detailedConclusion: 'Uống đủ liệu trình DAA 8-12 tuần đạt tỷ lệ khỏi bệnh gần như tuyệt đối (> 97%).'
  },
  {
    id: '2018-tg18-viem-tui-mat',
    title: 'Tokyo Guidelines 2018 (TG18): Chẩn đoán, Phân độ nặng và Xử trí Viêm túi mật cấp',
    titleEn: 'Tokyo Guidelines 2018: Diagnostic criteria, severity grading, and management of acute cholecystitis',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2018,
    organization: 'Hội Gan Mật Tụy Nhật Bản (JSHBPS) & Ủy ban TG18',
    journal: 'J Hepatobiliary Pancreat Sci',
    file: '2018-tg18-viem-tui-mat.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K80.0', 'K81.0', 'K80.1'],
    intervention: 'Phẫu thuật cắt túi mật nội soi sớm (< 72h), Dẫn lưu túi mật qua da (PTGBD) / EUS-GBD LAMS cho bệnh nhân nguy cơ cao, Kháng sinh phân tầng theo độ nặng và dừng sau 24h sau mổ độ I/II',
    primaryEndpoint: 'Giảm tỷ lệ tử vong, tỷ lệ biến chứng quanh phẫu thuật, thời gian nằm viện và chi phí điều trị',
    keyResults: 'Lap-C sớm < 72h an toàn; Siêu âm nhạy 82% đặc hiệu 81%; PTGBD giải áp hiệu quả; Dừng KS ≤ 24h sau mổ Độ I/II kiểm soát tốt nhiễm trùng.',
    summary: 'Hướng dẫn kim chỉ nam quốc tế về viêm túi mật cấp: Tiêu chuẩn chẩn đoán TG18/TG13, phân tầng 3 mức độ nặng (Grade I-III), lưu đồ mổ nội soi sớm vs dẫn lưu túi mật cấp cứu, và phác đồ kháng sinh tối ưu.',
    detailedConclusion: 'Cắt túi mật nội soi sớm là lựa chọn hàng đầu cho Độ I và Độ II ở bệnh nhân nguy cơ mổ thấp; PTGBD là can thiệp đầu tay cho Độ III hoặc nguy cơ mổ cao không đáp ứng nội khoa.'
  },
  {
    id: '2018-tg18-viem-duong-mat',
    title: 'Tokyo Guidelines 2018 (TG18): Chẩn đoán, Phân độ nặng và Dẫn lưu Viêm đường mật cấp',
    titleEn: 'Tokyo Guidelines 2018: Diagnostic criteria, severity grading, and management bundles for acute cholangitis',
    sourceType: 'intl-guideline',
    specialty: 'gi',
    design: 'guideline',
    impact: 'practice-changing',
    year: 2018,
    organization: 'Hội Gan Mật Tụy Nhật Bản (JSHBPS) & Ủy ban TG18',
    journal: 'J Hepatobiliary Pancreat Sci',
    file: '2018-tg18-viem-duong-mat.html',
    conditionKey: 'gerd-peptic',
    icd10: ['K83.0', 'K80.3', 'K80.4'],
    intervention: 'Nội soi mật tụy ngược dòng (ERCP) dẫn lưu giải áp sớm/cấp cứu (< 24-48h), PTBD cứu vãn, EUS-BD, gói quản lý 9 bước (Bundles), kháng sinh phổ rộng kỵ khí / Pseudomonas / Enterococcus và dừng sau 4-7 ngày sau dẫn lưu',
    primaryEndpoint: 'Giảm tỷ lệ tử vong 30 ngày từ 3.7% xuống 2.0% ở Độ II, ngăn ngừa sốc nhiễm khuẩn và suy đa tạng',
    keyResults: 'ERCP là can thiệp đầu tay (Grade 1 Level B); EBS và ENBD hiệu quả tương đương (Grade 1 Level A); Dẫn lưu sớm trong 24-48h cứu sống bệnh nhân; Dừng KS sau 4-7 ngày dẫn lưu thành công.',
    summary: 'Hướng dẫn kim chỉ nam quốc tế về viêm đường mật cấp: Tiêu chuẩn chẩn đoán TG18/TG13, phân tầng 3 mức độ nặng, lưu đồ dẫn lưu đường mật khẩn cấp (ERCP/PTBD/EUS-BD), gói quản lý bundles và phác đồ kháng sinh.',
    detailedConclusion: 'Dẫn lưu đường mật giải áp khẩn cấp (ERCP đầu tay) kết hợp hồi sức tạng và kháng sinh là chìa khóa sống còn; chỉ thực hiện lấy sỏi triệt để khi tình trạng viêm cấp đã ổn định.'
  },

  // --- SẢN PHỤ KHOA (OBSTETRICS & GYNECOLOGY) ---
  {
    id: '2026-byt-u-xo-tu-cung',
    title: 'BYT 2026: Hướng dẫn Chẩn đoán và Xử trí U xơ Tử cung (Uterine Fibroids)',
    titleEn: 'National Guidelines on Management of Uterine Leiomyomas',
    sourceType: 'vn-moh',
    specialty: 'obgyn',
    design: 'guideline',
    impact: 'regulatory',
    year: 2026,
    organization: 'Bộ Y tế Việt Nam',
    journal: 'Bộ Y tế Việt Nam',
    file: '2026-byt-u-xo-tu-cung.html',
    conditionKey: 'obgyn',
    icd10: ['D25', 'D25.9'],
    intervention: 'Phân loại vị trí FIGO, theo dõi định kỳ, điều trị nội khoa (Dụng cụ tử cung chứa Levonorgestrel, chất đồng vận/đối vận GnRH), can thiệp nút mạch (UAE), bóc u hoặc cắt tử cung',
    primaryEndpoint: 'Kiểm soát xuất huyết tử cung bất thường (AUB), giảm đau vùng chậu, bảo tồn khả năng sinh sản nếu có nhu cầu',
    summary: 'Hướng dẫn phân loại u xơ theo vị trí cơ tử cung, chỉ định can thiệp phẫu thuật vs điều trị bảo tồn nội khoa cá thể hóa.',
    detailedConclusion: 'U xơ dưới niêm mạc (FIGO 0, 1, 2) gây rong kinh rong huyết ưu tiên can thiệp nội soi buồng tử cung bóc nhân xơ.'
  },

  // --- DƯỢC LÝ & SỬ DỤNG KHÁNG SINH (PHARMACOLOGY) ---
  {
    id: '2026-lww-khang-sinh-co-ban',
    title: 'Nguyên lý Sử dụng Kháng sinh Hợp lý và Cơ chế Đề kháng Vi sinh',
    titleEn: 'Principles of Antimicrobial Therapy and Resistance Mechanisms',
    sourceType: 'intl-study',
    specialty: 'infect',
    design: 'review',
    impact: 'informative',
    year: 2026,
    organization: 'LWW Medical Pharmacology Series',
    journal: 'Lancet Infect Dis',
    file: '2026-lww-khang-sinh-co-ban.html',
    conditionKey: 'icu',
    icd10: ['Z16', 'A41'],
    intervention: 'Phân nhóm kháng sinh diệt khuẩn vs kìm khuẩn, phụ thuộc thời gian (T > MIC) vs phụ thuộc nồng độ (Cmax/MIC, AUC/MIC), quản lý kháng sinh (AMS)',
    primaryEndpoint: 'Tối ưu hiệu quả diệt khuẩn và làm chậm sự phát triển của vi khuẩn đa kháng',
    summary: 'Cẩm nang tra cứu phổ kháng khuẩn của các nhóm kháng sinh chính: Penicillin, Cephalosporin thế hệ 1-5, Carbapenem, Aminoglycoside, Macrolide, Fluoroquinolone.',
    detailedConclusion: 'Áp dụng nguyên tắc 5R trong sử dụng kháng sinh: Đúng bệnh, đúng thuốc, đúng liều, đúng đường dùng, và đúng thời gian.'
  }
];

if (typeof window !== 'undefined') {
  (window as any).KHO_GUIDELINES_STATIC = KHO_GUIDELINES_STATIC;
}
